[Xamarin.Android.Build.Tasks] Fix incremental rebuilds (Take 2!)
Rebuilding the Xamarin.Android.Build.Tasks project would fail:

	$ xbuild
	# works

	# "change a file
	$ touch Tasks/Aapt.cs

	# Rebuild; should work, right?
	$ xbuild
		Tasks/LinkAssemblies.cs(103,32): error CS0117: `Xamarin.Android.Tasks.Profile' does not contain a definition for `SharedRuntimeAssemblies'
		Utilities/MonoAndroidHelper.cs(230,16): error CS0117: `Xamarin.Android.Tasks.Profile' does not contain a definition for `SharedRuntimeAssemblies'

	# wat?

The problem was due to a3dfd4cd *and* 59ec488b:

1. In 59ec488b, `Xamarin.Android.Build.Tasks.targets` was included
    *before* including `$(MSBuildToolsPath)\Microsoft.CSharp.targets`.
    This meant that `$(IntermediateOutputPath)` wasn't set when
    `Xamarin.Android.Build.Tasks.targets` was imported, and thus
    `$(_GeneratedProfileClass)` contained no directory name.

2. In a3dfd4cd, the `@(Compile)` item group was only updated when the
    `_GenerateProfileClass` target was executed, which only happened
    when `$(_GeneratedProfileClass)` didn't exist. This is why it
    works on the initial build but not subsequent builds.

Things worked prior to a3dfd4cd because the `_Foo` target *always*
executed, and thus `@(Compile)` always contained the generated
Profile.g.cs file.

Fix the `<Import/>` ordering issue (1), and instead of updating
`@(Compile)` when the target executes, just add the generated file to
`@(Compile)` within Xamarin.Android.Build.Tasks.csproj (2).