[Mono.Android] add missing property in AndroidMessageHandler
Context: https://github.com/dotnet/runtime/commit/01c4028969fafb927762477d6991c483f3b3cc5c

I found usage of the `ServerCertificateCustomValidationCallback`
property triggered ILLink warnings:

    warning IL2037: System.Net.Http.HttpClientHandler.GetServerCertificateCustomValidationCallback(): No members were resolved for 'get_ServerCertificateCustomValidationCallback'.

This would also fail at runtime.

Going forward:

* Add a test that sets `ServerCertificateCustomValidationCallback`.
* Add `IL2037` to `$(WarningsAsErrors)`

I also found a bug in `Java.Interop-Tests.NET.csproj`, it fails to
build for me:

    external\Java.Interop\tests\Java.Interop-Tests\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attributej]
    external\Java.Interop\tests\Java.Interop-Tests\obj\Debug\Java.Interop-Tests.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attributej]
    external\Java.Interop\tests\Java.Interop-Tests\obj\Debug\Java.Interop-Tests.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attributej]
    external\Java.Interop\tests\Java.Interop-Tests\obj\Debug\Java.Interop-Tests.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attributej]
    external\Java.Interop\tests\Java.Interop-Tests\obj\Debug\Java.Interop-Tests.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attributej]
    external\Java.Interop\tests\Java.Interop-Tests\obj\Debug\Java.Interop-Tests.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attributej]
    external\Java.Interop\tests\Java.Interop-Tests\obj\Debug\Java.Interop-Tests.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attributej]
    external\Java.Interop\tests\Java.Interop-Tests\obj\Debug\Java.Interop-Tests.AssemblyInfo.cs(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attributej]
    tests\Mono.Android-Tests\Java.Interop-Tests\obj\Release\net6.0-android\.NETCoreApp,Version=v6.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attributej]
    tests\Mono.Android-Tests\Java.Interop-Tests\obj\Release\net6.0-android\Java.Interop-Tests.NET.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attributej]
    tests\Mono.Android-Tests\Java.Interop-Tests\obj\Release\net6.0-android\Java.Interop-Tests.NET.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attributej]
    tests\Mono.Android-Tests\Java.Interop-Tests\obj\Release\net6.0-android\Java.Interop-Tests.NET.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attributej]
    tests\Mono.Android-Tests\Java.Interop-Tests\obj\Release\net6.0-android\Java.Interop-Tests.NET.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attributej]
    tests\Mono.Android-Tests\Java.Interop-Tests\obj\Release\net6.0-android\Java.Interop-Tests.NET.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attributej]
    tests\Mono.Android-Tests\Java.Interop-Tests\obj\Release\net6.0-android\Java.Interop-Tests.NET.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attributej]
    tests\Mono.Android-Tests\Java.Interop-Tests\obj\Release\net6.0-android\Java.Interop-Tests.NET.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attributej]
    16 Error(s)

We needed to exclude some `.cs` files in `obj`:

    Exclude="$(JavaInteropTestDirectory)obj\**;$(JavaInteropTestDirectory)bin\**"

I'm unsure how this is currently working on CI.