MOAR LOGGING
Context: good! https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3201349&view=logs&j=8556562a-ae5f-5bd1-7c4d-bf1af4b6f1e1&t=a4d74fbf-7b8e-51d6-b189-8c80ca04a74a
Context:  Bad! https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3201349&view=logs&j=8556562a-ae5f-5bd1-7c4d-bf1af4b6f1e1&t=1ce93f75-3079-5716-18de-288761bcb886

LOGGING FOR THE LOGGING GODS!

The story so far: now we have GREF logs (yay), and can thus see their
creation & destruction.

Conspicuously MISSING, however, is the handle in the exception
message!

	System.NotSupportedException: Unable to activate instance of type
	Xamarin.Forms.Performance.Integration.Droid.MainActivity from native
	handle 0xff88ad3c (key_handle 0x2629e85).

The GREF logs we have DO NOT MENTION 0xff88ad3c nor 0x2629e85.

Compare to the working (JIT-only) iteration, which has a `handle`
statement:

	handle 0x2786; key_handle 0x2629e85: Java Type: `xamarin/forms/performance/integration/MainActivity`; MCW type: `Xamarin.Forms.Performance.Integration.Droid.MainActivity`

This leaves one current scary hypothesis (good for Halloween!):
what if the instance isn't being *activated*?

When a Java Callable Wrapper constructor is executed, the Java side
invokes `mono.android.TypeManager.Activate()`, which is
`Java.Interop.TypeManager.n_Activate()`, which will NOT activate an
instance for a variety of reasons.

Is `TypeManager.n_Activate()` being executed?

If it *is* executed, does it *do* anything?

LOG THE HELL OUT OF IT.

Ditto `TypeManager.CreateInstance()`.

Additionally, update `OSBridge::_monodroid_gref_log()` so that the
message is written to *both* `grefs.txt` AND `adb logcat`, to make it
easier to reason about things when only one or the other is around.
(This should allow the `handle` statement to appear in `adb logcat`.)