[Xamarin.Android.Build.Tasks] use `as` w/ GetRegisteredTaskObject (#5488)
Context: https://github.com/jonathanpeppers/Xamarin.Legacy.Sdk

When working on an experiment that enables multi-targeting such as:

	<Project Sdk="Xamarin.Legacy.Sdk">
	  <PropertyGroup>
	    <TargetFrameworks>monoandroid11.0;net6.0-android</TargetFrameworks>
	  </PropertyGroup>
	</Project>

I got the build error:

	Xamarin.Android.Aapt2.targets(123,3): error MSB4018: The "Aapt2Compile" task failed unexpectedly.
	System.InvalidCastException: [A]Xamarin.Android.Tasks.Aapt2Daemon cannot be cast to [B]Xamarin.Android.Tasks.Aapt2Daemon. Type A originates from 'Xamarin.Android.Build.Tasks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Build.Tasks.dll'. Type B originates from 'Xamarin.Android.Build.Tasks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.win-x64\11.0.200-ci.master.22\tools\Xamarin.Android.Build.Tasks.dll'.
	  at Xamarin.Android.Tasks.Aapt2Daemon.GetInstance(IBuildEngine4 engine, String aapt2, Int32 numberOfInstances, Int32 initalNumberOfDaemons, Boolean registerInDomain)
	  at Xamarin.Android.Tasks.Aapt2.Execute()
	  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
	  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

The cause of the crash is that:

 1. Two different versions of `Xamarin.Android.Build.Tasks.dll` are
    loaded into the process: one version from the "legacy"
    Visual Studio install location, and one from the .NET 6 install.

    This wouldn't be a problem, except-

 2. An instance of `Aapt2Daemon`, from
    `Xamarin.Android.Build.Tasks.dll`, is kept around as "global"
    state via [`IBuildEngine4.RegisterTaskObject()`][0], and-

 3. Code in the "other" `Xamarin.Android.Build.Tasks.dll` retrieves
    the global `Aapt2Daemon` instance, attempting to cast it to the
    "current" `Xamarin.Android.Build.Tasks.dll` copy.

(3) fails, because we're casing to the "wrong" `Aapt2Daemon` type.
(Yes, this is quite odd & confusing, because the two different versions
of the assembly are both loaded & running at the same time.)

A "workaround" is to prefer the use of `as` over explicit casts.
That way, if the "wrong" type is stored globally, the `as` expression
will return `null`, and we'll behave as if there were no cached value.

To increase the utility of the cache, I also added some extension
methods which include the current `Assembly.Location` in the key:

  * `RegisterTaskObjectAssemblyLocal()`
  * `GetRegisteredTaskObjectAssemblyLocal()`
  * `UnregisterTaskObjectAssemblyLocal()`

The inclusion of `Assembly.Location` in the key ensures that we don't
inadvertently obtain the cached data that the "other" assembly stored.

I audited all `GetRegisteredTaskObject()` calls in this repo, and
added comments for the three tasks the usage seemed appropriate.

The following tasks are all able to share their values across
assembly versions:

  * `<ResolveAndroidTooling/>` uses the path to `aapt2` as a key and
    stores `System.Version` in the value.
  * `<ResolveJdkJvmPath/>` uses `JavaSdkPath` as the key and stores
    the string `JdkJvmPath` in the value.
  * `<ValidateJavaVersion/>` uses the path to java/javac as the key
    and stores a string in the value.

[0]: https://docs.microsoft.com/dotnet/api/microsoft.build.framework.ibuildengine4.registertaskobject?view=msbuild-16-netcore