Remap AndroidInterface to DesugarAndroidInterface$_CC
Context: https://github.com/xamarin/xamarin-android/pull/7799#issuecomment-1439020631

`DesugarInterfaceStaticMethod()` (from Java.Interop) fails:

	Java.Lang.NoSuchMethodError : no static method "Lcom/xamarin/interop/AndroidInterface;.getClassName()Ljava/lang/String;"
	   at Java.Interop.JniEnvironment.StaticMethods.GetStaticMethodID(JniObjectReference , String , String )
	   at Java.Interop.JniType.GetStaticMethod(String , String )
	   at Java.Interop.JniPeerMembers.JniStaticMethods.GetMethodInfo(String , String )
	   at Java.Interop.JniPeerMembers.JniStaticMethods.GetMethodInfo(String )
	   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeObjectMethod(String , JniArgumentValue* )
	   at Java.InteropTests.IAndroidInterface.getClassName()
	   at Java.InteropTests.JniPeerMembersTests.DesugarInterfaceStaticMethod()
	   at System.Reflection.MethodInvoker.InterpretedInvoke(Object , IntPtr* )
	   at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
	  --- End of managed Java.Lang.NoSuchMethodError stack trace ---
	java.lang.NoSuchMethodError: no static method "Lcom/xamarin/interop/AndroidInterface;.getClassName()Ljava/lang/String;"
		at crc643df67da7b13bb6b1.TestInstrumentation_1.n_onStart(Native Method)
		at crc643df67da7b13bb6b1.TestInstrumentation_1.onStart(TestInstrumentation_1.java:27)
		at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

This is because `AndroidInterface` isn't desugared, so there is no
`AndroidInterface$-CC` type.

`AndroidInterface` isn't desugared, because it's *empty*.  There are
thus two ways to make `DesugarInterfaceStaticMethod()` work:

 1. Provide an Android-specific `AndroidInterface` type, which contains
    a `static` interface method.  This will cause the type to be
    desugared, creating the `AndroidInterface$-CC` type, and the test
    should thus work.

 2. Use type remapping (f6f11a5a) to remap `AndroidInterface$-CC` to
    `DesugarAndroidInterface$_CC`.

(1) is (somewhat?) "duplicative" of the new test
`SupportDesugaringStaticInterfaceMethods()`.  We could do that, but…
¯\_(ツ)_/¯

Which leaves (2), which is "more interesting".  It's more interesting
in part because it also presents a problem!
`AndroidRuntime.GetStaticMethodFallbackTypesCore()` doesn't support/use
type remapping!  Meaning that even if we have a `<replace-type/>`
to map `AndroidInterface` to `DesugarAndroidInterface$_CC`, that
remapping won't be used!

🧐

Update `AndroidRuntime.GetStaticMethodFallbackTypesCore()` so that
the returned types are *after* calling
`AndroidRuntime.GetReplacementTypeCore()`, which looks up
`<replace-type/>` values.  This (should?) allow use to remap
`AndroidInterface` with `DesugarAndroidInterface$_CC`, allowing the
`DesugarInterfaceStaticMethod()` test to pass. 🤞