Bump to mono/2017-04/cb694fad
In our continuing series of commits to fix building with mono/2017-04,
the [most recent build failure][0] is a *linker* error due to the use
of `inline` functions:

	./.libs/libmini.a(libmini_la-tramp-amd64.o):…/xamarin-android/external/mono/mono/mini/tramp-amd64.c:746:
	undefined reference to `mono_arch_unwindinfo_get_size'

This should be resolved in mono/2017-04/cb694fad, which makes the
offending `inline` functions `static inline` instead.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/388/