[jnimarshalmethod-gen] Fix moved array type references (#351)
When running `jnimarshalmethod-gen.exe` on an assembly multiple times:

	$ mono jnimarshalmethod-gen.exe Mono.Android.dll ...
	$ mono jnimarshalmethod-gen.exe Mono.Android.dll ...

The second invocation could fail with a `TypeLoadException`:

	Error: jnimarshalmethod-gen: Unable to process assembly '…/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v8.1/Mono.Android.dll'
	VTable setup of type Org.Apache.Http.Impl.IO.AbstractSessionOutputBufferInvoker failed
	System.TypeLoadException: VTable setup of type Org.Apache.Http.Impl.IO.AbstractSessionOutputBufferInvoker failed
	  at (wrapper managed-to-native) System.RuntimeType.GetMethodsByName_native(System.RuntimeType,intptr,System.Reflection.BindingFlags,bool)
	  at System.RuntimeType.GetMethodsByName (System.String name, System.Reflection.BindingFlags bindingAttr, System.Boolean ignoreCase, System.RuntimeType reflectedType)
	  at System.RuntimeType.GetMethodCandidates (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.CallingConventions callConv, System.Type[] types, System.Boolean allowPrefixLookup)
	  at System.RuntimeType.GetMethods (System.Reflection.BindingFlags bindingAttr)
	  at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.CreateMarshalMethodAssembly (System.String path)
	  at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.ProcessAssemblies (System.Collections.Generic.List`1[T] assemblies)

The `TypeLoadException` occurred because `jnimarshalmethod-gen.exe`
was breaking some of the array type references.  For example,
`byte[][]` became `byte[]`, and sometimes we lost the `ArrayType`,
so `T[]` sometimes became `T`.

Fix array handling so that array types are appropriately generated.