[xaprepare] add more retry logic
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4156676&view=logs&j=996c69ec-9601-56aa-a920-9140ba1f716a&t=32be717a-abee-54ef-d1a3-effe9a871c31&l=116

We still occasionally get failures on CI such as:

    Downloading NuGet
    Step Xamarin.Android.Prepare.Step_DownloadNuGet failed: An error occurred while sending the request.
    System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_DownloadNuGet failed: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 152.199.4.184:443
        at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
        at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
        at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
        --- End of inner exception stack trace ---
        at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
        at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
        --- End of inner exception stack trace ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Xamarin.Android.Prepare.Utilities.<GetDownloadSizeWithStatus>d__35.MoveNext() in C:\a\1\s\build-tools\xaprepare\xaprepare\Application\Utilities.cs:line 439
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Xamarin.Android.Prepare.Step_DownloadNuGet.<Execute>d__1.MoveNext() in C:\a\1\s\build-tools\xaprepare\xaprepare\Steps\Step_DownloadNuGet.cs:line 30
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Xamarin.Android.Prepare.Step.<Run>d__17.MoveNext() in C:\a\1\s\build-tools\xaprepare\xaprepare\Application\Step.cs:line 42
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Xamarin.Android.Prepare.Scenario.<Run>d__26.MoveNext() in C:\a\1\s\build-tools\xaprepare\xaprepare\Application\Scenario.cs:line 37
        --- End of inner exception stack trace ---
        at Xamarin.Android.Prepare.Scenario.<Run>d__26.MoveNext() in C:\a\1\s\build-tools\xaprepare\xaprepare\Application\Scenario.cs:line 48
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Xamarin.Android.Prepare.Context.<Execute>d__202.MoveNext() in C:\a\1\s\build-tools\xaprepare\xaprepare\Application\Context.cs:line 815
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at Xamarin.Android.Prepare.App.<Run>d__3.MoveNext() in C:\a\1\s\build-tools\xaprepare\xaprepare\Main.cs:line 164

I added retry logic to the `GetDownloadSizeWithStatus()` method. I
also renamed the `IOExceptionRetryInitialDelay` and
`IOExceptionRetries` variables to be general purpose.

I went back and improved upon my changes in 51f16187, so that it uses
the `WaitAWhile()` as used in other places.