Merge in radekdoulik/apkdiff/master@dc6cfc4 (#4539)
Changes: https://github.com/radekdoulik/apkdiff/compare/3a479d...dc6cfc

  * radekdoulik/apkdiff@dc6cfc4: Update the handling of an unknown option
  * radekdoulik/apkdiff@3b825e6: Handle unknown option
  * radekdoulik/apkdiff@8975470: Support aab packages
  * radekdoulik/apkdiff@8122150: Add new regression options
  * radekdoulik/apkdiff@fbac824: Use thousand separator in regression prints
  * radekdoulik/apkdiff@e5aef10: Count regression failures and report the count
  * radekdoulik/apkdiff@11ba628: Added assembly size regression testing
  * radekdoulik/apkdiff@e7ee8e9: Added apk size regression testing implementation
  * radekdoulik/apkdiff@b959951: Set platform target
  * radekdoulik/apkdiff@a74d022: Fix white space
  * radekdoulik/apkdiff@3afd5a7: Print also percentage in package size difference
  * radekdoulik/apkdiff@fd8d3e0: Show assemblies and shared libraries total differences in summary
  * radekdoulik/apkdiff@130598f: Add section sizes example
  * radekdoulik/apkdiff@b1ee9a6: Update LibZipSharp to newer version
  * radekdoulik/apkdiff@d84b35e: Compare shared libraries section sizes
  * radekdoulik/apkdiff@3a3ceb3: Added another example output
  * radekdoulik/apkdiff@4e094f5: Add initial assembly comparison
  * radekdoulik/apkdiff@7efe903: Compare shared libraries symbols and their sizes
  * radekdoulik/apkdiff@fcac80f: Improve csproj file

Besides the other changes we want the regression testing.

Example output:

	$ apkdiff.exe --test-apk-size-regression=51200 --test-assembly-size-regression=51200 Xamarin.Forms_Performance_Integration-Signed-Release.apkdesc bin\TestDebug\Xamarin.Forms_Performance_Integration-Signed.apk
	Size difference in bytes ([*1] apk1 only, [*2] apk2 only):
	  +  26,749,952 assemblies/Mono.Android.dll
	Error: apkdiff: Assembly 'assemblies/Mono.Android.dll' size increase 26,749,952 is 26,698,752 bytes more than the threshold 51,200.
	  +  14,655,424 assemblies/Mono.Android.pdb *2
	  +   2,423,388 lib/x86/libmonosgen-2.0.so
	  +   2,413,568 assemblies/mscorlib.dll
	Error: apkdiff: Assembly 'assemblies/mscorlib.dll' size increase 2,413,568 is 2,362,368 bytes more than the threshold 51,200.
	  +   2,025,076 classes.dex
	  +   1,755,580 lib/armeabi-v7a/libmonosgen-2.0.so
	  +   1,683,644 assemblies/mscorlib.pdb *2
	  +   1,511,544 assemblies/Xamarin.Android.Support.v7.AppCompat.dll
	Error: apkdiff: Assembly 'assemblies/Xamarin.Android.Support.v7.AppCompat.dll' size increase 1,511,544 is 1,460,344 bytes more than the threshold 51,200.
	...
	Summary:
	  +  43,001,792 Assemblies 303.25% (of 14,180,480)
	  +  10,653,224 Shared libraries 89.86% (of 11,855,444)
	  +  66,973,060 Package size difference 318.80% (of 21,007,581)
	Error: apkdiff: PackageSize increase 66,973,060 is 66,921,860 bytes more than the threshold 51,200. apk1 size: 21,007,581 bytes, apk2 size: 87,980,641 bytes.
	Error: apkdiff: Size regression occured, 39 check(s) failed.