[build] Fix Homebrew/openssl (#5387)
Context: https://github.com/actions/virtual-environments/issues/1811

Recently some CI builds are ending early, because Homebrew is failing
like this:

    Installing automake
    ...
    stderr | Error: Not a directory @ dir_s_rmdir - /usr/local/Cellar/openssl
     | Removing: /usr/local/Cellar/openssl/1.0.2t... (1,787 files, 12MB)

    Error: Installation of automake failed

Apply the suggested workaround to fix this for now while we wait for
updated macOS images.