[Xamarin.Android.Build.Tasks] Fix issue where app will not install (#7719)
Fixes: https://dev.azure.com/DevDiv/DevDiv/_workitems/edit/1398544

It is quite common for users to switch between Debug and Release
configurations in order to test the app.  However, if the `Release`
build is using a custom signing keystore you will generally see this
warning and error:

	warning MSB6006: "adb" exited with code 1.
	[BT : 1.8.1] error : Installation of the app failed.

This is not entirely helpful, since you often need to dig into the
diagnostic log to figure out what the actual issue is.

This warning is produced when we try to run
`adb uninstall -k @PACKAGE_NAME@`:

	adb uninstall -k com.xamarin.example
	The -k option uninstalls the application while retaining the data/cache.
	At the moment, there is no way to remove the remaining data.
	You will have to reinstall the application with the same signature, and fully uninstall it.
	If you truly wish to continue, execute 'adb shell cmd package uninstall -k'.

We are not entirely sure why the application gets into this state,
but once it does you have to completely uninstall it.  We currently
ignore this error but that then results in the following error:

	Error: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.xamarin.example signatures do not match newer version; ignoring!

This is because the apps used different signing keystores.  As a
result they are incompatible.  The only option once you get this issue
is to uninstall the app manually and try again.  However the error
messaging is not obvious so users generally have no idea what to do.

Fix a few things in this area. Introduce a new `<AndroidAdb/>` task
which is responsible for making the calls to `adb`.  We previously used
`<Exec/>`, which made it hard to make any customizations around error
messaging.  We will check the result of the `<AndroidAdb/>` task when
calling `adb uninstall -k @PACKAGE_NAME@` and if the output contains
`adb shell cmd package uninstall` then we will automatically call
`adb shell cmd package uninstall @PACKAGE_NAME@`.  This will completely
remove the app from the device and will allow the later `bundletool`
invocation to work.

We have also updated `<InstallApkSet/>` to look for error messages from
`bundletool` and report them, so users will get better information.
We now generate error messages like:

	[BT : 1.8.1] error : Installation of the app failed.
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: The APKs have been extracted in the directory: /var/folders/5p/10yqy2kx6r9dnmnxh_nt6s0r0000gn/T/1389125984700138671
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 01:54:24 E/SplitApkInstallerBase: Failed to commit install session 1426763565 with command cmd package install-commit 1426763565. Error: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.xamarin.toggledebugreleasewithsigning signatures do not match newer version; ignoring!
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: [BT:1.8.1] Error: Installation of the app failed.
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: com.android.tools.build.bundletool.model.exceptions.CommandExecutionException
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000:  Installation of the app failed.
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:192)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$2(InstallApksCommand.java:214)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:81)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:43)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:214)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: Caused by: com.android.ddmlib.InstallException: Failed to commit install session 1426763565 with command cmd package install-commit 1426763565. Error: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.xamarin.toggledebugreleasewithsigning signatures do not match newer version; ignoring!
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.ddmlib.SplitApkInstallerBase.installCommit(SplitApkInstallerBase.java:99)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:85)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.ddmlib.internal.DeviceImpl.installPackages(DeviceImpl.java:1166)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:176)
	obj/Release/android/bin/com.xamarin.toggledebugreleasewithsigning.apks : java error BT0000: 	... 6 more

Unit Test are added.