[ci] Use Microsoft.SourceLink.GitHub (#1030)
Context: https://github.com/xamarin/xamarin-android/commit/7b4d4b8c235b22b688db13e59771722da89f37cb
Context: https://github.com/dotnet/sourcelink#githubcom-and-github-enterprise
Context: https://www.hanselman.com/blog/exploring-net-cores-sourcelink-stepping-into-the-source-code-of-nuget-packages-you-dont-own

Changes: http://github.com/xamarin/xamarin-android-tools/compare/fc3c2ac191a47715bc58e110ef28f38009158416...29f11f2a304376bfa96de999a78083fe5a8174c6

  * xamarin/xamarin-android-tools@29f11f2: Bump to mono/mono.posix@d8994ca, xamarin/LibZipSharp@98e9173 (#193)
  * xamarin/xamarin-android-tools@7cfe683: [ci] Use Microsoft.SourceLink.GitHub (#192)
  * xamarin/xamarin-android-tools@01a0dde: [Localization] Import translated resx files (#189)
  * xamarin/xamarin-android-tools@cc715d9: [Xamarin.Android.Tools.AndroidSdk] Permit NDK r25 (#190)
  * xamarin/xamarin-android-tools@3c55e9a: Avoid `Environment.SpecialFolder.ApplicationData` (#188)
  * xamarin/xamarin-android-tools@0d55472: LEGO: Merge pull request 187
  * xamarin/xamarin-android-tools@6946512: Juno: check in to juno/hb_befb220e-87ce-47e9-a9e6-10ea592b2337_20220729154833425. (#186)
  * xamarin/xamarin-android-tools@6e3433a: Juno: check in to juno/hb_befb220e-87ce-47e9-a9e6-10ea592b2337_20220729025332507. (#185)
  * xamarin/xamarin-android-tools@73c4388: [Xamarin.Android.Tools.AndroidSdk] Update SDK component for API-33 (#184)
  * xamarin/xamarin-android-tools@da3653e: [Xamarin.Android.Tools.AndroidSdk] Add API-33 to KnownVersions
  * xamarin/xamarin-android-tools@327d433: [ci] Run OneLocBuild on a schedule (#180)
  * xamarin/xamarin-android-tools@8ab60e4: [ci] Use latest macOS and Windows images (#181)
  * xamarin/xamarin-android-tools@4dd3292: LEGO: Merge pull request 182
  * xamarin/xamarin-android-tools@56b61f1: [Localization] Add OneLocBuild job (#175)
  * xamarin/xamarin-android-tools@14076a6: [Xamarin.Android.Tools.AndroidSdk] Add API-32 to KnownVersions
  * xamarin/xamarin-android-tools@9c641b3: [Xamarin.Android.Tools.AndroidSdk] Update SDK component for API-32 (#169)
  * xamarin/xamarin-android-tools@ec346d0: [Xamarin.Android.Tools.AndroidSdk] Permit NDK r24 (#171)
  * xamarin/xamarin-android-tools@47832f1: [Xamarin.Android.Tools.AndroidSdk] AndroidSdkInfo validation locator (#170)
  * xamarin/xamarin-android-tools@20f6112: Bump LibZipSharp to 2.0.4 (#166)
  * xamarin/xamarin-android-tools@e4f0d59: Add support for writing android:roundIcon to Android manifest (#162)

Add a reference to the [Microsoft.SourceLink.GitHub NuGet package][0]
to `src/*/*.csproj` and `tools/*/*.csproj` so that `*.pdb` such as
`Java.Interop.pdb` contain URLs to facilitate debugging into their
corresponding assemblies without needing to checkout and build the
`Java.Interop` repo locally:

	% dotnet tool install --global SourceLink --version 3.1.1

	% $HOME/.dotnet/tools/sourcelink print-urls bin/Debug-net7.0/Java.Interop.pdb
	c1eaa3b7ef9a7354080ca02e56f5052a7b04fcf78298210fb69a1c05c5827c3d sha256 csharp /Volumes/Xamarin-Work/src/xamarin/Java.Interop/src/Java.Interop/GlobalSuppressions.cs
	https://raw.githubusercontent.com/jonpryor/Java.Interop/661b599c7ae1b80a20e482f397190b50a028f7d1/src/Java.Interop/GlobalSuppressions.cs
	…

	% $HOME/.dotnet/tools/sourcelink test bin/Debug-net7.0/Java.Interop.pdb
	3 Documents with errors:
	983b6f609d1a601d57df96467aafe6a0cc6173a23d261f98ad582d16983259a9 sha256 csharp /Volumes/Xamarin-Work/src/xamarin/Java.Interop/src/Java.Interop/obj/Debug/net7.0/JniEnvironment.g.cs
	https://raw.githubusercontent.com/jonpryor/Java.Interop/661b599c7ae1b80a20e482f397190b50a028f7d1/src/Java.Interop/obj/Debug/net7.0/JniEnvironment.g.cs
	error: url failed NotFound: Not Found
	9596da901062cf5add81d66c23696ca92bbfa59c82fe10f4f06d45292e2cb0ff sha256 csharp /Volumes/Xamarin-Work/src/xamarin/Java.Interop/src/Java.Interop/obj/Debug/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.cs
	https://raw.githubusercontent.com/jonpryor/Java.Interop/661b599c7ae1b80a20e482f397190b50a028f7d1/src/Java.Interop/obj/Debug/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.cs
	error: url failed NotFound: Not Found
	508b170eae1ea8b281b2a892293c0b1f2b1ee67db1bd8ce89036541d3f121643 sha256 csharp /Volumes/Xamarin-Work/src/xamarin/Java.Interop/src/Java.Interop/obj/Debug/net7.0/Java.Interop.AssemblyInfo.cs
	https://raw.githubusercontent.com/jonpryor/Java.Interop/661b599c7ae1b80a20e482f397190b50a028f7d1/src/Java.Interop/obj/Debug/net7.0/Java.Interop.AssemblyInfo.cs
	error: url failed NotFound: Not Found
	sourcelink test failed

These errors are expected, as they are generated files.

[0]: https://www.nuget.org/packages/Microsoft.SourceLink.GitHub