[generator] Use the *real* Mono.Options.
The Mono.Options-PCL package not only doesn't support enumerations,
but it doesn't support nullable types either!

Consequently, when running `generator --product-version=6`, it would
error out with:

	System.IndexOutOfRangeException: Index was outside the bounds of the array.
	  at Mono.Options.Option.Parse[T] (System.String value, Mono.Options.OptionContext c) [0x00059] in .../Java.Interop/tools/generator/Mono.Options-PCL.cs:533
	  at Mono.Options.OptionSet+ActionOption`1[T].OnParseComplete (Mono.Options.OptionContext c) [0x00014] in .../Java.Interop/tools/generator/Mono.Options-PCL.cs:936
	  at Mono.Options.Option.Invoke (Mono.Options.OptionContext c) [0x00003] in .../Java.Interop/tools/generator/Mono.Options-PCL.cs:631
	  at Mono.Options.OptionSet.ParseValue (System.String option, Mono.Options.OptionContext c) [0x000aa] in .../Java.Interop/tools/generator/Mono.Options-PCL.cs:1150
	  at Mono.Options.OptionSet.Parse (System.String argument, Mono.Options.OptionContext c) [0x000a8] in .../Java.Interop/tools/generator/Mono.Options-PCL.cs:1125
	  at Mono.Options.OptionSet.Parse (IEnumerable`1 arguments) [0x000c1] in .../Java.Interop/tools/generator/Mono.Options-PCL.cs:1015
	  at Xamarin.Android.Binder.CodeGeneratorOptions.Parse (System.String[] args) [0x0034c] in .../Java.Interop/tools/generator/CodeGenerator.cs:146
	  at Xamarin.Android.Binder.CodeGenerator.Main (System.String[] args) [0x00002] in .../Java.Interop/tools/generator/CodeGenerator.cs:191

Dump Mono.Options-PCL and use the "real" Mono.Options Nuget package.
That allows proper parsing of nullable types and enumerations and...