[build] Build the latest stable platform.
Commit 01988e08 broke `ResolveSdks` because it forced
the system to build the v1.0 and v9.0 apis. v9.0 is
unstable, as a result the following exception occurs

	The "ResolveSdks" task failed unexpectedly.
	System.NullReferenceException: Object reference not set to an instance of an object

This is because there are NO stable api's available.

This commit resets the system to build the latest stable api.