[xaprepare] Switch to AdoptOpenJDK distribution of OpenJDK 1.8 (#5836)
Context: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

On 20201-04-12, most CI builds started failing:

	Downloading JetBrains OpenJDK from https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbrsdk-8u202-osx-x64-b1483.37.tar.gz
	  Error: Failed to obtain JetBrains OpenJDK size. HTTP status code: Forbidden (403)

The JetBrains OpenJDK 1.8 packages we've been using since c8ab4555
will not be downloadable starting on May 1, 2021, as Bintray is
deprecated and will be shut down.

CI builds failed on April 12 because Bintray downloads resulted in
HTTP-403 errors in order to bring attention to their deprecation:

> We will have some short service brown-outs to remind users about
> the services that are going away on May 1st.

Switch to Switch to [Adopt OpenJDK 1.8][0] packages instead.

[0]: https://adoptopenjdk.net/