[build] remove usage of ant (#3696)
Context: http://build.azdo.io/3085600
Context: https://github.com/Homebrew/homebrew-core/issues/44608

On 2019-Sep-26, or thereabouts, we started seeing this build error:

	==> Downloading https://www-us.apache.org/dist/commons/bcel/binaries/bcel-6.3.1-bin.tar.gz
	stderr | curl: (22) The requested URL returned error: 404 Not Found
	stderr | Error: An exception occurred within a child process:
	stderr |   DownloadError: Failed to download resource "ant--bcel"
	stderr | Download failed: https://www-us.apache.org/dist/commons/bcel/binaries/bcel-6.3.1-bin.tar.gz
	Error: Installation of ant failed

This is coming from `brew install ant`.  Apparently, something
related to the [Homebrew `ant` Formulae][0] has broken recently, and
all attempts to use Homebrew to install `ant` are failing, worldwide.

Looking into it, we only use `ant` and a related `<Ant/>` task to
build `src/proguard`, and ProGuard has instructions to instead build
with `maven`, `gradle`, and `javac` (among others).  Meaning we don't
actually *need* `ant` *at all*.

I reworked `src/proguard` to be built with `gradle`, the same way we
are building `r8.jar`.  This allows us to not need `ant` anymore, and
thus avoid the `brew install ant` error.

[0]: https://formulae.brew.sh/formula/ant