[generator] More AttributeTargets on SupportedOSPlatformAttribute (#1054)
Context: 31c83fb56a8f98e503796a8389af8c32fae40566
Context: https://github.com/xamarin/xamarin-android/pull/7478
Context: https://github.com/buyaa-n/runtime/blob/7a62a22db186fda42dad6cbd681cf056fcf6aee6/src/libraries/System.Private.CoreLib/src/System/Runtime/Versioning/PlatformAttributes.cs#L52-L62

In order to compile classic MonoAndroid bindings that contain the new
.NET `[SupportedOSPlatform]` attributes, we have a dummy copy that we
can compile against.  However this copy does not allow
`AttributeTargets.Field`, so compiling with 31c83fb5 causes:

	/Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-33/mcw/Dalvik.Bytecode.IOpcodes.cs(646,4):
	error CS0592: Attribute global::System.Runtime.Versioning.SupportedOSPlatformAttribute' 
	is not valid on this declaration type. It is only valid on 'assembly, module, 
	class, struct, constructor, method, property, indexer, event' declarations. 

Update our copy to have the same `AttributeTargets` as the .NET
version so we can compile on classic.