[One .NET] produce 31, 32, 33 packs (#7187)
Context: https://github.com/xamarin/xamarin-android/issues/7183
Context: https://bugzilla.xamarin.com/11/1114/bug.html
Context: https://bugzilla.xamarin.com/23/2367/bug.html
Context: https://github.com/xamarin/monodroid/commit/8c03aba6aabeec7fbd5a7425aeff9d73a4a19952
Context: https://github.com/xamarin/monodroid/commit/78ab9b5539d031ff3c334430295b6e2fcb346498
Context: https://github.com/xamarin/monodroid/commit/6679dfc62eae462b5acc9deb095d0fa41786f80b

**Background**: Java Callable Wrapper (JCW) constructors!  Consider the
following C# class:

	public class MyThread1 : Java.Lang.Thread {
	}

This type has one constructor: the implicit default constructor.

How many constructors does the JCW contain?

At least 8:

	// Java
	public /* partial */ class MyThread1 extends java.lang.Thread /* … */ {
	    public MyThread1();
	    public MyThread1(Rnnable target);
	    public MyThread1(ThreadGroup group, Runnable target);
	    public MyThread1(String name);
	    public MyThread1(ThreadGroup group, String name);
	    public MyThread1(Runnable target, String name);
	    public MyThread1(ThreadGroup group, Runnable target, String name);
	    public MyThread1(ThreadGroup group, Runnable target, String name, long stackSize);
	}

Wait, what?  *Why*?  Constructor generation is unexpectedly hard.

Aside: consider the binding for the `Thread(String)` constructor:

	/* partial */ class Thread : Object, IRunnable {
	    [Register (".ctor", "(Ljava/lang/String;)V", "")]
	    public unsafe Thread (string name) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
	    {
	        const string __id = "(Ljava/lang/String;)V";

	        if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
	            return;

	        IntPtr native_name = JNIEnv.NewString ((string?)name);
	        try {
	            JniArgumentValue* __args = stackalloc JniArgumentValue [1];
	            __args [0] = new JniArgumentValue (native_name);
	            var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
	            SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
	            _members.InstanceMethods.FinishCreateInstance (__id, this, __args);
	        } finally {
	            JNIEnv.DeleteLocalRef (native_name);
	        }
	    }
	}

The key part are the calls to
[`JniPeerMembers.JniInstanceMethods.StartCreateInstance()`][0] and
[`JniPeerMembers.JniInstanceMethods.FinishCreateInstance()`][1], which:

 1. Gets the JCW corresponding to the *runtime* type `this.GetType()`,
    i.e. `MyThread1`

 2. Looks up the Java-side constructor on the JCW from (1) which has
    the JNI signature in `__id`.

For `MyThread1`, this will lookup the `MyThread1()` default
constructor in the JCW.

Now consider `MyThread2`:

	// C#
	public class MyThread2 : Thread {
	    public MyThread2()
	        : base ("name)
	    {
	    }
	}

Here, the `MyThread2()` default constructor invokes the
`Java.Lang.Thread(string)` constructor, which will attempt to find
the Java Callable Wrapper constructor `MyThread2(String)`!  This in
turn requires that the `MyThread2(String)` constructor exist.

We cannot have a "direct" relationship between the managed type and
the Java Callable Wrapper.  *At minimum*, there needs to be a
`MyThread2(String)` constructor, even though `MyThread2` doesn't have
such a constructor.

The only way to know which constructors need to be generated is by
disassembling the IL to see which constructor is invoked, which was
more work than we wanted to do.

So what we instead do is emit *all possible constructor overloads*.
This ensures that the `MyThread2(String)` JCW constructor will exist
when needed, at the cost of extra unusable constructors also existing.

So far so good; things have worked this way for over 10 years.

**The scenario**:

 1. Create a new default .NET 6 project, using the default
    `$(TargetFramework)` value of `net6.0-android` (API-31):

        dotnet new android

 2. Add a `Java.Lang.Thread` subclass to the new project:

        public class MyThread : Java.Lang.Thread {
        }

 3. Build!

Expected results: it builds.

Actual results: it fails (?!):

	obj\Debug\net6.0-android\android\src\crc6474063b540de74d1e\RenderingThread.java(76,3): error JAVAC0000:  error: no suitable constructor found for Thread(ThreadGroup,Runnable,String,long,boolean)
	  super (p0, p1, p2, p3, p4);
	constructor Thread.Thread() is not applicable
	  (actual and formal argument lists differ in length)
	constructor Thread.Thread(Runnable) is not applicable
	  (actual and formal argument lists differ in length)
	constructor Thread.Thread(ThreadGroup,Runnable) is not applicable
	  (actual and formal argument lists differ in length)
	constructor Thread.Thread(String) is not applicable
	  (actual and formal argument lists differ in length)
	constructor Thread.Thread(ThreadGroup,String) is not applicable
	  (actual and formal argument lists differ in length)
	constructor Thread.Thread(Runnable,String) is not applicable
	  (actual and formal argument lists differ in length)
	constructor Thread.Thread(ThreadGroup,Runnable,String) is not applicable
	  (actual and formal argument lists differ in length)
	constructor Thread.Thread(ThreadGroup,Runnable,String,long) is not applicable
	  (actual and formal argument lists differ in length)

**Discussion**: This build break is caused by the combination of:

 1. Commit df6c716e, which binds API-33 and declares it stable, and
 1. Commit 0ab3db07, wherein we decreed that when building an App
    project, the App is packaged against the *latest runtime pack*. 

(1) adds a new `Java.Lang.Thread` constructor from API-33:
[`Thread(ThreadGrouop, Runnable, String, long, boolean)`][2].

(2) means that the app, which was *built against* API-31, is
*packaged against* API-33.  This in turn means that the JCWs are
generated from an API-33 source, and thus the new API-33 constructor
is emitted as one of the `MyThread` constructors.  This in turn
requires that the app be built against an API-33 `android.jar`, which
isn't used because `$(TargetFramework)` specifies API-31.

**The workaround**: set `$(TargetFramework)`=net6.0-android33.0.

**The fix**: 

Update `Mono.Android.Apis.projitems` to now contains
`%(AndroidApiInfo.DotNetSupported)` item metadata for each API level:

	<AndroidApiInfo Include="v11.0">
	  <Name>R</Name>
	  <Level>30</Level>
	  <Id>30</Id>
	  <Stable>True</Stable>
	  <DotNetSupported>False</DotNetSupported>
	</AndroidApiInfo>
	<AndroidApiInfo Include="v12.0">
	  <Name>S</Name>
	  <Level>31</Level>
	  <Id>31</Id>
	  <Stable>True</Stable>
	  <DotNetSupported>True</DotNetSupported>
	</AndroidApiInfo>

We will now build .NET runtime packs whenever
`%(AndroidApiInfo.DotNetSupported)`=True, specifically for API-31,
API-32, and API-33.  We will ship these going forward.

The workload now installs API-31 runtime packs by default.
The API-32 and API-33 runtime packs can be restored from NuGet, or
via the `android-32` or `android-33` workloads.

I added a test for this scenario that validates the runtime pack used
during a build.

I will port these changes to xamarin-android/main in a future PR.

[0]: https://github.com/xamarin/java.interop/blob/247145e4eed6d7c8dcef947a657f88da6663ad69/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs#L129-L144
[1]: https://github.com/xamarin/java.interop/blob/247145e4eed6d7c8dcef947a657f88da6663ad69/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs#L162-L175
[2]: https://developer.android.com/reference/java/lang/Thread#Thread(java.lang.ThreadGroup,%20java.lang.Runnable,%20java.lang.String,%20long,%20boolean)