Bump to dotnet/dotnet/main@ca3dd2c2d9 10.0.100-rc.1.25412.102 (#10397)
Changes: https://github.com/dotnet/dotnet/compare/8b29a16822...ca3dd2c2d9

- **Updates**:
  - From [10.0.0-beta.25401.103 to 10.0.0-beta.25412.102][2]
    - Microsoft.DotNet.Build.Tasks.Feed
  - From [0.11.5-alpha.25401.103 to 0.11.5-alpha.25412.102][2]
    - Microsoft.DotNet.Cecil
  - From [10.0.0-rc.1.25401.103 to 10.0.0-rc.1.25412.102][2]
    - Microsoft.NET.ILLink.Tasks
    - Microsoft.NETCore.App.Ref
  - From [10.0.100-rc.1.25401.103 to 10.0.100-rc.1.25412.102][2]
    - Microsoft.NET.Sdk
  - From [10.0.100-preview.7.25401.103 to 10.0.100-rc.1.25412.102][2]
    - Microsoft.TemplateEngine.Authoring.Tasks

[2]: https://github.com/dotnet/dotnet/compare/8b29a16822...ca3dd2c2d9

Other changes:

* Temporarily disable `$(VerifyReferenceTrimCompatibility)`

* Temporarily disable `$(VerifyReferenceAotCompatibility)`

* Remove many `HACK`'s from NativeAOT support, as we have proper
  runtime packs for NativeAOT now

One new `HACK` is required to include Android RIDs for:

* https://github.com/dotnet/sdk/blob/2a4195bb70f47c15ff9e6d848c59517dc873e0f4/src/Layout/redist/targets/GenerateBundledVersions.targets#L397-L403

* Fix `CS9273` for `field` keyword

Handle `field` keyword:

    src\Mono.Android\Android.App\Application.cs(23,13): error CS9273: In language version 14.0, 'field' is a keyword within a property accessor. Rename the variable or use the identifier '@field' instead.

Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>