Bump to Mono.Cecil 0.11.4.
Hopefully fixes a [build break][0]:

	CSC : error CS1705: Assembly 'illink' with identity 'illink, Version=6.0.100.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
	uses 'Mono.Cecil, Version=0.11.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'
	which has a higher version than referenced assembly
	'Mono.Cecil' with identity 'Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'

Bump `$(MonoCecilVersion)` to compensate?

Note: an actual fix very likely requires a Java.Interop bump, as
Java.Interop references Cecil 0.11.3 (same as the error message)
while `$(MonoCecilVersion)` is 0.11.2 (not present in the error).

[0]: https://github.com/xamarin/xamarin-android/pull/6131#pullrequestreview-716413727