[dependencies] Install Mono 5.2.0.114
Commit 986869bc [didn't work as desired][0]:

	Error: --arch=32 Failed to switch to 'mono32'.

(It worked locally! Because my `$PATH` was messed up.)

The problem is that `mono --arch=32` **exec**(2)'s `mono32`, but
`mono32` wasn't a whitelisted binary installed into
`Mono.framework/Versions/Current/Commands`, which is the directory
that `$PATH` contains on the Jenkins machines.

Thus, `mono32` couldn't be found, and `MonoAotOffsetsDumper.exe`
couldn't be executed, and I'm a sad panda.

Install and use Mono 5.2.0.114, which should contain `mono32`.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/385