Bump to dotnet/installer/main@46b17bd1 6.0.100-preview.6.21280.2 (#5977)
Changes: https://github.com/dotnet/installer/compare/3ebe0ca9715283842b003a75cf2b3603ca28d964...46b17bd1587380d190dcdfd45a61a5b5c1eb6c93
Changes: https://github.com/mono/linker/compare/620b243420f5218be7002fdc04223c05854c60d6...50901f9ba5c8672c2758577a61f45fea3cc6cd76
Changes: https://github.com/dotnet/runtime/compare/5a26d12c41b866731a195938bf3c162ba4a04ce2...6e5f722a9dab49f9626ea95326ef6e74129621ca

Updates:

  * Microsoft.Dotnet.Sdk.Internal:
    [from 6.0.100-preview.6.21276.2 to 6.0.100-preview.6.21280.2][0]

  * Microsoft.NET.ILLink.Tasks:
    [from 6.0.100-preview.6.21275.1 to 6.0.100-preview.6.21277.2][1]

  * Microsoft.NETCore.App.Ref:
    [from 6.0.0-preview.6.21274.1 to 6.0.0-preview.6.21276.13][2]

Update the `BuildTest.AbiNameInIntermediateOutputPath()` test:

  * Context: 6034f6f35552f67dd872f00857b7a4edacda66e8

  * .NET 6 is no longer bringing in .NET 6 linux `.so` files that
    used to trigger the warning:

        warning XA4301: Cannot determine ABI of native library 'C:\src\xamarin-android\packages\sqlitepclraw.lib.e_sqlite3.linux\1.1.11\runtimes\linux-arm64\native\libe_sqlite3.so'.

    We can simply remove an assert that was looking for this.

    I suspect this is related to improvements in NuGet, such as:

      * https://github.com/NuGet/NuGet.Client/commit/10274281c37e9dd3626938757f7e947d649b821b

Update the `InstallAndRunTests.CustomLinkDescriptionPreserve()` test:

  * Context: https://www.nuget.org/packages/SQLitePCLRaw.bundle_green/2.0.3

  * `CustomLinkDescriptionPreserve()` test builds an Android
    application that references a `netstandard2.0` library.
    The `netstandard2.0` library has a dependency on `sqlite-net-pcl`.

  * One improvement here is now `SQLitePCLRaw.lib.e_sqlite3.android`
    is brought in by NuGet correctly.

  * Aside: there is some *odd* NuGet behavior in that `netstandard2.0`,
    `netcoreapp3.0`, and `monoandroid8.0` dependencies are brought in:

        Task ResolvePackageAssets
        ...
        RuntimeCopyLocalItems
            ~\.nuget\packages\sqlite-net-pcl\1.7.335\lib\netstandard2.0\SQLite-net.dll
            ~\.nuget\packages\sqlitepclraw.bundle_green\2.0.3\lib\netcoreapp3.0\SQLitePCLRaw.batteries_v2.dll
            ~\.nuget\packages\sqlitepclraw.bundle_green\2.0.3\lib\netcoreapp3.0\SQLitePCLRaw.nativelibrary.dll
            ~\.nuget\packages\sqlitepclraw.core\2.0.3\lib\netstandard2.0\SQLitePCLRaw.core.dll
            ~\.nuget\packages\sqlitepclraw.lib.e_sqlite3.android\2.0.3\lib\monoandroid80\SQLitePCLRaw.lib.e_sqlite3.android.dll
            ~\.nuget\packages\sqlitepclraw.provider.e_sqlite3\2.0.3\lib\netstandard2.0\SQLitePCLRaw.provider.e_sqlite3.dll

  * Unfortunately we get a crash at runtime:

        System.TypeInitializationException: TypeInitialization_Type, SQLite.SQLiteConnection
        ---> System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.provider.dynamic_cdecl, Version=2.0.3.851, Culture=neutral, PublicKeyToken=b68184102cba0b3b' or one of its dependencies.
        at SQLitePCL.Batteries_V2.Init() in SQLitePCLRaw.batteries_v2.dll:token 0x6000004+0x0
        at SQLite.SQLiteConnection..cctor() in SQLite-net.dll:token 0x6000020+0x16

  * …because we're missing `SQLitePCLRaw.provider.dynamic_cdecl`?

  * I don't quite understand what's happening here, due to how
    complicated the dependency graph is here.  For now changing the
    workaround to include `SQLitePCLRaw.provider.dynamic_cdecl`
    instead of `SQLitePCLRaw.lib.e_sqlite3.android` is sufficient to
    fix this test.

Update the `<ProcessNativeLibraries/>` task to exclude Mono Components
from Release builds.

  * Context: https://github.com/dotnet/runtime/blob/main/docs/design/mono/components.md#detailed-design---packaging-and-runtime-packs
  * Context: https://github.com/dotnet/runtime/blob/483fc90e356cc2d4f45fc5ad5e86dbbd92ef22d9/docs/design/mono/components.md

  * New `.so` files were appearing in Release builds:

        349,816 lib/arm64-v8a/libmono-component-diagnostics_tracing.so *2
        167,608 lib/arm64-v8a/libmono-component-hot_reload.so *2

  * These files are new Mono "components".

  * For now, we should exclude these files for Release builds, as they
    are meant for Debug scenarios.
    `diagnostics_tracing` is for profiling & diagnostics,
    `hot_reload` is "Hot Reload".

  * TODO: implement a "proper" mechanism for choosing whether
    components should go inside an app or not.

Update the `Microsoft.Android.Sdk.ILLink` preserve lists so that
types which no longer exist are not mentioned.  This fixes IL2008
warning messages:

	Mono.Android.xml(14,4): warning IL2008: Could not resolve type 'Android.Runtime.JniNativeInterfaceInvoker'
	Mono.Android.xml(19,4): warning IL2008: Could not resolve type 'Android.Runtime.JavaTypeConverter`1'
	Mono.Android.xml(13,4): warning IL2008: Could not resolve type 'Android.Runtime.JniNativeInterfaceStruct'
	Mono.Android.xml(5,4): warning IL2008: Could not resolve type 'Android.Runtime.GeneratedDummyHost'

Update the `Microsoft.Android.Sdk.ILLink` substitution file so that
the correct syntax to optimize
`Java.Interop.TypeManager.TypeRegistrationFallback()` is used.

  * Context: 5b3d8cdd16bbfff8a205e9aac6fc9d6d1a5a925d

  * The Feature XML syntax is not obvious, but:

    * If you use `//method/@value`, the method return type must be
      one of a limited set of types, which does *not* include
      `System.Type`:
      https://github.com/mono/linker/blob/54f4827313384e43bfd15c7ec6a45b6fa76090c3/src/linker/Linker.Steps/ProcessLinkerXmlBase.cs#L486-L598

    * If you want to just replace the result of the method invocation
      with `null`, you don't want `//method/@value` anyway!

    * `//method/@signature` must include parameter types and return types.

  * Previously, we observed an IL2009 warning:

        warning IL2009: Could not find method 'System.Type TypeRegistrationFallback()' on type 'Java.Interop.TypeManager'

    This was because `//method/@signature` lacked parameter types.

  * Fix `//method/@signature`, and remove `//method/@value`, so that
    the linker does what we wanted it to do:

        <method signature="System.Type TypeRegistrationFallback(System.String)" body="stub" />

Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>

[0]: https://github.com/dotnet/installer/compare/3ebe0ca9715283842b003a75cf2b3603ca28d964...46b17bd1587380d190dcdfd45a61a5b5c1eb6c93
[1]: https://github.com/mono/linker/compare/620b243420f5218be7002fdc04223c05854c60d6...50901f9ba5c8672c2758577a61f45fea3cc6cd76
[2]: https://github.com/dotnet/runtime/compare/5a26d12c41b866731a195938bf3c162ba4a04ce2...6e5f722a9dab49f9626ea95326ef6e74129621ca