Update *.apkdesc files.
Commits 2d6afda1ce8494a42519154933d53dc3f37220a3 &
69fa552176283882201dec109b5c42234c8c9cee result in smaller
`.png` resources, which causes the `.apk` size to shrink, e.g.

	Summary:

	…
	 28,672 Package size difference -0.30% (of 9,549,982)
	stdErr: Error: apkdiff: PackageSize decrease 28,672 is 23,552 bytes more than the threshold 5,120. apk1 size: 9,549,982 bytes, apk2 size: 9,521,310 bytes.
	Error: apkdiff: Size regression occured, 1 check(s) failed.

Update the .apkdesc files so that the tests pass.