[generator] Disable [SupportedOSPlatform] until .NET 5/6. (#781)
Context: f7acf1e5e44e02e46bfc9bee223d0859be5e50dd
Context: 653d208f85a27be8bb9bd7a178e422ddcf29b55a
Context: https://github.com/xamarin/xamarin-android/pull/5497#pullrequestreview-568088000

We cannot currently build `net5.0` or `net6.0` assemblies in our
xamarin-android tree; we instead do some workaround that involves
compiling with `netcoreapp3.1` while referencing the 5.0 BCL.

This creates a conflict between the local `[SupportedOSPlatform]` we
create in `Mono.Android.dll` built for `netcoreapp3.1` , and the real
one in the 5.0 BCL.

	error CS0433: The type 'SupportedOSPlatformAttribute' exists in both
	'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' and
	'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
	[/Users/runner/work/1/s/tests/Mono.Android-Tests/Java.Interop-Tests/Java.Interop-Tests.NET.csproj]

Disable generating `SupportedOSPlatformAttribute` until we can build
`Mono.Android.dll` with `NET` defined, in which case it will not
contain the local attribute, and we can re-enable f7acf1e5.