[generator] Support varargs arrays in event listener methods (#832)
Fixes: https://github.com/xamarin/java.interop/issues/817

Assume you have a Java event listener interface which accepts a Java
[varargs array][0], e.g.:

	// Java
	public interface SomeListener {
	    void onSomeNotification(long a, Object... b);
	}

	public class Whatever {
	    public void setSomeListener(SomeListener listener) {…}
	}

then `SomeListener` and `Whatever` are bound as expected:

	// C# binding
	public partial interface ISomeListener {
	    void OnSomeNotification(long a, params Object[] b);
	}
	public partial class Whatever {
	    public void SetSomeListener(ISomeListener listener) {…}
	}

*and also*, we ["eventify"][1] the listener interface members, wherein
the listener interface members become events on the using type, with
their `on` prefix removed:

	public partial class Whatever {
	    public event EventHandler<SomeNotificationEventArgs> SomeNotification {…}
	}

All parameters on the listener method become constructor parameters
on the  `EventArgs` subclass:

	public partial class SomeNotificationEventArgs : EventArgs {
	    public SomeNotificationEventArgs(long a, params Object[] b);
	}

Those parameters also become readonly properties:

	partial class SomeNotificationEventArgs {
	    public long A {get;}
	}

The bug is that when Java varargs arrays are used, the C# `params` 
keyword remains on the declared `EventArgs` subclass property:

	partial class SomeNotificationEventArgs {
	    public params Object[] B {get;}
	}

Which results in a CS1519 error:

	error CS1519: Invalid token 'params' in class, struct, or interface member declaration

Fix the CS1519 by removing the extraneous `params` output:

	partial class SomeNotificationEventArgs {
	    public Object[] B {get;}
	}

[0]: https://docs.oracle.com/javase/1.5.0/docs/guide/language/varargs.html
[1]: https://docs.microsoft.com/en-us/xamarin/android/internals/api-design#events-and-listeners