Parse Mono.Android.dll FIRST for typemaps
The remaining unit test failures are because `java/lang/Object`
is bound as
`Java.InteropTests.JavaLangRemappingTestObject, Java.Interop-Tests`,
NOT `Java.Lang.Object, Mono.Android`.

`Android.RuntimeTests.XmlReaderPullParserTest.ToLocalJniHandle()`:

	System.NotSupportedException : Unable to activate instance of type Java.InteropTests.JavaLangRemappingTestObject from native handle 0x19 (key_handle 0x2408476).
	----> System.MissingMethodException : No constructor found for Java.InteropTests.JavaLangRemappingTestObject::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
	----> Java.Interop.JavaLocationException : Exception_WasThrown, Java.Interop.JavaLocationException
	   at Java.Interop.TypeManager.CreateInstance(IntPtr , JniHandleOwnership , Type )
	   at Java.Interop.TypeManager.CreateInstance(IntPtr , JniHandleOwnership )
	   at Android.Runtime.XmlResourceParserReader.FromNative(IntPtr , JniHandleOwnership )
	   at Android.Runtime.XmlResourceParserReader.FromJniHandle(IntPtr handle, JniHandleOwnership transfer)
	   at Android.Content.Res.Resources.GetXml(Int32 )
	   at Android.RuntimeTests.XmlReaderPullParserTest.ToLocalJniHandle()
	   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
	   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object , BindingFlags )
	--MissingMethodException
	   at Java.Interop.TypeManager.CreateProxy(Type , IntPtr , JniHandleOwnership )
	   at Java.Interop.TypeManager.CreateInstance(IntPtr , JniHandleOwnership , Type )
	--JavaLocationException
	Java.Lang.Error: Exception_WasThrown, Java.Lang.Error

	  --- End of managed Java.Lang.Error stack trace ---
	java.lang.Error: Java callstack:
		at crc643df67da7b13bb6b1.TestInstrumentation_1.n_onStart(Native Method)
		at crc643df67da7b13bb6b1.TestInstrumentation_1.onStart(TestInstrumentation_1.java:35)
		at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

	  --- End of managed Java.Lang.Error stack trace ---
	java.lang.Error: Java callstack:
		at crc643df67da7b13bb6b1.TestInstrumentation_1.n_onStart(Native Method)
		at crc643df67da7b13bb6b1.TestInstrumentation_1.onStart(TestInstrumentation_1.java:35)
		at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

`Java.InteropTests.JniRuntimeJniValueManagerTests.CreateValue()`:

	System.NotSupportedException : Unable to activate instance of type Java.InteropTests.JavaLangRemappingTestObject from native handle 0x3432 (key_handle 0x9d3f1d1).
	----> System.MissingMethodException : No constructor found for Java.InteropTests.JavaLangRemappingTestObject::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
	----> Java.Interop.JavaLocationException : Exception_WasThrown, Java.Interop.JavaLocationException
	   at Java.Interop.TypeManager.CreateInstance(IntPtr , JniHandleOwnership , Type )
	   at Android.Runtime.AndroidValueManager.CreatePeer(JniObjectReference& , JniObjectReferenceOptions , Type )
	   at Java.Interop.JavaPeerableValueMarshaler.CreateGenericValue(JniObjectReference& , JniObjectReferenceOptions , Type )
	   at Java.Interop.JniValueMarshaler`1[[Java.Interop.IJavaPeerable, Java.Interop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].CreateValue(JniObjectReference& , JniObjectReferenceOptions , Type )
	   at Java.Interop.JniRuntime.JniValueManager.CreateValue(JniObjectReference& , JniObjectReferenceOptions , Type )
	   at Java.InteropTests.JniRuntimeJniValueManagerTests.CreateValue()
	   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
	   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object , BindingFlags )
	--MissingMethodException
	   at Java.Interop.TypeManager.CreateProxy(Type , IntPtr , JniHandleOwnership )
	   at Java.Interop.TypeManager.CreateInstance(IntPtr , JniHandleOwnership , Type )
	--JavaLocationException
	Java.Lang.Error: Exception_WasThrown, Java.Lang.Error

	  --- End of managed Java.Lang.Error stack trace ---
	java.lang.Error: Java callstack:
		at crc643df67da7b13bb6b1.TestInstrumentation_1.n_onStart(Native Method)
		at crc643df67da7b13bb6b1.TestInstrumentation_1.onStart(TestInstrumentation_1.java:35)
		at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

	  --- End of managed Java.Lang.Error stack trace ---
	java.lang.Error: Java callstack:
		at crc643df67da7b13bb6b1.TestInstrumentation_1.n_onStart(Native Method)
		at crc643df67da7b13bb6b1.TestInstrumentation_1.onStart(TestInstrumentation_1.java:35)
		at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

etc., etc.

(*Actually*, part of the problem is that `AndroidRuntime` doesn't
support Java.Interop-style activation constructors *at all*…
…and I don't want to deal with that right now, either.)

It was borderline bananas to expect anything to work when
`java/lang/Object` *wasn't* bound as `Java.Lang.Object, Mono.Android`.
I'm frankly suprised there are *only* 23 failures, most of them
duplicates of the same 8 failures, two of which are above.

Update `<GenerateJavaStubs/>` and related typemap code to special-case
`Mono.Android.dll` so that it is processed *first*.  This *should*
ensure that `Java.Lang.Object` is *preferred* over any other possible
binding of `java/lang/Object`.