[Mono.Android] Bind API-37.2 Beta 3
Context: https://developer.android.com/about/versions/17/qpr2
Context: ec3d578949eee8fe5c5e346dd78186d3001af76f
Context: 932224bf6dbf2d54ab6c5d9c4544f6e15f99bfea

Android 17 QPR2 has been released.

  * [API-37.2 Beta 3 vs. API-37][0]

Additionally, Google appears to be changing things up.  For API-36*,
there were two releases: 36 and 36.1, with API-36.1 being introduced
in QPR2 (Quarterly Platform Release 2), and there were no other point
releases for API-36*.

This year, API-37.1 was introduced in *QPR1*, and API-37.2 is being
introduced in QPR2.  Which means the `TODO` assumptions from ec3d5789
within `GetAndroidDefineConstants.cs` are no longer valid, so bump
that to *4*, just in case.

As with API-37.1, @jonpryor cannot find a release announcement, so
there isn't a lot to link to.

Step 1: bind it!
Step 2: Enumify it, make stable.

This is Step 1.  We consider this binding *unstable* until we complete
enumification (Step 2).

Additionally, the "auto `Color`" logic in 932224bf introduces an error:

	…/Android.Resource.cs(841,11): error CS0283: The type 'Color' cannot be declared const

Update the `//field` metadata changes from 932224bf so that `final`
fields aren't turned into `Color` instances.  These fields will remain
as `int` fields.

[0]: https://developer.android.com/sdk/api_diff/c-2-beta3/changes