[tests] Fix recently added AndroidMessageHandler test (#7859)
Context: 5d4668505038901f93ae4663f0c74ce110a0a50b
Context: https://github.com/xamarin/xamarin-android/pull/7785/commits/7b2e1728295d476f23d832e48640082c9f424aa0

Commit 5d466850 -- via [7b2e17][0] -- added usage of the NUnit3
[`RetryAttribute`][1] to some of our on-device unit tests.
Unfortunately, `RetryAttribute` doesn't exist in NUnitLite, resulting
in build failures such as:

	…/tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidMessageHandlerTests.cs(42,4):
	error CS0246: The type or namespace name 'RetryAttribute' could not be found (are you missing a using directive or an assembly reference?)

Oops.

This failure wasn't caught because we've trained ourselves to
partially ignore various failures in the **Tests** tab  -- networking
is hard, mkay? -- but completely missed the *compilation* failures,
which don't appear in the **Tests** tab and are harder to see.

Double oops.

Update `AndroidMessageHandlerTests.cs` to remove usage of `[Retry]`
and instead retry things "manually"

[0]: https://github.com/xamarin/xamarin-android/pull/7785/commits/7b2e1728295d476f23d832e48640082c9f424aa0
[1]: https://docs.nunit.org/articles/nunit/writing-tests/attributes/retry.html