Update BuildReleaseArm64XFormsDotNet.apkdesc
apkdiff: File 'assemblies/System.IO.Compression.dll' has changed by -878 bytes (-5.49 %). This exceeds the threshold of 5.00 %.
Error: apkdiff: Size regression occured, 1 check(s) failed.