Revert "[tests] Report errors last in `RunApkTests` (#1596)" (#1601)
Reverts commit 4a85391f80154c7181b1eb4aeccbbb6e00296084

Commit 4a85391f [broke the build][0]:

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/967/

	xamarin-android/build-tools/scripts/TestApks.targets(223,5): error : Root element is missing
	...
	ERROR: Step ‘Publish xUnit test result report’ aborted due to exception: 
	org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	        at org.jenkinsci.lib.dtkit.util.converter.ConversionService.convert(ConversionService.java:316)
	Caused: org.jenkinsci.lib.dtkit.util.converter.ConversionException: Error to convert - A file not found
	        at org.jenkinsci.lib.dtkit.util.converter.ConversionService.convert(ConversionService.java:358)
	...
	Finished: FAILURE

Revert until we can better test things.