[main] Update dependencies from dotnet/installer (#5830)
[main] Update dependencies from dotnet/installer


 - Update dotnet apkdesc, CheckIncludedAssemblies test

 - Merge remote-tracking branch 'origin/main' into darc-main-65998f2a-6cbb-40ce-874f-d9e4964f7051

 - Actually fix CheckIncludedAssemblies

 - [xaprepare] Fix IndexOutOfRangeException

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4651587&view=logs&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&t=17818c58-7ce3-5786-ae89-adf017dab0ca

The **determine which test stages to run** step is failing (?!):

	Determining test jobs to run...

	Step Xamarin.Android.Prepare.Step_DetermineAzurePipelinesTestJobs failed: Index was outside the bounds of the array.
	System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_DetermineAzurePipelinesTestJobs failed: Index was outside the bounds of the array. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
	  at Xamarin.Android.Prepare.Step_DetermineAzurePipelinesTestJobs.Execute (Xamarin.Android.Prepare.Context context) [0x000db] in <57f6c34b3bb14f7fa916671a4c4f9705>:0
	  at Xamarin.Android.Prepare.Step.Run (Xamarin.Android.Prepare.Context context) [0x00079] in <57f6c34b3bb14f7fa916671a4c4f9705>:0
	  at Xamarin.Android.Prepare.Scenario.Run (Xamarin.Android.Prepare.Context context, Xamarin.Android.Prepare.Log log) [0x000e7] in <57f6c34b3bb14f7fa916671a4c4f9705>:0
	   --- End of inner exception stack trace ---
	  at Xamarin.Android.Prepare.Scenario.Run (Xamarin.Android.Prepare.Context context, Xamarin.Android.Prepare.Log log) [0x0014b] in <57f6c34b3bb14f7fa916671a4c4f9705>:0
	  at Xamarin.Android.Prepare.Context.Execute () [0x000ee] in <57f6c34b3bb14f7fa916671a4c4f9705>:0
	  at Xamarin.Android.Prepare.App.Run (System.String[] args) [0x00848] in <57f6c34b3bb14f7fa916671a4c4f9705>:0

I *think* this is from `commitMessagePieces[3]`; add some
`commitMessagePieces.Length` checks to avoid the exception.

 - [tests] fixed CheckTimestamps

The path to the linker directory was expecting:

    obj\Debug\net6.0-android\linked

When we are now using:

    obj\Debug\net6.0-android\[RID]\linked

I updated the test to just check for a parent directory named `linked`.

This was passing in past .NET 6 builds, but looking a the MSBuild
targets in dotnet/sdk, it does not seem like they even care about the
timestamps on linker output:

https://github.com/dotnet/sdk/blob/a245b6ff06b483927e57d953b803a390ad31db95/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L113-L116

`Outputs="$(_LinkSemaphore)"` will likely be the only file that gets
"touch"-ed.

 - Bump to dotnet/installer@96ec2df 6.0.100-preview.4.21214.14

Changes: http://github.com/dotnet/installer/compare/c6e6c1b...96ec2df

 - Merge remote-tracking branch 'origin/main' into darc-main-65998f2a-6cbb-40ce-874f-d9e4964f7051

 - Use new runtime pack names, user projects default to UseMonoRuntime=true

 - Fix xa_build_configuration.cmake

 - Bump apkdesc files

 - Merge remote-tracking branch 'origin/main' into darc-main-65998f2a-6cbb-40ce-874f-d9e4964f7051