[Xamarin.Android.Build.Tasks] Handle duplicate Resources for Resource.Designer.cs
You can have versioned resources in android. As a
result you can have duplicate resource entries.
In the case of styleable items we were trying to
use a dictionary to keep track of the items which
we need to generate id's for. However because we
where comming across duplicate resource entires
we were crashing with a

	System.ArgumentException: An item with the same key has already been added.

This was because we had already created that `CodeMemberField`
and added it to the dictionary. What we need to do is skip over
items which have already been added.

Another problem with this was the order in which we
generated the styleable items. Adding the new `MultiSelectListPreference`
item caused the `ManagedResourceParser` to produce
different results. It turns out that android does some
sorting on the values and fields it produces for
the `Styleable` items.

Given the following xml declaration

	  <declare-styleable name="MultiSelectListPreference">
		<attr name="entries"/>
		<attr name="android:entries"/>
		<attr name="entryValues"/>
		<attr name="android:entryValues"/>
	</declare-styleable>

the following is produced in the `R.txt` file.

	int[] styleable MultiSelectListPreference { 0x010100b2, 0x010101f8, 0x7f030001, 0x7f030002 }
	int styleable MultiSelectListPreference_android_entries 0
	int styleable MultiSelectListPreference_android_entryValues 1
	int styleable MultiSelectListPreference_entries 2
	int styleable MultiSelectListPreference_entryValues 3

Note that the items are ordered alphabetically and NOT by the
order in which they appear in the xml. This needs to be done
BEFORE we actaully generate or lookup the actual id values
for these items. This is so they have the correct `index` into
the `MultiSelectListPreference` array. This commit also
fixes up this issue.

Unit test has been modified to take into account these new
senarios.