[CodeGen-Binding] Use Gradle 4.4 (#1107)
The VSTS build environment was updated to install Java 9.0.1.
[This promptly broke everything][vsts-build] when building
`tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding`:

[vsts-build]: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1224076

	Executing: ./gradlew assembleDebug --stacktrace
	...
	* What went wrong:
	Could not determine java version from '9.0.1'.
	* Try:
	Run with --info or --debug option to get more log output.
	* Exception is:
	java.lang.IllegalArgumentException: Could not determine java version from '9.0.1'.
	        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
	        at org.gradle.api.JavaVersion.current(JavaVersion.java:80)

The fix is to upgrade to Gradle 4.3 or later, which supports Java 9.

To upgrade the Gradle used, run:

	./gradlew wrapper --gradle-version=4.4 --distribution-type=bin --stacktrace