[Xamarin.Android.Build.Tasks] <CopyIfChanged/> should check size (#3405)
Fixes: https://github.com/xamarin/xamarin-android/issues/2584

Building a project with two different `$(TargetFrameworkVersion)`:

	msbuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.4
	msbuild /t:Configuration=Release /p:TargetFrameworkVersion=v9.0

Results in a build error:

	error MSB4018: The "LinkAssemblies" task failed unexpectedly.
	Mono.Linker.MarkException: Error processing method: 'System.Void BatchStepSensor.BatchStepSensorFragment::OnSaveInstanceState(Android.OS.Bundle)' in assembly: 'BatchStepSensor.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.OS.BaseBundle::PutInt(System.String,System.Int32)
	    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
	    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
	    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
	    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
	    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
	    at Mono.Linker.Steps.MarkStep.ProcessQueue()
	    --- End of inner exception stack trace ---
	    at Mono.Linker.Steps.MarkStep.ProcessQueue()
	    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
	    at Mono.Linker.Steps.MarkStep.Process()
	    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
	    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
	    at Mono.Linker.Pipeline.Process(LinkContext context)
	    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
	    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
	    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
	    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
	    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Which is due to an outdated `Mono.Android.dll` in the `obj` directory:

	Target Name=_CopyIntermediateAssemblies
	    CopyIfChanged
	    ...
	    Skipping C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\Mono.Android.dll its up to date
	    ...
	    ModifiedFiles:
	        obj\Release\linksrc\BatchStepSensor.dll

Reviewing the `<CopyIfChanged/>` MSBuild task, there is a code path
where the copy is skipped if the source file is newer than the
destination.

In the case of modifying `$(TargetFrameworkVersion)` on an
incremental build, a *different* `Mono.Android.dll` would have an
older timestamp.  The copy would be skipped.

A fix here is to *also* check the size of the source and destination
files, and only allow the copy to be skipped if the sizes match.

~~ _ConvertResourcesCases ~~

These changes surfaced a bug in the `_ConvertResourcesCases` target`;
if `build.props` changes then:

  * The `_CompileResources` target runs
  * The `_ConvertResourcesCases` target is skipped (!)

And you get a build error such as:

	Resources\layout\test.axml(3): error APT0000: resource drawable/IMALLCAPS (aka UnnamedProject.UnnamedProject:drawable/IMALLCAPS) not found.

The solution here is to make the `Inputs` of `_CompileResources` and
`_ConvertResourcesCases` the same.  I also adjusted a test to check
both `aapt` and `aapt2`.