[linux] Delete Windows-only stuff from install dir (#2856)
The linux build has [been broken][0] ever since commit 4ccbeb74:

	dh_clideps -X/usr/lib/xamarin.android/xbuild-frameworks/ \
	...
	Unhandled Exception:
	IKVM.Reflection.BadImageFormatException: Exception of type 'IKVM.Reflection.BadImageFormatException' was thrown.
	  at IKVM.Reflection.Reader.PEReader.RvaToFileOffset (System.UInt32 rva) [0x00070] in <f3855a9b922743e79049757cdcdbb705>:0 
	...
	dh_clideps: cli_parser call failed: 'LANG=C MONO_PATH= MONO_GAC_PREFIX=  /usr/bin/ikdasm --moduleref libwinpthread-1.dll 2>&1 > /tmp/dh_clideps.s9Ph' rc: 256 output: 

This looks ~identical to the error mentioned in e16639ac, yet the
`--exclude-moduleref=libwinpthread-1.dll` isn't helping.

Try an alternate solution: remove `aapt2.exe` and
`libwinpthread-1.dll`.  This should keep `dh_clideps` from
encountering the native PE files, and in turn allow Debian packaging
to complete without error.

Additionally, exclude the `java-interop` module, should it exist.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux-release/1051