[AndroidSdkWindows] Guard against exception checking registry (#79)
Fixes: https://developercommunity.visualstudio.com/content/problem/883179/ilegal-characters-in-path-after-fresh-install.html

Somehow, a registry key contains invalid path characters.
This causes an `ArgumentException` from
`AndroidSdkWindows.CheckRegistryKeyForExecutable()`:

	System.ArgumentException: Illegal characters in path.
	   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
	   at System.IO.Path.Combine(String path1, String path2)
	   at Xamarin.Android.Tools.AndroidSdkWindows.CheckRegistryKeyForExecutable(UIntPtr key, String subkey, String valueName, Wow64 wow64, String subdir, String exe)
	   at Xamarin.Android.Tools.AndroidSdkWindows.<GetAllAvailableAndroidSdks>d__37.MoveNext()
	   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
	   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	   at Xamarin.Android.Tools.AndroidSdkBase.get_AllAndroidSdks()
	   at Xamarin.Android.Tools.AndroidSdkBase.Initialize(String androidSdkPath, String androidNdkPath, String javaSdkPath)
	   at Xamarin.Android.Tools.AndroidSdkWindows.Initialize(String androidSdkPath, String androidNdkPath, String javaSdkPath)
	   at Xamarin.Android.Tools.AndroidSdkInfo..ctor(Action`2 logger, String androidSdkPath, String androidNdkPath, String javaSdkPath)

Handle the `ArgumentException` by wrapping the body of
`CheckRegistryKeyForExecutable()` within a `try/catch` block and
catch all exceptions.  If an exception is thrown, there is no
executable of interest.