Revert "Support build-tools 33.0.0."
This reverts commit f86fedcc0c92fc93ec352c54ea934b01e8234c75.

Build-tools 33.0.0 causes unit test failures, e.g.

    Error: Cannot fit requested classes in a single dex file (# methods: 68000 > 65536)

This appears to be because build-tools 33.0.0 no longer contains
`mainDexClasses.rules`, so linking doesn't *do* as much.

Revert to build-tools 32.0.0.