[Mono.Android] Remove `AdditionalProperties` from Java.Interop tools project references. (#8573)
Context: https://github.com/xamarin/xamarin-android/commit/e2854ee71961d4a9910944e5b2aa7107cdf2349c

Often when compiling XA locally on Windows I get this error:
```
CSC : error CS2012: Cannot open 'c:\code\xamarin-android\external\Java.Interop\tools\generator\obj\Debug-net7.0\generat
or.dll' for writing -- 'The process cannot access the file 'c:\code\xamarin-android\external\Java.Interop\tools\generat
or\obj\Debug-net7.0\generator.dll' because it is being used by another process.' [c:\code\xamarin-android\external\Java
.Interop\tools\generator\generator.csproj]
```

This is caused by our usage of `AdditionalProperties` in our `<ProjectReference>`.  This was needed as a result of trying to reference a `net472;net7.0` `generator` project in a `MonoAndroid1.0;net7.0` `Mono.Android` project.  `AdditionalProperties` cause an additional build of the referenced project, setting global properties.  Both this additional build and the original build are now `net7.0` causing them to clobber each other.

Since we're now in a fully .NET world, we are no longer multi-targeting `generator` or `Mono.Android` so we can remove this hack and avoid the extra builds and potential sharing violation errors.