[xaprepare] *Actually* install API-CANARY
The result of `jar tf $(_AndroidJar)`?

	"/Users/builder/android-toolchain/jdk-21/bin/jar" tf "/Users/builder/android-toolchain/sdk/platforms/android-CANARY/android.jar"
	java.nio.file.NoSuchFileException: /Users/builder/android-toolchain/sdk/platforms/android-CANARY/android.jar

`android-CANARY/android.jar` didn't exist!

Remove my install, re-run `make prepare`, and:

	[00:00:56.6831457] Checking if platform-36.0-CANARY_r03 exists in /Users/jon/android-toolchain/sdk/platforms/android-CANARY
	[00:00:56.6831525] Component 'platform-36.0-CANARY_r03' directory does not exist: /Users/jon/android-toolchain/sdk/platforms/android-CANARY
	[00:00:56.6839114]     skipping, not requested
	[00:00:56.6839186]   • Checking [00:00:56.6839232] source-36_r01

🧐 API-CANARY isn't installed!

(Which explains why it can't be found!)

Update `AndroidToolchain.cs` so that `isPreview: true` is provied for
API-CANARY.

This *should* cause xaprepare to provision the API level, allowing
things to build.

If this fails, follow @jpobst's suggestion and instead specify
`isLatestStable: true` for API-CANARY.

[0]: https://discord.com/channels/732297728826277939/732297837953679412/1413601582829801584