[Xamarin.Android.Build.Tasks] fix for missing content provider (#2387)
Using a commercial master build of Xamarin.Android, I get the
following crash at runtime:

    java.lang.RuntimeException: Unable to get provider mono.android.ResourcePatcher: java.lang.ClassNotFoundException: Didn't find class "mono.android.ResourcePatcher" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/HelloForms.HelloForms-g8b7mdSG3CF6lxWgPVIURg==/base.apk"],nativeLibraryDirectories=[/data/app/HelloForms.HelloForms-g8b7mdSG3CF6lxWgPVIURg==/lib/arm64, /data/app/HelloForms.HelloForms-g8b7mdSG3CF6lxWgPVIURg==/base.apk!/lib/arm64-v8a, /system/lib64]]
           at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
           at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
           at android.app.ActivityThread.access$1100(ActivityThread.java:199)
           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
           at android.os.Handler.dispatchMessage(Handler.java:106)
           at android.os.Looper.loop(Looper.java:193)
           at android.app.ActivityThread.main(ActivityThread.java:6669)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Looking at `obj\Debug\android\AndroidManifest.xml`, I had this line:

    <provider android:name="mono.android.ResourcePatcher" android:exported="false" android:initOrder="1999999998" android:authorities="HelloForms.HelloForms.mono.android.ResourcePatcher.__mono_init__" />

This `ResourcePatcher` content provider should only be present when
the new "Enhanced" Fast Deployment is enabled.

Reviewing the code, it seemed that the `ManifestDocument` class was
adding this to the manifest in a case where it shouldn't.

Changes:

- Added checks of the `$(_InstantRunEnabled)` MSBuild property, before
  deciding if the content provider is present in the manifest file.
- Added a test to verify this scenario. I had to make use of the
  `$(_XASupportsFastDev)` property in the test.
- Removed extra input logging of `GenerateJavaStubs`.