Merge apkdiff from upstream
Besides the other changes we want the regression testing.

Example output:

    apkdiff.exe --test-apk-size-regression=51200 --test-assembly-size-regression=51200 Xamarin.Forms_Performance_Integration-Signed-Release.apkdesc bin\TestDebug\Xamarin.Forms_Performance_Integration-Signed.apk
    Size difference in bytes ([*1] apk1 only, [*2] apk2 only):
      +  26,749,952 assemblies/Mono.Android.dll
    Error: apkdiff: Assembly size differs more than 51,200 bytes.
      +  14,655,424 assemblies/Mono.Android.pdb *2
      +   2,423,388 lib/x86/libmonosgen-2.0.so
      +   2,413,568 assemblies/mscorlib.dll
    Error: apkdiff: Assembly size differs more than 51,200 bytes.
      +   2,025,076 classes.dex
      +   1,755,580 lib/armeabi-v7a/libmonosgen-2.0.so
      +   1,683,644 assemblies/mscorlib.pdb *2
      +   1,511,544 assemblies/Xamarin.Android.Support.v7.AppCompat.dll
    Error: apkdiff: Assembly size differs more than 51,200 bytes.
    ...
    Summary:
      +  43,001,792 Assemblies 303.25% (of 14,180,480)
      +  10,653,224 Shared libraries 89.86% (of 11,855,444)
      +  66,973,060 Package size difference 318.80% (of 21,007,581)
    Error: apkdiff: PackageSize differ more than 51,200 bytes. apk1 size: 21,007,581 bytes, apk2 size: 87,980,641 bytes.
    Error: apkdiff: Size regression occured, 39 test(s) failed.

Changes:

    dc6cfc Update the handling of an unknown option
    3b825e Handle unknown option
    897547 Support aab packages
    812215 Add new regression options
    fbac82 Use thousand separator in regression prints
    e5aef1 Count regression failures and report the count
    11ba62 Added assembly size regression testing
    e7ee8e Added apk size regression testing implementation
    b95995 Set platform target
    a74d02 Fix white space
    3afd5a Print also percentage in package size difference
    fd8d3e Show assemblies and shared libraries total differences in summary
    130598 Add section sizes example
    b1ee9a Update LibZipSharp to newer version
    d84b35 Compare shared libraries section sizes
    3a3ceb Added another example output
    4e094f Add initial assembly comparison
    7efe90 Compare shared libraries symbols and their sizes
    fcac80 Improve csproj file
    3a479d Update solution/project files to load in VS/Mac without issues