[mono-runtimes] Bundle Consts.cs, use correct opt.exe install location
Context: https://github.com/xamarin/xamarin-android/pull/162

PR #162 tries to use the mono bundle (fbfd676c) to avoid rebuilding
mono on subsequent builds (when the mono commit hasn't changed), in
order to speed up the Jenkins build process (currently tracking at
~3.5 *hours* for a non-PR build...)

[PR #162 currently fails][0] when building `src/Mono.Data.Sqlite`:

	CSC: error CS2001: Source file `/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/external/mono/mcs/build/common/Consts.cs' could not be found

Fix this error by copying `external/mono/mcs/build/common/Consts.cs`
into `bin/$(Configuration)/include`, and updating the `Consts.cs`
references within `Mono.Data.Sqlite.csproj` and `Mono.Posix.csproj` so
that they'll use the `include` copy.

This should allow us to use the bundle to build these projects.

Additionally, `llc.exe` and `opt.exe` are installed into
`$prefix/bin`, which isn't correct; `$prefix/bin` as a construct
doesn't exist on Windows. Install these into `$prefix/lib/mandroid`.

Update the bundle version to note these bundle changes.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pr-builder/67/console