Revert "[build] Fix the Linux build" (#403)
Reverts xamarin/xamarin-android#394 (commit 61b21bce).

[It broke the build][b209]:

	Java.Lang/Object.cs(15,5): error CS0012: The type `System.IDisposable' is defined in an assembly that is not referenced.
    Consider adding a reference to assembly `System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Doubly odd, I *thought* that this had successfully gone through the
PR builder, but I can't find an actual PR build for this PR!

Revert the attempted Linux build fix. We want things building, which
will allow me time to investigate a better Linux fix.

[b209]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/209/