[tests] apk size regression testing (#4545)
Use `apkdiff` (2e28f2ea) and `.apkdesc` description files to check
for `.apk` size regressions.  This allows for more informative and
useful messages when `.apk` size regressions occur, e.g.

	Saving apk description to '../../../bin/TestRelease/Xamarin.Forms_Performance_Integration-Signed.apkdesc'
	 Size difference in bytes ([*1] apk1 only, [*2] apk2 only):

	100,000 assemblies/Mono.Android.dll
	Error: apkdiff: Assembly 'assemblies/Mono.Android.dll' size increase 100,000 is 48,800 bytes more than the threshold 51,200.

	    492 lib/armeabi-v7a/libmonodroid.so
	    216 lib/x86/libmonodroid.so
	Summary:

	100,000 Assemblies 0.71% (of 14,080,480)
	    708 Shared libraries 0.01% (of 11,855,444)
	      0 Package size difference 0.00% (of 21,007,581)
	Error: apkdiff: Size regression occured, 1 check(s) failed.

The new `<ApkDiffCheckRegression/>` task handles running the `apkdiff`
tool and creates `TestResult*.xml` files for convenient CI reporting
of `.apk` size regressions.

Add `tests/apk-sizes-reference/*.apkdesc` files to contain "expected
sizes" for verification.