[build] Build the monodroid-profile BCL assemblies reliably (#135)
Commit 37b5fd51 broke `make jenkins` (and possible `make all`?)
through the introduction of the `%(_MonoRuntime.DoBuild)` metadata:
`%(_MonoRuntime.DoBuild)` wasn't added everywhere required.
In particular, the `host-Darwin` item didn't gain `<DoBuild/>`,
meaning *`host-Darwin` wasn't built*. This in turn meant that the
monodroid BCL wasn't built (!) which caused a build break much later
within `src/Mono.Android`:

	Executing: mono .../xamarin-android/external/Java.Interop/bin/Debug/jcw-gen.exe
		-o ".../xamarin-android/src/Mono.Android/obj/Debug/android-23/jcw/src"
		-L ".../xamarin-androidg/lib/xbuild-frameworks/MonoAndroid/v6.0/"
		-L ".../xamarin-android/src/Mono.Android/../../bin/Debug/lib/xbuild-frameworks/MonoAndroid/v6.0/../v1.0/"
		-L ".../xamarin-android/src/Mono.Android/../../MonoAndroid/v6.0/../v1.0/Facades"
		".../xamarin-android/src/Mono.Android/../../bin/Debug/lib/xbuild-frameworks/MonoAndroid/v6.0/Mono.Android.dll"
	jcw-gen: Could not load assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Perhaps it doesn't exist in the Mono for Android profile?

`mscorlib.dll` couldn't be found because it wasn't *built*, nor
installed into `bin/Debug/lib/xbuild-frameworks/MonoAndroid/v1.0`.

Additionally, fully building the AOT cross compilers requires adding
`mxe-Win32` to `$(ALL_HOST_ABIS)`, otherwise e.g. `win-armeabi` fails
to build because `arm_dpimacros.h` doesn't exist (as `arm_dpimacros.h`
is built by `mxe-Win32`):

	Error parsing '.../xamarin-android/external/mono/mono/metadata/metadata-cross-helpers.c'
	.../xamarin-android/external/mono/mono/arch/arm/arm-codegen.h(937,10): fatal: 'mono/arch/arm/arm_dpimacros.h' file not found
	Error parsing '.../xamarin-android/external/mono/mono/mini/mini-cross-helpers.c'
	.../xamarin-android/external/mono/mono/arch/arm/arm-codegen.h(937,10): fatal: 'mono/arch/arm/arm_dpimacros.h' file not found
	Unhandled Exception:
	System.Exception: Expected to find struct definition for MonoObject

Fix the `mono-runtimes.mdproj` build so that it doesn't re-execute
targets when not necessary, by "rolling" with xbuild limitations and
refactoring item groups as appropriate. In particular, xbuild doesn't
like referencing item metadata within a `//Target/@Outputs` that in
turn references a property group:

	<PropertyGroup>
		<V>Value</v>
	</PropertyGroup>
	<ItemGroup>
		<Item Include="Something">
			<Metadata>$(V)</Metadata>
		</Item>
	</ItemGroup>
	<Target Name="Example" Inputs="..."
			Outputs="%(Item.Metadata)">
		...
	</Target>

Whenever the `Example` target is run, it will *always* run, even if
`Value` exists, because `xbuild` perceives the
`//Target[@Name='Example']/@Outputs` value as being
`$(V)`, *not* `Value`, which is wonderfully broken.

To compensate, Don't Do That™; in particular, item metadata used
within `//Target/@Outputs` *must* be hardcoded and not contain a
property reference. This "hardcoding" removes the need for the
`$(_Cross*ffsetsHeaderFile)` properties, so remove them.

Remove `System.Net.Http.WebRequest.dll` from `@(_BclAssembly)`, as it
is no longer built in the monodroid profile; requiring it as an output
means that the "host" mono build is *always* built, which isn't needed.

Improve the `_BuildRuntimes` and `_InstallRuntimes` targets so that
their referenced files aren't *so* repetitive, in particular by
"splitting out" `@(_RuntimeLibraries)` into `@(_RuntimeSource)`,
`@(_ProfilerSource)`, and `@(_MonoPosixHelperSource)`. This allows
more intelligently `strip`ing the native libraries in the Release
configuration, while also maintaining generation of the `.d.so` files.