[generator] Fix NRE from return type not consistently set (#834)
Fixes: https://github.com/xamarin/xamarin-android/issues/5921

Context: https://github.com/xamarin/java.interop/pull/834#issuecomment-838954034
Context: https://github.com/xamarin/java.interop/blob/61bf407ef23c693521c951c00c784c35a24001be/tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs#L1175-L1181

Consider the following Java type declaration:

	package com.example;

	public interface FlowIterator<R> {
	  R next();

	  public static class RangeIterator<T extends Comparable<T>> implements FlowIterator<T> {
	    public T next() {return null;}
	  }
	}

This used to work in d16-7 -- not sure when exactly we broke it --
but it now throws a `NullReferenceException` when using
`generator --codegen-target=XAJavaInterop1`, when emitting the nested
`FlowIteratorRangerIterator` type:

	$ mono bin/Debug/generator.exe -o yyy ji-834-fixed.xml --codegen-target=XAJavaInterop1
	…
	Unhandled Exception:
	System.NullReferenceException: Object reference not set to an instance of an object
	  at Xamarin.SourceWriter.MethodWriter.WriteReturnType (Xamarin.SourceWriter.CodeWriter writer)
	  at Xamarin.SourceWriter.MethodWriter.WriteSignature (Xamarin.SourceWriter.CodeWriter writer)
	  at Xamarin.SourceWriter.MethodWriter.Write (Xamarin.SourceWriter.CodeWriter writer)

Fix the `NullReferenceException` by ensuring that the `ReturnType`
property and `Parameters` collection are set before the
`BoundMethodAbstractDeclaration` constructor completes.