[Xamarin.Android.Build.Tasks] Shared Runtime app crash on startup (#3084)
Fixes: https://github.com/xamarin/xamarin-android/issues/3081

When running an app under commercial Xamarin.Android with the shared
runtime enabled -- `$(AndroidUseSharedRuntime)`=True -- we crash
during process startup:

	System.ArgumentException: Handle must be valid.
	Parameter name: instance
	  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method)
	  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod)
	  at Java.Interop.TypeManager.GetClassName (System.IntPtr class_ptr)
	  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType)
	  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type)
	  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer)
	  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer)
	  at Java.Lang.Thread.get_DefaultUncaughtExceptionHandler ()
	  at Android.Runtime.JNIEnv.Initialize (Android.Runtime.JnienvInitializeArgs* args)

The [*immediately* apparent "cause"][0] of the crash is that
[`JNIEnv::GetObjectClass()` was returning NULL][1]:

	IntPtr class_ptr = JNIEnv.GetObjectClass (handle);
	// `class_ptr` is IntPtr.Zero (?!)
	string class_name = GetClassName (class_ptr);
	// throws ArgumentException

Further investigation showed that the "cause" was in the contents of
the `typemap.jm.inc` file; see also decfbccf.  Here are the file
sizes for `typemap.jm.inc`, with and without the shared runtime:

	$ ls -la typemap.mj.inc                        # with shared runtime
	-rw-r--r--  1 d  staff  462  9 May 09:42 typemap.mj.inc
	$ ls -la obj/Debug/android/typemap.mj.inc      # without shared runtime
	-rw-r--r--  1 d  staff  8982060  9 May 09:43 obj/Debug/android/typemap.mj.inc

As you can see, the shared runtime file is missing a huge amount of
data.  In the past when we generated the old typemap files we only
needed to generate the mapping for the types in the user assemblies.
This was because when using the shared runtime,
`Mono.Android.DebugRuntime-*.apk` contained typemap files for
`Mono.Android.dll`.  However as of decfbccf these are now expected to
be compiled into the `libxamarin-app.so` native library, and
[`libmono-android*.so` doesn't support loading typemap files][2]
from `.apk` files.  This means that even when using the shared
runtime we should be generating *all* the mappings in that library.

We do not currently *understand* ***why*** the lack of typemap
entries causes the above `ArgumentException`.  We just know it does.

Fix shared runtime execution by updating `<GenerateJavaStubs/>` so
that *all* types are always provided to `TypeNameMapGenerator`, even
when the shared runtime is used.

[0]: https://xamarinhq.slack.com/archives/C03CEGRUW/p1557320053256800
[1]: https://github.com/xamarin/xamarin-android/blob/0eedf95de281449e6f1682231ac5bae4abd1d459/src/Mono.Android/Java.Interop/TypeManager.cs#L242-L243
[2]: https://github.com/xamarin/xamarin-android/commit/decfbccf3e99449c9a8d6afef113c9339f1bc85b#diff-fcb50a6533eb26323059bc5c8bda1dd7L384