Bump to .NET 8
Changes: https://github.com/dotnet/installer/compare/11f6b8f7129e34d5317f47ccbc110b2b11c05749...d552037815b75e01be05b6e8d269d54413363e7f
Changes: https://github.com/dotnet/linker/compare/5f9bfd94d9c687207872ae03f751ea19704381c0...493ce626f3278b2d0fd883330bf11a64254981bb
Changes: https://github.com/dotnet/runtime/compare/6d10e4c8bcd9f96ccd73748ff827561afa09af57...b8d49801fe03b96d2fead3d97a11dce1e723dd17

A summary of what it took to get this working:

* Run `darc update-dependencies --id 152596`

* Setup .NET 6,7,8 "multi-targeting"

* Setup dotnet6/dotnet7/dotnet8 NuGet feeds

* `$(DotNetTargetFrameworkVersion)` should be 8.0

* Rename API diff for `net8.0`

* Fix `AutoImport.props` for 8.0

* Update `.apkdesc` files

* Update `CheckIncludedAssemblies` test

* Use .NET Core `3.1.x`

Trying to avoid:

    dotnet-install: Failed to locate the latest version in the channel '3.1.417' with 'preview' quality for 'dotnet-sdk', os: 'win', architecture: 'x64'.

* Install .NET 6 for legacy MSBuild tests

* [Mono.Android.Export] fix `NotSupportedException`

Context: https://github.com/mono/mono/blob/242ac50598e4f596e1a42f9dd377701096ea3a74/mcs/class/referencesource/mscorlib/system/reflection/emit/dynamicmethod.cs#L276-L277
Context: https://github.com/dotnet/runtime/commit/e46523032d72c8b0d2b14ce4b14229a8c268a6e5

    System.NotSupportedException: Wrong MethodAttributes or CallingConventions for DynamicMethod. Only public, static, standard supported

* Use correct Mono pack names for `$(AotAssemblies)`

* Fix `DotNetPublish` test

Was failing with:

    Build should be using C:\a_work\1\s\xamarin-android\bin\Release\dotnet\packs\Microsoft.Android.Ref.33\34.0.0-ci.pr.gh7451.52\ref\net7.0\Mono.Android.dll
Expected: True
But was:  False

* Remove a `net7.0` assertion for build warnings

See: https://github.com/dotnet/runtime/issues/77385

* Pass `-SkipNonVersionedFiles` to `dotnet-install` scripts to avoid:

   dotnet --info
   Exited with code: 137