[build] Fix the Release Configuration build (#54)
The Release configuration build would fail, because:

1. `mono.linq.expressions` wouldn't build on non-Windows platforms.

2. `Java.Interop.dll` in Release set
    `FEATURE_JNIENVIRONMENT_SAFEHANDLES`, which didn't compile.

3. `tools\generator.csproj` wasn't *in* the Release configuration,
    which caused a compilation error when building
    `generator-Tests.csproj` because `generator.exe` wasn't
    referenced.

4. `src\java-interop` didn't build because of:

		java-interop-gc-bridge-mono.c:871:79: error: use of undeclared identifier 'klass'
		        jmethodID   add_method_id   = get_add_reference_method (bridge, env, handle, klass);

Fix (1) by bumping to a Mono.Linq.Expressions commit which does build
on non-Windows platforms in the Release configuration.

Fix (2) by using `FEATURE_JNIENVIRONMENT_JI_PINVOKES` instead.

Fix (3) by adding `tools\generator.csproj` to the Release
configuration.

Fix (4) by removing `#if DEBUG` use so that `klass` is in scope.