[Mono.Android] Add unsigned NewArray overloads. (#4119)
Fixes: https://github.com/xamarin/java.interop/issues/556

Context: https://github.com/xamarin/java.interop/commit/99cf71951c02252a9f150ad8f2250e76cf36a050

Changes: https://github.com/xamarin/java.interop/compare/621e297fe181bcd1967d47368faa846a82196dd3...99cf71951c02252a9f150ad8f2250e76cf36a050

  * xamarin/Java.Interop@99cf719: [generator] Call explicit unsigned NewArray() methods (#558)
  * xamarin/Java.Interop@2c77a8d: [param-name-importer] Integrate xamarin-android-docimporter-ng (#560)

`generator` now requires the use of `JNIEnv.NewArray(X[])` where `X`
is an unsigned type -- `uint`, `ushort`, etc. -- in order to support
arrays of Kotlin unsigned types.

This allows users to get an XA2006 package time error if they are
using an older Xamarin.Android that does not support unsigned types,
instead of a runtime error.  We feel that a packaging-time error will
be more reliable and less user-hostile than "random" runtime errors
on downlevel product versions.

Additionally, update `Xamarin.Android.Build.Tasks.csproj` and
`Xamarin.Android.Tools.Aidl.csproj` to use Irony 1.1.0 (up from 0.9.1)
in order to fix a [Windows unit test execution issue][0]:

	System.IO.FileNotFoundException: Could not load file or assembly 'Irony, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ca48ace7223ead47'

[0]: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3418084&view=ms.vss-test-web.build-test-results-tab&runId=10836400&resultId=100022&paneView=debug