[Xamarin.Android.Build.Tasks] Remove Java.Interop*.dll reference. (#6400)
Commit 3e6a6232d904acfc95017eeae58408787b0f8dc9
Context: https://discord.com/channels/732297728826277939/732297837953679412/898675755779768330
Context: https://github.com/xamarin/Java.Interop/commit/3e6a6232d904acfc95017eeae58408787b0f8dc9

An unfortunate unexpected breakage occurred due to commit
xamarin/Java.Interop@3e6a6232: the version of `Java.Interop.dll`
changed -- which we *should* have expected but completely overlooked
& forgot -- which in turn meant that *everything* which depends upon
it -- which is everything -- started breaking due to the version
change, e.g.

	error CS1705: Assembly 'Microsoft.Maui' with identity 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
	uses 'Java.Interop, Version=0.1.6.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
	which has a higher version than referenced assembly
	'Java.Interop' with identity 'Java.Interop, Version=0.1.2.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

The primary motivation with xamarin/Java.Interop@3e6a6232 was to
improve the use of *MSBuild* task assemblies, however
`Java.Interop.dll` is *not* really a *MSBuild* assembly.  It is a
dependency pulled in for `Java.Interop.Export.dll` which was itself
pulled in for a single small static method
`MarshalMemberBuilder.GetMarshalMethodName(…)`.

As such, let's remove the assembly references to both
`Java.Interop.dll` and `Java.Interop.Export.dll` from
`Xamarin.Android.Build.Tasks.dll`, by copying over the needed method.

This means we do not need to continuously update the version number of
`Java.Interop.dll` and `Java.Interop.Export.dll`, which will allow
assemblies created with newer versions of Xamarin.Android to continue
working on earlier releases where Java.Interop has a version number
of `0.1.0.0`.

Additionally, remove `Java.Interop.dll` and `Java.Interop.Export.dll`
from the `lib\xamarin.android\xbuild\Xamarin\Android` directory in
the installer.  `Java.Interop.dll` should only be consumed via the
framework profiles.  `Java.Interop.Export.dll` was experimental and
is not in active use.