[Xamarin.Android.Tools.AnnotationSupport] Support one-element arrays (#272)
[Xamarin.Android.Tools.AnnotationSupport] Support one-element arrays (#272)

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=59046

`AnnotationValue.ValueAsArray` was assumed to be non-`null` for e.g.
`android.support.annotation.IntDef` annotations, and the
`//annotation/val[@name='value']/@val` attribute was assumed to
contain a brace-enclosed, comma-separated list of values:


	<annotation name="android.support.annotation.IntDef">
	  <val name="flag" val="true" />
	  <val name="value" val="{com.example.Whatever.Flags.FLAG_FOO, com.example.Whatever.Flags.FLAG_FOO}" />
	</annotation>

However, we encountered a scenario where a single value was present
and there were no braces enclosing the value, e.g.:

	<annotation name="android.support.annotation.IntDef">
	  <val name="flag" val="true" />
	  <val name="value" val="com.example.Whatever.Flags.FLAG_FOO" />
	</annotation>

The unfortunate result was that `AnnotationValue.ValueAsArray` wasn't
set, resulting in a `NullReferenceException`:

	System.ArgumentNullException: Value cannot be null.
	Parameter name: source
	  at System.Linq.Enumerable.Select[TSource,TResult] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] selector)
	  at Xamarin.AndroidTools.AnnotationSupport.DefinitionManagedTypeFinderExtension.ProcessAnnotationValue (Xamarin.AndroidTools.AnnotationSupport.AnnotatedItem item, Xamarin.AndroidTools.AnnotationSupport.AnnotationData a, Xamarin.AndroidTools.AnnotationSupport.AnnotationValue v)
	  at Xamarin.AndroidTools.AnnotationSupport.DefinitionManagedTypeFinderExtension.ProcessAnnotation (Xamarin.AndroidTools.AnnotationSupport.AnnotatedItem item)
	  at Xamarin.AndroidTools.AnnotationSupport.ManagedTypeFinder.LoadManagedMappings (System.Collections.Generic.IEnumerable`1[T] anns, Xamarin.AndroidTools.AnnotationSupport.ManagedTypeFinder+IType[] types)
	  at Xamarin.AndroidTools.AnnotationSupport.ManagedTypeFinderGeneratorTypeSystem.OnAnnotationsParsed (System.Collections.Generic.IEnumerable`1[T] itemsToBeBound)
	  at Xamarin.AndroidTools.AnnotationSupport.AndroidAnnotationsSupport.Load (System.String annotationsZipFile)
	  at Xamarin.Android.Binder.CodeGenerator.GenerateAnnotationAttributes (System.Collections.Generic.List`1[T] gens, System.Collections.Generic.IEnumerable`1[T] zips)
	  at Xamarin.Android.Binder.CodeGenerator.Run (Xamarin.Android.Binder.CodeGeneratorOptions options, Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver)
	  at Xamarin.Android.Binder.CodeGenerator.Run (Xamarin.Android.Binder.CodeGeneratorOptions options)
	  at Xamarin.Android.Binder.CodeGenerator.Main (System.String[] args)

Update `AnnotationValue` so that `AnnotationValue.ValueAsArray` is
*always* set, and either contains the `{...}` values *or* contains
an single element array with the
`//annotation/val[@name='value']/@val` attribute value.