[Xamarin.Android.NUnitLite] Ensure test results path exists (#435)
For example, Release builds don't create the internal `.__override__`
directory by default for security purposes, but if no external
storage is available, the internal `.__override__` path is used.

Result:

	System.IO.DirectoryNotFoundException: Could not find a part of the path "/data/data/Xamarin.Android.RuntimeTests/files/.__override__/TestResults.xml".

which means you can't obtain the unit test execution. Doh!

Ensure that `resultsPath` actually exists to avoid the
`DirectoryNotFoundException` error.