[ci] Use Python 3 for signing tasks (#8367)
Authenticode signing attempts started failing recently with:

    ERROR: 'xsign' is misspelled or not recognized by the system.

Updating to Python 3 is the suggested fix for this issue.