Bump to dotnet/sdk/main@c204043de1 9.0.100-rc.2.24468.2 (#9311)
Changes: https://github.com/dotnet/sdk/compare/dc8695276b...c204043de1
Changes: https://github.com/dotnet/runtime/compare/dec716d1c4...46cfb747b4
Changes: https://github.com/dotnet/emsdk/compare/c8026c0932...6e079c23ae

Updates:

* Microsoft.NET.Sdk: from 9.0.100-rc.2.24459.3 to 9.0.100-rc.2.24468.2
* Microsoft.NETCore.App.Ref: from 9.0.0-rc.2.24456.9 to 9.0.0-rc.2.24463.7
* Microsoft.NET.Workload.Emscripten.Current.Manifest-9.0.100.Transport: from 9.0.0-rc.2.24454.2 to 9.0.0-rc.2.24455.1
* Microsoft.NET.ILLink.Tasks: from 9.0.0-rc.2.24456.9 to 9.0.0-rc.2.24463.7

~~ Other changes ~~

* Add `[RequiresDynamicCode]` for System.Linq.Expressions

Fixes the build error(s):

    src/Mono.Android/Android.Runtime/IJavaObjectValueMarshaler.cs(40,11): error IL3050:
    Using member 'System.Linq.Expressions.Expression.Call(Type, String, Type[], params Expression[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Calling a generic method requires dynamic code generation. This can be suppressed if the method is not generic.
    src/Mono.Android/Android.Runtime/IJavaObjectValueMarshaler.cs(54,7): error IL3050:
    Using member 'System.Linq.Expressions.Expression.Call(Type, String, Type[], params Expression[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Calling a generic method requires dynamic code generation. This can be suppressed if the method is not generic.

* Feeds for dotnet/runtime 8.0.10

* Bump to dotnet/java-interop/main@d8599654

Changes: https://github.com/dotnet/java-interop/compare/51b784a2...d8599654

  * Bump external/xamarin-android-tools from 6575743 to 11fad9d
  * [Java.Interop] Add [RequiresDynamicCode] attribute
  * Bump to dotnet/android-tools@ab2165d

Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>