[generator] Prevent generating duplicate EventArgs classes (#726)
Fixes: https://github.com/xamarin/java.interop/issues/461

Given this Java listener interface:

	// Java
	interface AnimatorListener {
	    void onAnimationEnd (int param1);
	    void onAnimationEnd (int param1, int param2);
	}

Previously we would generate *two*
`partial class AnimationEndEventArgs` declarations:

	// C# binding event args for java.code.AnimatorListener.onAnimationEnd
	public partial class AnimationEndEventArgs : global::System.EventArgs {
	    public AnimationEndEventArgs (int param1)
	    {
	        this.param1 = param1;
	    }

	    int param1;
	    public int Param1 {
	        get { return param1; }
	    }
	}

	// C# binding event args for java.code.AnimatorListener.onAnimationEnd
	public partial class AnimationEndEventArgs : global::System.EventArgs {
	    public AnimationEndEventArgs (int param1, int param2)
	    {
	        this.param1 = param1;
	        this.param2 = param2;
	    }

	    int param1;
	    public int Param1 {
	        get { return param1; }
	    }

	    int param2;
	    public int Param2 {
	        get { return param2; }
	    }
	}

This causes a compilation error:

	error CS0102: The type 'AnimationEndEventArgs' already contains a definition for 'param1'

We need to detect these situations and instead combine multiple
`EventArgs` classes into one, with a constructor for each method:

	// event args for java.code.AnimatorListener.OnAnimationEnd
	public partial class AnimationEndEventArgs : global::System.EventArgs {
	    public AnimationEndEventArgs (int param1)
	    {
	        this.Param1 = param1;
	    }

	    public AnimationEndEventArgs (int param1, int param2)
	    {
	        this.Param1 = param1;
	        this.Param2 = param2;
	    }

	    public int Param1 { get; private set; }
	    public int Param2 { get; private set; }
	}

Additionally, clean up the generated code a little bit by using auto
properties instead of fields.