[Xamarin.Android.Build.Tasks] Preserve Link action for assemblies (#133)
Fixes: http://bugzilla.xamarin.com/show_bug.cgi?id=42788

Preserve Link action for assemblies, so that they are rewritten
with the resolved references.

The issue in this bug looks like this:

* `[mscorlib]System.MonoTODOAttribute` is referenced from
    `System.Core.dll`.

* Because `ResolveFromAssemblyStep.ProcessLibrary()` sets the action
    to Copy, the `System.Core.dll` is only copied from original place
		and not saved with resolved references.

* The `System.MonoTODOAttribute` resolves to reference inside the
    `Microsoft.CSharp.dll` assembly (where it is kept, it is stripped
    from `mscorlib.dll`) and thus the reflection fails at runtime,
		when attempting to load the `System.Core.dll` assembly

The result is a `TypeLoadException`:

    System.TypeLoadException: Failed for unknown reasons.
      at (wrapper managed-to-native) System.MonoCustomAttrs:GetCustomAttributesDataInternal (System.Reflection.ICustomAttributeProvider)
      at System.MonoCustomAttrs.GetCustomAttributesData (ICustomAttributeProvider obj) [0x00011] in <filename unknown>:0 
      at System.Reflection.CustomAttributeData.GetCustomAttributes (System.Reflection.MemberInfo target) [0x00000] in <filename unknown>:0 
      at Mono.CSharp.MetadataImporter.ImportTypes (System.Type[] types, Mono.CSharp.Namespace targetNamespace, Boolean importExtensionTypes) [0x000c3] in <filename unknown>:0 
      at Mono.CSharp.ReflectionImporter.ImportAssembly (System.Reflection.Assembly assembly, Mono.CSharp.RootNamespace targetNamespace) [0x00021] in <filename unknown>:0 
      at Microsoft.CSharp.RuntimeBinder.DynamicContext.Create () [0x000d1] in <filename unknown>:0 
      at Microsoft.CSharp.RuntimeBinder.CSharpInvokeMemberBinder.FallbackInvokeMember (System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject[] args, System.Dynamic.DynamicMetaObject errorSuggestion) [0x00006] in <filename unknown>:0 
      at System.Dynamic.InvokeMemberBinder.FallbackInvokeMember (System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject[] args) [0x00000] in <filename unknown>:0 
      at System.Dynamic.DynamicMetaObject.BindInvokeMember (System.Dynamic.InvokeMemberBinder binder, System.Dynamic.DynamicMetaObject[] args) [0x0000b] in <filename unknown>:0 
      at System.Dynamic.InvokeMemberBinder.Bind (System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject[] args) [0x00016] in <filename unknown>:0 
      at System.Dynamic.DynamicMetaObjectBinder.Bind (System.Object[] args, System.Collections.ObjectModel.ReadOnlyCollection`1 parameters, System.Linq.Expressions.LabelTarget returnLabel) [0x000de] in <filename unknown>:0 
      at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T] (System.Runtime.CompilerServices.CallSite`1 site, System.Object[] args) [0x0001c] in <filename unknown>:0 
      at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, System.Dynamic.T0 arg0, System.Dynamic.T1 arg1, System.Dynamic.T2 arg2) [0x00120] in <filename unknown>:0 
      at DynamicTest.MainActivity+<OnCreate>c__AnonStorey0.<>m__0 (System.Object sender, System.Net.DownloadStringCompletedEventArgs e) [0x0029f] in /Users/petercollins/git/monodroid-samples/DynamicTest/DynamicTest/MainActivity.cs:69 
      at System.Net.WebClient.OnDownloadStringCompleted (System.Net.DownloadStringCompletedEventArgs e) [0x0000b] in <filename unknown>:0 
      at System.Net.WebClient.DownloadStringOperationCompleted (System.Object arg) [0x00000] in <filename unknown>:0 
      at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
      at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <filename unknown>:0 
      at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00009] in <filename unknown>:0 
      at (wrapper dynamic-method) System.Object:8fac3e9d-0d86-4913-8b38-60c3330d5f9d (intptr,intptr)