[Microsoft.Android.Sdk.ILLink] Depend on Xamarin.Android.Build.Tasks (#4827)
Context: https://dev.azure.com/xamarin/public/_build/results?buildId=20658&view=logs&j=eaa940d3-522b-5c6f-5355-ccf9c59bc592&t=7c64c695-9fff-5310-84da-a67a6770a0aa

The Linux build (063d645c & related) has failed to build since commit
51b77c60, because of a dependency issue:

	CSC : error CS2001: Source file '…/src/Microsoft.Android.Sdk.ILLink/../Xamarin.Android.Build.Tasks/obj/Release/Profile.g.cs' could not be found.

The cause of this error is because
`Microsoft.Android.Sdk.ILLink.csproj` doesn't depend upon
`Xamarin.Android.Build.Tasks.csproj`, and
`Xamarin.Android.Build.Tasks.csproj` is responsible for creating
`Profile.g.cs`.

Update `@(ProjectReference)` within `Microsoft.Android.Sdk.ILLink`
so that `Profile.g.cs` will exist, fixing the CS2001 error.

Note: this will *not* fix the the Linux build.  The Linux build was
also separately broken by 8f9c6382:

	…/build-tools/api-xml-adjuster/api-xml-adjuster.targets(44,5): error : class-parse: Unable to read file '…/android-toolchain/sdk/platforms/android-R/android.jar':
	Could not find a part of the path "…/android-toolchain/sdk/platforms/android-R/android.jar".

This error occurs because commit 8f9c6382 was *incomplete*: it started
installing `…/platforms/android-30/android.jar`, but other parts of the
build system still require the existence of
`…/platforms/android-R/android.jar`, which is no longer installed.

The other build environments -- including CI! -- were able to build
because they still had a `…/platforms/android-R/android.jar` file from
previous `make prepare` invocations; `~/android-toolchain` is not
cleaned up between builds, and thus contained "stale" artifacts.

The Linux build environment, on the other hand, is always "clean".
On the down side, this means that Linux builds always take longer,
as the build environment must always be recreated, but on the plus
side it does catch inconsistencies like this.

The 8f9c6382 breakage will be fixed as part of [PR #4821][0]

[0]: https://github.com/xamarin/xamarin-android/pull/4821