[ApiXmlAdjuster] Add additional expected attributes (#476)
Context: https://github.com/xamarin/xamarin-android/pull/3223
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-debug/619/

Commit 7f8f039b breaks the xamarin-android build, as it introduces new
XML attributes to `class-parse` output which
`Xamarin.Android.Tools.ApiXmlAdjuster` doesn't appreciate:

	Unhandled Exception:
	System.Exception: …/xamarin-android/bin/BuildDebug/api/api-10.xml.class-parse (16,7): Element 'class' has an unexpected attribute: 'source-file-name'. Expected attributes are: source-file-name
	  at Xamarin.Android.Tools.ApiXmlAdjuster.XmlUtil.CheckExtraneousAttributes (System.String elementName, System.Xml.XmlReader reader, System.String[] expected)
	  at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiLoaderExtensions.LoadTypeAttributes (Xamarin.Android.Tools.ApiXmlAdjuster.JavaType type, System.Xml.XmlReader reader, System.String[] otherAllowedAttributes)
	  at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiLoaderExtensions.Load (Xamarin.Android.Tools.ApiXmlAdjuster.JavaClass kls, System.Xml.XmlReader reader)

Update `Xamarin.Android.Tools.ApiXmlAdjuster` so that the new
attributes introduced in 7f8f039b are considered acceptable.

Additionally, fix the error message so that it *actually* lists the
"expected attributes", instead of repeating the *un*-expected attribute.