Bump to mono/debugger-libs/master@b024d07 (#2988)
Context: http://build.devdiv.io/2590575
Changes: https://github.com/mono/debugger-libs/compare/b45303f...b024d07

Some Windows machines fail to build `Xamarin.Android.sln` with:

    external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs(2606,30):
        Error CS0234: The type or namespace name 'Unix' does not exist in the namespace 'Mono' (are you missing an assembly reference?)

There is a `<Reference Include="Mono.Posix"/>` that doesn't work on my
Windows machine, and *some* CI machines?

But if I look at: http://build.devdiv.io/2590624

This build worked using:

    /reference:"C:\Program Files (x86)\GtkSharp\2.12\lib\Mono.Posix\Mono.Posix.dll"

So I guess things work if you have GTK installed?

Since we probably don't want to require GTK to be installed, I fixed
the issue upstream in mono/debugger-libs by relying on a NuGet package
on Windows.