[Mono.Android] Fix API-34 exercise enums with name conflicts (#8254)
Context: dab495ff1e139e2761bd690cb001f3df78a8e0db

While creating enumerations for API-34 constants, three enums were
created that had the same type name as a bound Java type.  These
enums have been renamed to no longer conflict with generated types.

  - `BodyTemperatureMeasurementLocation` -> `BodyTemperatureMeasurementLocationType`
  - `ExerciseSegmentType` -> `ExerciseSegmentTypeEnum`
  - `ExerciseSessionType` -> `ExerciseSessionTypeEnum`

This was noticed because `CS2002` warnings appeared when building `Mono.Android`:

	CSC : error CS2002: Source file 'C:\code\xamarin-android\src\Mono.Android\obj\Debug\net8.0\android-34\mcw\Android.Health.Connect.DataTypes.ExerciseSessionType.cs' specified multiple times

To help ensure this is prevented in the future, turn
`CS2002` warnings into errors.