[ci] Upgrade to macOS 12 Monterey and Xcode 13.4
Context: https://github.com/xamarin/xamarin-android/commit/fb227bdfcc59d3d69017e1e53f403a97b9fefcf7

We recently ran into an issue in our official builds that only occurred
when using Xcode 13.2.  This issue didn't surface in our PR builds which
use Xcode 12.4:

    timing-internal.hh(433,4): error GD3D6EBB4: no matching function for call to 'calculate_interval'
        calculate_interval (event.start, event.end, interval, total_ns);

Our [PR build pool][0] was recently updated to include some Monterey
images.  We should be able to avoid issues like this in the future by
using the same macOS and Xcode versions for both PR builds and official
builds.

[0]: https://devdiv.visualstudio.com/DevDiv/_settings/agentqueues?queueId=2206&view=agents