[empty] trigger a new build
Signing failed on the previous commit:

    Prepare Signing Tools
    ...
    NuGet aquisition started
    ##[error]The remote server returned an error: (403) Forbidden.

Then retry failed again:

    error: 7> 30.16.45.34 Failed to sign file /Users/builder/azdo/_work/2/s/xamarin-android/bin/BuildRelease/Microsoft.NET.Workload.Android-30.0.100-preview.7.107.pkg
    ERROR: One or more files were not able to sign.
    ##[error]Bash exited with code '1'.
    ##[error]Bash wrote one or more lines to the standard error stream.
    ##[error]ERROR: One or more files were not able to sign.

We hit a point where retry is not possible anymore:

    ##[error]The nuget command failed with exit code(1) and error(Response status code does not indicate success: 409 (Conflict - The feed already contains 'Microsoft.Android.Ref 30.0.100-preview.7.107+sha.3d54f06'.

Let's try an empty commit and see how that fares.