[Xamarin.Android.Build.Tasks] Fix ManagedResourceParser to handle duplicate `attr` elements.
Context https://work.azdo.io/1184573

`aapt2` is captable of processing the following input without
error.

```
<declare-styleable name="CustomFonts">
  <attr name="android:scrollX" />
  <attr name="customFont" />
  <attr name="customFont" />
</declare-styleable>
```

Our `ManagedResourceParser` will generate the following exception

	 System.ArgumentException: An entry with the same key already exists.
		at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
		at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
		at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
		at Xamarin.Android.Tasks.ManagedResourceParser.Parse(String resourceDirectory, IEnumerable`1 additionalResourceDirectories, Boolean isApp, Dictionary`2 resourceMap)
		at Xamarin.Android.Tasks.GenerateResourceDesigner.RunTask()
		at Xamarin.Android.Tasks.AndroidTask.Execute()

This PR reworks the `ManagedResourceParser` to handle these
duplicate `attr` elements. It also introduces a new Task property
which will let us speficy the exact location of the `R.txt` file.
This means we no longer need to rely on relative pathing.