[tests] update to latest GPS packages (#6565)
We recently discovered the following doesn't work in .NET 6:

* `dotnet new android`
* Add `<PackageReference Include="Xamarin.Google.MLKit.BarcodeScanning" Version="116.1.2.2" />`

`dotnet build` fails with many `javac` errors:

    obj\Debug\net6.0-android\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(8,52): error JAVAC0000:  error: package com.google.android.gms.common.api.GoogleApiClient does not exist

`Xamarin.Build.Download` didn't actually download the Java libraries.

If you make this change to Xamarin.Build.Download locally, it solves
the issue:

https://github.com/xamarin/XamarinComponents/commit/faf04b389ea3e1b9a57d9f9bd5ba57f0ad2f87fa

We never shipped this fix!

This is resolved now with [Xamarin.Build.Download 0.11.0][0]. So
adding this to the original `.csproj` solves the problem:

    <PackageReference Include="Xamarin.Build.Download" Version="0.11.0" />

Let's update tests that would have caught this issue. I found I could
reproduce the issue with newer Google Play Services NuGet packages,
while the old ones we used in tests worked fine.

[0]: https://www.nuget.org/packages/Xamarin.Build.Download/0.11.0