[Mono.Android-TestsAppBundle] Fix the build
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3328422&view=logs&j=8556562a-ae5f-5bd1-7c4d-bf1af4b6f1e1&t=edd3bdba-6ec4-5961-ea81-8c75bc7c9371

The build failed:

	.../src/Mono.Android/Test/Xamarin.Android.RuntimeTests/TestInstrumentation.cs(24,39): error CS0234: The type or namespace name 'JavaInterop_Tests_Reference' does not exist in the namespace 'Java.InteropTests' (are you missing an assembly reference?)

Add an appropriate `@(ProjectReference)`.