[One .NET] produce 31, 32, 33 packs
Context: https://github.com/xamarin/xamarin-android/issues/7183

Adding a class like this to a `dotnet new android` project:

    class MyThread : Java.Lang.Thread { }

Causes the build to fail with:

    obj\Debug\net6.0-android\android\src\crc6474063b540de74d1e\RenderingThread.java(76,3): error JAVAC0000:  error: no suitable constructor found for Thread(ThreadGroup,Runnable,String,long,boolean)
      super (p0, p1, p2, p3, p4);
    constructor Thread.Thread() is not applicable
      (actual and formal argument lists differ in length)
    constructor Thread.Thread(Runnable) is not applicable
      (actual and formal argument lists differ in length)
    constructor Thread.Thread(ThreadGroup,Runnable) is not applicable
      (actual and formal argument lists differ in length)
    constructor Thread.Thread(String) is not applicable
      (actual and formal argument lists differ in length)
    constructor Thread.Thread(ThreadGroup,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor Thread.Thread(Runnable,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor Thread.Thread(ThreadGroup,Runnable,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor Thread.Thread(ThreadGroup,Runnable,String,long) is not applicable
      (actual and formal argument lists differ in length)

This is a new `Thread` constructor added in API 33:

https://developer.android.com/reference/java/lang/Thread#Thread(java.lang.ThreadGroup,%20java.lang.Runnable,%20java.lang.String,%20long,%20boolean)

What's happening here is a result of our workload authoring...

* `net6.0-android` defaults to `$(TargetPlatformVersion)` 31

* You get a `Microsoft.Android.Ref.31` reference assembly for
  `Mono.Android.dll`

* However, we mistakenly thought a `Microsoft.Android.Runtime.33`
  "runtime" assembly for `Mono.Android.dll` would work!

And so the `<GenerateJavaStubs/>` MSBuild target runs against an API
33 `Mono.Android.dll`, generating a `Thread` constructor that doesn't
compile.

To fix this:

* `Mono.Android.Apis.projitems` now contains metadata for each API
  level, such as:

    <AndroidApiInfo Include="v11.0">
      <Name>R</Name>
      <Level>30</Level>
      <Id>30</Id>
      <Stable>True</Stable>
      <DotNetSupported>False</DotNetSupported>
    </AndroidApiInfo>
    <AndroidApiInfo Include="v12.0">
      <Name>S</Name>
      <Level>31</Level>
      <Id>31</Id>
      <Stable>True</Stable>
      <DotNetSupported>True</DotNetSupported>
    </AndroidApiInfo>

* Build API 31, 32, 33 runtime packs based on
  `%(AndroidApiInfo.DotNetSupported)`. We will ship these going forward.

* The workload now installs 31 packs by default. The API 32 & 33 packs
  can be restored from NuGet, or via the `android-32` or `android-33`
  workloads.

I added a test for this scenario that validates the runtime pack used
during a build.

I will port these changes to xamarin-android/main in a future PR.