[installer] Include java-interop.jar in the installation (#3235)
Fixes: https://github.com/xamarin/xamarin-android/issues/3234

We had trouble creating the required java types, because
`java-interop.jar` was missing.

Thus we end up with:

	Error: jnimarshalmethod-gen: Unable to create Java VM
	System.TypeInitializationException: The type initializer for 'Types' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object
	  at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x000b2] in <3d0cf794364146b58e1c173deac04834>:0
	  at Java.Interop.JniType..ctor (System.String classname) [0x00006] in <3d0cf794364146b58e1c173deac04834>:0
	  at Java.Interop.JniEnvironment+Types..cctor () [0x000d2] in <3d0cf794364146b58e1c173deac04834>:0
	   --- End of inner exception stack trace ---
	  at Java.Interop.JniType..ctor (System.String classname) [0x00006] in <3d0cf794364146b58e1c173deac04834>:0
	  at Java.Interop.JniRuntime..ctor (Java.Interop.JniRuntime+CreationOptions options) [0x001b4] in <3d0cf794364146b58e1c173deac04834>:0
	  at Java.Interop.JreRuntime..ctor (Java.Interop.JreRuntimeOptions builder) [0x00007] in <0837e9ee267c4328a98bfd16059a729d>:0
	  at Java.Interop.JreRuntimeOptions.CreateJreVM () [0x00000] in <0837e9ee267c4328a98bfd16059a729d>:0
	  at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.CreateJavaVM (System.String jvmDllPath) [0x0000d] in <c1d2f255a4b541868afd675bdc42a188>:0