[xaprepare] log exceptions, and handle CRL check failures
Context: https://github.com/dotnet/arcade/pull/15546

Right now failures just print:

    Downloading dotnet-install script...
    -> https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh
    Error: Download of dotnet-install from 'https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh' failed

Let's log the exception message, as it retries.

After this change, we get the intermittent error on macOS only:

    Warning: Download of 'https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh' failed: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
    ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown

In dotnet/arcade#15546, they addressed this problem by using
`SocketsHttpHandler` and configuring the `CertificateChainPolicy` to
ignore the `RevocationStatusUnknown` error.

Let's use the same approach here.