[build] MonoAndroidFramework.props/targets for short-form MSBuild projects
In order to build the following projects:

* OpenTK.csproj
* System.EnterpriseServices.csproj
* Xamarin.Android.NUnitLite.csproj

These need to be `MonoAndroid` assemblies that import
`Xamarin.Android.CSharp.targets`. They are *not* built by `xabuild`.

At first you would think you could just do:

    <Project Sdk="Microsoft.NET.Sdk">
      <!-- Everything else here -->
      <Import Project="$(OutputPath)\..\..\..\xbuild\Xamarin\Android\Xamarin.Android.CSharp.targets" />
    </Project>

This yields a warning such as:

    Xamarin.Android.CSharp.targets(50,5): warning MSB4011: "Microsoft.CSharp.targets" cannot be imported again.
    It was already imported at "C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (37,3)".
    This is most likely a build authoring error. This subsequent import will be ignored.

We can change this to:

    <PropertyGroup>
      <LanguageTargets Condition="Exists('$(OutputPath)\..\..\..\xbuild\Xamarin\Android\Xamarin.Android.CSharp.targets')">$(OutputPath)\..\..\..\xbuild\Xamarin\Android\Xamarin.Android.CSharp.targets</LanguageTargets>
    </PropertyGroup>
    <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.targets" />

This makes `Xamarin.Android.CSharp.targets` get imported as if it were
the C# targets. No warnings!

This is the same trick used by MSBuild.Sdk.Extras:

https://github.com/novotnyllc/MSBuildSdkExtras/blob/7bf8b6484b9fc4df3c10ba96b6722423b0898026/Source/MSBuild.Sdk.Extras/Build/Platforms.targets#L16-L18

For extra usability, let's setup things so all three projects can
simply do:

    <Project>
      <Import Project="..\..\build-tools\MonoAndroidFramework.props" />
      <!-- Everything else here -->
      <Import Project="..\..\build-tools\MonoAndroidFramework.targets" />
    </Project>

In a future PR, we can consolidate remaining projects that need to
import `Xamarin.Android.CSharp.targets`.

~~ Fix for transitive @(ProjectReference) ~~

Originally these changes were failing with:

    mono --debug /Users/builder/azdo/_work/1/s/xamarin-android/bin/Release/lib/mandroid-internal/typenamemap-gen.exe -o typemap ...
    Failed to read '/Users/builder/azdo/_work/1/s/xamarin-android/bin/Release/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v11.0/libzip.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
    System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
        at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders (System.UInt16& subsystem, System.UInt16& dll_characteristics) [0x000c8] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil.PE/ImageReader.cs:200
        at Mono.Cecil.PE.ImageReader.ReadImage () [0x0008b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil.PE/ImageReader.cs:85
        at Mono.Cecil.PE.ImageReader.ReadImage (Mono.Disposable`1[T] stream, System.String file_name) [0x00007] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil.PE/ImageReader.cs:763
        at Mono.Cecil.ModuleDefinition.ReadModule (Mono.Disposable`1[T] stream, System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00006] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/ModuleDefinition.cs:1146
        at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0006c] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/ModuleDefinition.cs:1118
        at Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/AssemblyDefinition.cs:131
        at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly (System.String file) [0x000de] in /Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:163
    typenamemap-gen: Error processing assemblies: error XA0009: Error while loading assembly: '/Users/builder/azdo/_work/1/s/xamarin-android/bin/Release/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v11.0/libzip.dll'.

`libzip.dll` is a Windows native library, but why is it even in the
`xbuild-frameworks/MonoAndroid/v11.0` folder at all?

Another difference with the dotnet/sdk, it appears that in some cases
transitive project dependencies projects in `.sln` files will get
their build output included in a projects' `$(OutputPath)`.

I found a helpful blog post on this:

https://cezarypiatek.github.io/post/managing-output-in-sdk-projects/

I added a new `_DoNotCopyProjectReferences` target that sets
`%(Private)` to `false` for every item in `@(ProjectReferenceWithConfiguration)`.

We might eventually want to migrate this behavior repo-wide, as it
will improve our build performance and fix many of the "double writes"
that occur during our build.