[BootstrapTasks] use libZipSharp in <UnzipDirectoryChildren/>
Context: https://github.com/xamarin/xamarin-android/pull/2666

In #2666, it appears we are hitting a bug in .NET framework on Windows
server machines?

    System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
        at System.IO.Compression.Zip64EndOfCentralDirectoryLocator.TryReadBlock(BinaryReader reader, Zip64EndOfCentralDirectoryLocator& zip64EOCDLocator)
        at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
        at Xamarin.Android.Tools.BootstrapTasks.UnzipDirectoryChildren.<ExtractFile>d__22.MoveNext()
        --- End of inner exception stack trace ---
        at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
        at Xamarin.Android.Tools.BootstrapTasks.UnzipDirectoryChildren.Execute()
        at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
        at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
        ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
        at System.IO.Compression.Zip64EndOfCentralDirectoryLocator.TryReadBlock(BinaryReader reader, Zip64EndOfCentralDirectoryLocator& zip64EOCDLocator)
        at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
        at Xamarin.Android.Tools.BootstrapTasks.UnzipDirectoryChildren.<ExtractFile>d__22.MoveNext()<---
        [E:\A\_work\1439\s\src\Xamarin.Android.Build.Tasks\Xamarin.Android.Build.Tasks.csproj]

Which occurs when unzipping:

    C:\Users\dlab14\android-toolchain\sdk\extras\android\m2repository\com\android\support\multidex\1.0.1\multidex-1.0.1.aar

What is also weird about this, is it only seems to break when
`$(TargetFrameworVersion)` is set to `v4.7.2`? xamarin-android/master
is working fine.

`<UnzipDirectoryChildren/>` was looking at `$(HostOS)` and:

* Using `System.IO.Compression` on Windows
* Using `$TMP` and `unzip` + `mv` commands on other platforms

But `Xamarin.Android.Tools.BootstrapTasks` already had a reference to
`libZipSharp`? We should just use it.

I refactored this MSBuild task:

* Same code for all platforms
* No temp directory needed
* Removed `HostOS` property
* General cleanup

Hopefully this will get #2666 to work.

I had to make a couple changes to *use* libZipSharp in
`Xamarin.Android.Tools.BootstrapTasks.csproj`:

* Created a `libzip-references.projitems`, that we can import in
  projects using `libZipSharp`
* Switched `Xamarin.ProjectTools` to use this as well as
  `BootstrapTasks`