[proguard] Preserve ManagedPeer class (#1351)
Fixes: https://github.com/xamarin/xamarin-android/issues/1331

Apps built with ProGuard enabled crash on startup:

	$ msbuild /t:Install /p:Configuration=Release /p:EnableProguard=true *.csproj
	# launch the app, and `adb logcat` contains:
	Unhandled Exception:
	System.TypeInitializationException: The type initializer for 'Java.Interop.ManagedPeer' threw an exception. ---> System.ArgumentException: Handle must be valid.
	Parameter name: type
	  at Java.Interop.JniEnvironment+Types.IsInstanceOf (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type)
	  at Android.Runtime.JNIEnv.IsInstanceOf (System.IntPtr obj, System.IntPtr clazz)
	  at Java.Interop.Runtime.IsGCUserPeer (System.IntPtr value)
	  at Java.Interop.Runtime.IsGCUserPeer (Android.Runtime.IJavaObject value)
	  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType)
	  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type)
	  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer)
	  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer)
	  at Android.Runtime.AndroidRuntime.GetExceptionForThrowable (Java.Interop.JniObjectReference& value, Java.Interop.JniObjectReferenceOptions transfer)
	  at Java.Interop.JniEnvironment+Types.FindClass (System.String classname)
	  at Java.Interop.JniType..ctor (System.String classname)
	  at Java.Interop.JniType.GetCachedJniType (Java.Interop.JniType& cachedType, System.String classname)
	  at Java.Interop.JniPeerMembers.get_JniPeerType ()
	  at Java.Interop.ManagedPeer..cctor ()
	   --- End of inner exception stack trace ---
	  at Java.Interop.JniRuntime..ctor (Java.Interop.JniRuntime+CreationOptions options)
	  at Android.Runtime.AndroidRuntime..ctor (System.IntPtr jnienv, System.IntPtr vm, System.Boolean allocNewObjectSupported, System.IntPtr classLoader, System.IntPtr classLoader_loadClass)
	  at Android.Runtime.JNIEnv.Initialize (Android.Runtime.JnienvInitializeArgs* args)

After Xamarin.Android stopped using Java.Interop built against the
`XAIntegration*` configuration (7d32ef3e), we need to ensure that the
type `com.xamarin.java_interop.ManagedPeer` -- found within 
`mono.android.jar` -- is preserved within the final `classes.dex`, as
`Java.Interop.ManagedPeer` requires it.

Thus we need to preserve that class when using ProGuard.