[Xamarin.Android.Build.Tasks] %(Aliases) & Resource.designer.cs (#3972)
Fixes: https://github.com/xamarin/xamarin-android/issues/3808

Context: https://xamarin.github.io/bugzilla-archives/12/12468/bug.html
Context: http://www.ecma-international.org/publications/standards/Ecma-334.htm §8.8

C# type name lookup in the context of "dotted names" such as `A.B` is
"interesting", in that name lookup is context sensitive, starting
from the current scope and expanding "outward".  Furthermore, once a
"matching" enclosing namespace is found, the search terminates.

Thus, spot the error:

	// C#
	namespace Example {
	  namespace System {
	  }
	  public class Resource : System.Object {
	    public static int app_name;
	  }
	}

The `Example.Resource` declaration results in a CS0234 error, which
may be surprising:

	error CS0234: The type or namespace name `Object' does not exist in
	the namespace `Example.System'. Are you missing an assembly reference?

There are two fixes:

 1. Add a top-level `using System` directive and have `Resource`
    inherit from `Object` instead of `System.Object`.
    
    This works *until* an `Example.Object` type is introduced, at
    which point the base class of `Resource` implicitly changes.

 2. Have `Example.Resource` inherit from `global::System.Object`.

The C# [`::` operator][0] is the "namespace alias operator", which
separates a "namespace alias" from an identifier.  Identifier lookup
is "rooted" from the specified namespace alias.

The `global` namespace alias represents the "global namespace", the
"root" of all type lookup.

When hand-writing code, solution (1) is almost always the better
solution.

In *generated* code, solution (1) is *rarely* the better solution,
because the code generator may not know what other "colliding" type
names will be brought into scope by a `using namespace` directive.
Solution (2) is thus preferred.

Which is why the `<GenerateResourceDesigner/>` task and
`ResourceDesignerImportGenerator.cs` specify
`CodeTypeReferenceOptions.GlobalReference`, so that `global::` is
emitted everywhere practical.

This works nicely, until C# [`extern alias`][1]es are used, e.g. by
using the [`%(ProjectReference.Aliases)`][2] MSBuild property or the
[`csc -reference:alias=filename` option][3]

	<ProjectReference Include="..\LibraryA\LibraryA.csproj">
	  <Project>{A31DB667-7565-4C13-99CD-82064660960F}</Project>
	  <Name>LibraryA</Name>
	  <Aliases>LibA</Aliases>
	</ProjectReference>

The above `@(ProjectReference)` fragment is translated into a
`csc -reference:LibA=path\to\LibraryA.dll` option.

An "interesting" side effect of such extern aliases is that types
within the referenced assembly are *only* accessible via the extern
reference.  For example, if `LibraryA.dll` contains
`Example.Resource`, then an "unqualified" `Example.Resource` will
result in a [CS0246][4] error.  The `Example.Resource` type within
`LibraryA.dll` can only be accessed as *either*
`Lib1::Example.Resource` *or* `Lib1.Example.Resource`.

(Aside: Which should be preferred, `Lib1::Example.Resource`, or
`Lib1.Example.Resource`?  As per the previous discussion about §8.8
and identifier lookup, the former is more reliable and won't suffer
possible name lookup collisions.)

Which brings us back to the `<GenerateResourceDesigner/>` task: if a
`MonoAndroid`-profile assembly (998fe618) is referenced via an
`extern` alias, *all* types referenced from that assembly *must* be
done "through" a namespace alias, not "unqualified".  Failure to do
so will result in a [CS0400 error][5]:

	// generated C# code
	partial class Resource {
	  public static void UpdateIdValues()
	  {
	    global::Example.Resource.app_name = ...
	    // ...
	  }
	}

	error CS0400: The type or namespace name 'Example' could not be found in the global namespace (are you missing an assembly reference?

To fix this, `<GenerateResourceDesigner/>` must do two things:

 1. Know about all assembly aliases, and emit an `extern alias`
    directive for them, and

 2. Reference types from all assemblies which provide an assembly
    alias through the alias name.

For example, given the previous `@(ProjectReference)` for
`LibraryA.csproj`, the generated `Resource.designer.cs` should
resemble:

	extern alias LibA;
	partial class Resource {
	  public static void UpdateIdValues()
	  {
	    LibA::Example.Resource.app_name = ...
	    // ...
	  }
	}	

[0]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/namespace-alias-qualifier
[1]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias
[2]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.projectreference.aliases?view=roslyn-dotnet
[3]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/reference-compiler-option
[4]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246
[5]: https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0400