[TestJVM] Don't assume that TestJVM.typeMappings is not null.
This is probably a sign of a bigger design issue, which I'm not sure
how to solve; see Aside, below.

The scenario: try to create a JVM!

	$ make shell
	csharp> var vm = new Java.InteropTests.TestJVM (new string[0]);

...promptly blows up REAL GOOD:

	System.TypeInitializationException: An exception was thrown by the type initializer for Java.Interop.ManagedPeer ---> System.NullReferenceException: Object reference not set to an instance of an object
	  at Java.InteropTests.TestJVM.GetTypeForJniSimplifiedTypeReference (System.String jniTypeReference) [0x00055] in /Users/jon/Dropbox/Developer/Java.Interop/tests/TestJVM/TestJVM.cs:67
	  at Java.Interop.JavaVM.GetTypeForJniTypeRefererence (System.String jniTypeReference) [0x00038] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:656
	  at Java.Interop.JavaVM.GetWrapperType (Java.Interop.JniReferenceSafeHandle handle) [0x00012] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:544
	  at Java.Interop.JavaVM.CreateObjectWrapper (Java.Interop.JniReferenceSafeHandle handle, JniHandleOwnership transfer, System.Type targetType) [0x0003c] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:532
	  at Java.Interop.JavaVM.GetObject (Java.Interop.JniReferenceSafeHandle handle, JniHandleOwnership transfer, System.Type targetType) [0x00044] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:523
	  at Java.Interop.JavaVM.GetObject[JavaException] (Java.Interop.JniReferenceSafeHandle jniHandle, JniHandleOwnership transfer) [0x0000e] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:570
	  at Java.Interop.JavaVM.GetExceptionForThrowable (Java.Interop.JniLocalReference value, JniHandleOwnership transfer) [0x00041] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:265
	  at Java.Interop.JniEnvironment.GetExceptionForLastThrowable () [0x0002d] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.cs:157
	  at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x00037] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:2982
	  at Java.Interop.JniType..ctor (System.String classname) [0x00002] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:27
	  at Java.Interop.JniType.GetCachedJniType (Java.Interop.JniType& cachedType, System.String classname) [0x00022] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:82
	  at Java.Interop.JniPeerMembers.get_JniPeerType () [0x0000d] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:44
	  at Java.Interop.JniPeerInstanceMethods..ctor (Java.Interop.JniPeerMembers members) [0x0002b] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniPeerInstanceMethods.cs:11
	  at Java.Interop.JniPeerMembers..ctor (System.String jniPeerType, System.Type managedPeerType) [0x000b9] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:27
	  at Java.Interop.ManagedPeer..cctor () [0x0000f] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/ManagedPeer.cs:14
	  --- End of inner exception stack trace ---
	  at Java.Interop.JavaVM..ctor (Java.Interop.JavaVMOptions options) [0x000f2] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:181
	  at Java.Interop.JreVM..ctor (Java.Interop.JreVMBuilder builder) [0x00002] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Runtime.Environment/Java.Interop/JreVM.cs:146
	  at Java.InteropTests.TestJVM..ctor (System.String[] jars, System.Collections.Generic.Dictionary`2 typeMappings) [0x00002] in /Users/jon/Dropbox/Developer/Java.Interop/tests/TestJVM/TestJVM.cs:32

The cause is twofold:

 1. The `javac` invocations in our .csproj files are "wrong"; they
    need to explicitly specify `javac -target`, otherwise they default
    to the highest supported JDK version, and since the local `javac`
    is from JDK 7, this means the resulting .class file is for JDK 7
    while we're trying to run on JDK 6 (see README.md Requirements).

 2. There's an unfortunate design defect, visible above, in that
    virtual methods are invoked from constructors:

	http://blogs.msdn.com/b/scottwil/archive/2005/01/14/353177.aspx
	http://msdn.microsoft.com/en-us/library/ms182331.aspx
	https://www.google.com/webhp#q=c%23+calling+virtual+methods+from+constructor

What's happening is that JniPeerMembers requires an instance of
com.xamarin.android.ManagedPeer, which can't be loaded due to (1), so
we hit the "normal exception path", which involves translating the
Java exception into a JavaException wrapper, which in turn requires
a JavaVM instance...which we're still in the middle of constructing!

Because the TestJVM constructor hasn't finished executing -- we're
still in fact executing the `: base(...)` expression --
TestJVM.typeMapping is never re-assigned from `null`, which causes
TestJVM.GetTypeForJniSimplifiedTypeReference() to throw a
NullReferenceException.

There are two proper fixes here:

 1. Properly compile the Java code. This will be done later; it's not
    done now so that we can more sanely address exceptional behavior.

 2. "Somehow" move the JavaVM.GetTypeForJniSimplifiedTypeReference()
    invocation outside of the constructor chain, allowing TestJVM to
    finish constructing before methods are invoked upon it.

    Unfortunately, I'm not sure how to do this.

In the meantime, "fix" TestJVM.GetTypeForJniSimplifiedTypeReference()
so that it doesn't throw if typeMappings is null. This provides a much
saner error message [0].

Aside: Why does the JavaVM constructor invoke ManagedPeer.Init()?
(See also commit dd099847.)

The initial rationale was that once a JavaVM instance was initialized,
it should henceforth be usable from Java invocations, supporting
Java (-side) Activation.

Requiring that everything be ready after the JavaVM has finished
construction may itself be a Bad Idea; we may instead want a separate
Initialize() or PrepareForActivation() call. This needs further
consideration.

[0]: csharp> var vm = new Java.InteropTests.TestJVM (new string[0]);
  System.TypeInitializationException: An exception was thrown by the type initializer for Java.Interop.ManagedPeer ---> Java.Interop.JavaException: com/xamarin/android/ManagedPeer : Unsupported major.minor version 51.0
    at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x00057] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:2988
    at Java.Interop.JniType..ctor (System.String classname) [0x00002] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:27
    at Java.Interop.JniType.GetCachedJniType (Java.Interop.JniType& cachedType, System.String classname) [0x00022] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:82
    at Java.Interop.JniPeerMembers.get_JniPeerType () [0x0000d] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:44
    at Java.Interop.JniPeerInstanceMethods..ctor (Java.Interop.JniPeerMembers members) [0x0002b] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniPeerInstanceMethods.cs:11
    at Java.Interop.JniPeerMembers..ctor (System.String jniPeerType, System.Type managedPeerType) [0x000b9] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:27
    at Java.Interop.ManagedPeer..cctor () [0x0000f] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/ManagedPeer.cs:14
    --- End of managed Java.Interop.JavaException stack trace ---
  java.lang.UnsupportedClassVersionError: com/xamarin/android/ManagedPeer : Unsupported major.minor version 51.0
          at java.lang.ClassLoader.defineClass1(Native Method)
          at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
          at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
          at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
          at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
          at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
          at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
          at java.security.AccessController.doPrivileged(Native Method)
          at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
          at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

    --- End of inner exception stack trace ---
    at Java.Interop.JavaVM..ctor (Java.Interop.JavaVMOptions options) [0x000f2] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:181
    at Java.Interop.JreVM..ctor (Java.Interop.JreVMBuilder builder) [0x00002] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Runtime.Environment/Java.Interop/JreVM.cs:143
    at Java.InteropTests.TestJVM..ctor (System.String[] jars, System.Collections.Generic.Dictionary`2 typeMappings) [0x00002] in /Users/jon/Dropbox/Developer/Java.Interop/tests/TestJVM/TestJVM.cs:31
    at <InteractiveExpressionClass>.Host (System.Object& $retval) [0x00000] in <filename unknown>:0
    at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object& result, System.Boolean& result_set) [0x0003e] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/mcs/eval.cs:369
    at Mono.CSharpShell.Evaluate (System.String input) [0x00000] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/tools/csharp/repl.cs:387