[Xamarin.Android.Build.Tasks] support Deterministic builds (#3554)
Fixes: https://github.com/xamarin/xamarin-android/issues/2957
Context: https://blog.paranoidcoding.com/2016/04/05/deterministic-builds-in-roslyn.html

Since Visual Studio 2019, [`$(Deterministic)`][0] is set in the .NET
framework class library project template:

	<PropertyGroup>
	  <Deterministic>True</Deterministic>
	  <!-- ... -->
	</PropertyGroup>

It is also the default for SDK-style projects.

What this setting does is enable a stable MVID for the produced .NET
assembly.  If you do `touch Foo.cs && msbuild`, the resulting
assembly will have its contents unchanged.  However, the timestamp of
the file *will* change.  There may be some narrow performance gains
we can get there.

The only drawback of `$(Determinitic)` is that the following will
produce a CS8357 build error:

	[assembly: AssemblyVersion ("1.0.*")]
	// error CS8357: The specified version string contains wildcards,
	//               which are not compatible with determinism.
	//               Either remove wildcards from the version string,
	//               or disable determinism for this compilation

Since `1.0.*` implies that the assembly changes on incremental
builds, `$(Deterministic)`=True cannot support it.  So we can't just
make it default without breaking someone.

~~ What should we do? ~~

We should start building Xamarin.Android using `$(Deterministic)`=True
and add a few tests for it.  We had some usage of
`[assembly:AssemblyVersion]` wildcards that seemed unnecessary.

When `$(Deterministic)`=True, any places using Mono.Cecil need to use
the appropriate `WriterParameters.DeterministicMvid` setting when
writing assemblies.  The linker has an equivalent
`LinkContext.DeterministicOutput` property.

After this change makes it in, we should consider putting
`<Deterministic>True</Deterministic>` in the Xamarin templates.
We would also need to remove some comments in `AssemblyInfo.cs` that
suggests to use `[assembly: AssemblyVersion ("1.0.*")]`.

~~ Other changes ~~

I added a few general fixes to `Xamarin.ProjectTools`:

  * Made properties so `AndroidUseSharedRuntime` and
    `EmbedAssembliesIntoApk` are strongly typed.
  * Added a `Deterministic` property
  * In `BaseTest`, `CreateApkBuilder()` and `CreateDllBuilder()` now
    have the `directory` parameter optional.

[0]: https://docs.microsoft.com/en-us/dotnet/visual-basic/reference/command-line-compiler/deterministic