[macos] Bump MinGW version (#4438)
New MinGW version is out (7.0.0_2) and it appears that some bots are
sad because they don't have it:

	Full Homebrew executable path value: /usr/local/bin/brew
	Running: /usr/local/bin/brew "tap" "xamarin/xamarin-android-windeps"
	Running: /usr/local/bin/brew "install" "xamarin/xamarin-android-windeps/mingw-zlib"
	stderr | Error: You must `brew unpin mingw-w64` as installing xamarin/xamarin-android-windeps/mingw-zlib requires the latest version of pinned dependencies
	 | ==> Installing mingw-zlib from xamarin/xamarin-android-windeps
	  Error: Installation of xamarin/xamarin-android-windeps/mingw-zlib failed

Please them by updating to the latest version.