[Xamarin.Android.Build.Tasks] Ignore `global` Alias when emitting code.
Fixes #4542

Our previous fix d18c824c did not take into account that users might
need to add `global` to their list of aliases in the `ProjectReferece`
MetaData. This then causes the following error

	Error CS1681: You cannot redefine the global extern alias (CS1681)

So to fix this we need to ignore the `global` entry if one is present.