[xaprepare] remove dependency on the windep homebrew recipe on mac
We've been seeing the attempts to install the recipe time out on our CI
servers:

    Error: Process '/usr/local/bin/brew "install" "xamarin/xamarin-android-windeps/mingw-zlib"' timed out after 00:30:00
    Error: Installation of xamarin/xamarin-android-windeps/mingw-zlib failed

Since the recipe existed only for the benefit of cross-building Mono for
Windows on macOS using mingw and we no longer do that, we can remove the
recipe.