Fix mono master build (#112)
Properly use `nunit.framework.dll` from NuGet packages. Mono 4.9
changes `nunit.framework.dll` so that all types and members are
`[Obsolete(IsError=true)]`, i.e. referencing them results in e.g.:

	GrefsTest.cs(12,3): error CS0619: `NUnit.Framework.TestFixtureAttribute' is obsolete:
	`The NUnit framework shipped with Mono is deprecated and will be removed in a future release.
	It was based on NUnit 2.4 which is long outdated. Please move to the NUnit NuGet package or
	some other form of acquiring NUnit.'

Some project files were properly using the NuGet package, but not all
of them. Fix all of the project files so that the NuGet package's
`nunit.framework.dll` is correctly used.

Additionally, set `$(DebugType)` to `Full` in `TestJVM.csproj`, to
work around a [Roslyn bug][0].
 
[0]: https://bugzilla.xamarin.com/show_bug.cgi?id=51175