[r8] fix Main-Class setting in manifest (#3737)
If you run:

	> java -jar .\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\r8.jar
	Error: Could not find or load main class com.android.tools.r8.SwissArmyKnife

Whoops!  In a85dd5b5 I bumped r8 to 1.5.68, which no longer contains
`com.android.tools.r8.SwissArmyKnife` anymore, but forgot to fix the
`Main-Class` setting.

This is not a problem for Xamarin.Android because it explicitly
provides the Main-Class on the command-line:

	> java -classpath .\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\r8.jar com.android.tools.r8.R8

...but it would be good to fix this anyway, for internal consistency.