[Xamarin.Android.Build.Tasks] fix DirectoryNotFoundException for builds on network shares
Fixes: https://github.com/xamarin/xamarin-android/issues/5218

Builds could fail on a Windows network share with:

    System.IO.DirectoryNotFoundException: Could not find a part of the path 'XYZ'
        at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
        at System.IO.File.InternalDelete(String path, Boolean checkHost)
        at System.IO.File.Delete(String path)
        at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)
        at Xamarin.Android.Tools.Files.ExtractAll(ZipArchive zip, String destination, Action`2 progressCallback, Func`2 modifyCallback, Func`2 deleteCallback, Func`2 skipCallback)
        at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(IDictionary`2 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
        at Xamarin.Android.Tasks.ResolveLibraryProjectImports.RunTask()
        at Xamarin.Android.Tasks.AndroidTask.Execute()

Normally a call to `File.Delete()` completes silently if the file does
not exist:

> If the file to be deleted does not exist, no exception is thrown.

https://docs.microsoft.com/dotnet/api/system.io.file.delete#remarks

However, this does not appear to be the case for a file on a network
share. `DirectoryNotFoundException` is thrown?!?

`Files.CopyIf*Changed` is a hot path, that is called many times
throughout a build. A simple `File.Exists()` check solves the problem,
but we don't want to add additional I/O calls. I made
`MonoAndroidHelper.SetWriteable()` able to optionally skip the
`File.Exists()` check.

When reviewing this code, I fixed some other issues: :eyes:

* `MonoAndroidHelper.SetDirectoryWriteable()` did not have the correct
  enum flags logic to check for `FileAttributes.ReadOnly`.
* `MonoAndroidHelper.SetWriteable()` can avoid using the
  `System.IO.FileInfo` API, as it creates an object on the heap.
  `File.GetAttributes()` and `File.SetAttributes()` are more
  appropriate for this case.