Remove Mono.Linq.Expressions
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3315048&view=logs&jobId=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&j=8556562a-ae5f-5bd1-7c4d-bf1af4b6f1e1&t=5076e147-fc66-561e-6c69-3aa777afefc5

xamarin/Java.Interop@76d6e6dc removed Mono.Linq.Expressions as a
submodule and replaced it with a NuGet package.

Remove the `Mono.Linq.Expressions.csproj` references and replace with
a `@(PackageReference)`.

This change will hopefully allow tests to build now:

	Java.Interop/tests/Java.Interop-Tests/Java.Interop/JniValueMarshalerContractTests.cs(10,12): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'Mono' (are you missing an assembly reference?)