[Xamarin.Android.Build.Tasks] Define `ANDROID_24` in Release builds (#167)
Commit a8f7db05 [broke the *Release* build][0]:

	Mono.Android/LayoutAttribute.Partial.cs(24,6): error CS1593: Delegate `System.Action<Android.App.LayoutAttribute,object>' does not take `1' arguments
	Mono.Android/LayoutAttribute.Partial.cs(25,6): error CS1593: Delegate `System.Func<Android.App.LayoutAttribute,string>' does not take `2' arguments
	Mono.Android/LayoutAttribute.Partial.cs(29,6): error CS1593: Delegate `System.Action<Android.App.LayoutAttribute,object>' does not take `1' arguments
	Mono.Android/LayoutAttribute.Partial.cs(30,6): error CS1593: Delegate `System.Func<Android.App.LayoutAttribute,string>' does not take `2' arguments
	Mono.Android/LayoutAttribute.Partial.cs(34,6): error CS1593: Delegate `System.Action<Android.App.LayoutAttribute,object>' does not take `1' arguments
	Mono.Android/LayoutAttribute.Partial.cs(35,6): error CS1593: Delegate `System.Func<Android.App.LayoutAttribute,string>' does not take `2' arguments
	Mono.Android/LayoutAttribute.Partial.cs(39,6): error CS1593: Delegate `System.Action<Android.App.LayoutAttribute,object>' does not take `1' arguments
	Mono.Android/LayoutAttribute.Partial.cs(40,6): error CS1593: Delegate `System.Func<Android.App.LayoutAttribute,string>' does not take `2' arguments
	Mono.Android/LayoutAttribute.Partial.cs(44,6): error CS1593: Delegate `System.Action<Android.App.LayoutAttribute,object>' does not take `1' arguments
	Mono.Android/LayoutAttribute.Partial.cs(45,6): error CS1593: Delegate `System.Func<Android.App.LayoutAttribute,string>' does not take `2' arguments

The cause of the breakage is that the **Release** Configuration in
`Xamarin.Android.Build.Tasks.csproj` didn't add `ANDROID_24` to
`$(DefineConstants)`, which *was* done in the *Debug* build. Without
`ANDROID_24` being defined, half of the `LayoutAttribute` partial
class present, so the half that was included couldn't build.

Add `ANDROID_24` to `$(DefineConstants)` in the Release configuration.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/45/