What's in `$(_AndroidJar)`?
The current build is failing:

	(GenerateJavaCallableWrappers target) ->
	         /Users/builder/azdo/_work/3/s/android/build-tools/scripts/JavaCallableWrappers.targets(38,5): error MSB3073: The command ""/Users/builder/android-toolchain/jdk-21/bin/javac" -source 17 -target 17 -d "obj/Release/net10.0/android-CANARY/jcw/bin" -classpath "/Users/builder/android-toolchain/sdk/platforms/android-CANARY/android.jar":"/Users/builder/azdo/_work/3/s/android/bin/Release/lib/xamarin.android/xbuild-frameworks/Microsoft.Android/36.1/mono.android.jar":"/Users/builder/azdo/_work/3/s/android/bin/Release/lib/packs/Microsoft.Android.Sdk.Darwin/36.0.0/tools/java_runtime.jar" @obj/Release/net10.0/android-CANARY/jcw/classes.txt" exited with code 1. [/Users/builder/azdo/_work/3/s/android/src/Mono.Android/Mono.Android.csproj::TargetFramework=net10.0]

But *why*?

The `.binlog` contains many errors, which make no sense:

	obj/Release/net10.0/android-CANARY/jcw/src/android/app/ActivityTracker.java:8: error: package android.app.Application does not exist

*How* can `android.app.Application` not exist?!

*Given* that this builds API-36 without errors, I have to wonder
if the problem is that `platforms/android-CANARY/android.jar`
is corrupt.

Update the `GenerateJavaCallableWrappers` target to run
`jar tf $(_AndroidJar)`, so that we can see the contents of
`platforms/android-CANARY/android.jar`.