Bump to xamarin/Java.Interop/main@cf80deb7 (#7664)
Changes: https://github.com/xamarin/java.interop/compare/f8d77faf55347a58030a694332ba97f0dee88246...cf80deb7d2ad3c79abfd0140e4adee4376b41af5

  * xamarin/java.interop@cf80deb7: [Java.Interop.Tools.JavaCallableWrappers] use IMetadataResolver more (xamarin/java.interop#1069)
  * xamarin/java.interop@5c5dc086: [generator] enum map.csv can set `@deprecated-since` for enum values (xamarin/java.interop#1070)

Any place we used:

  * `TypeDefinitionCache?`
  * `IMetadataResolver?`

As of xamarin/java.interop@cf80deb7, Java.Interop no longer allows
`null` values for these parameters, so overloads which were]
`[Obsolete]` now emit errors instead of warnings:

	[Obsolete ("Use the TypeDefinitionCache overload for better performance.", error: true)]
	public static MethodDefinition GetBaseDefinition (this MethodDefinition method) =>
	    GetBaseDefinition (method, resolver: null!);

This results in 3 compiler errors in xamarin-android:

	src\Xamarin.Android.Build.Tasks\Mono.Android\ApplicationAttribute.Partial.cs(65,11):
	  error CS0619: 'TypeDefinitionRocks.IsSubclassOf(TypeDefinition, string)' is obsolete: 'Use the TypeDefinitionCache overload for better performance.'
	src\Xamarin.Android.Build.Tasks\Mono.Android\ApplicationAttribute.Partial.cs(268,12):
	  error CS0619: 'JavaNativeTypeManager.ToJniName(TypeDefinition)' is obsolete: 'Use the TypeDefinitionCache overload for better performance.'
	src\Xamarin.Android.Build.Tasks\Utilities\ManifestDocumentElement.cs(28,11):
	  error CS0619: 'JavaNativeTypeManager.ToJniName(TypeDefinition)' is obsolete: 'Use the TypeDefinitionCache overload for better performance.'

After these changes, it appears we will improve the performance
further of apps that use:

  * `ApplicationAttribute.BackupAgent`
  * `ApplicationAttribute.Name`
  * `AndroidManifest.xml` attributes that take a `System.Type` values

Additionally, fix a `NullReferenceException` in the linker:

	Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
	   at Java.Interop.Tools.Cecil.TypeDefinitionRocks.GetBaseType(TypeDefinition type, IMetadataResolver resolver) in /Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:line 21
	   at Java.Interop.Tools.Cecil.TypeDefinitionRocks.GetTypeAndBaseTypes(TypeDefinition type, IMetadataResolver resolver)+MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:line 36
	   at Java.Interop.Tools.Cecil.TypeDefinitionRocks.IsSubclassOf(TypeDefinition type, String typeName, IMetadataResolver resolver) in /Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:line 87
	   at MonoDroid.Tuner.FixAbstractMethodsStep.ProcessType(TypeDefinition type) in /Users/builder/azdo/_work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs:line 81
	   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
	   at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason, MessageOrigin& origin)
	   at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
	   at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
	   at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
	   at Mono.Linker.Steps.MarkStep.MarkModule(ModuleDefinition module, DependencyInfo reason)
	   at Mono.Linker.Steps.MarkStep.ProcessMarkedPending()
	   at Mono.Linker.Steps.MarkStep.Initialize()
	   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
	   at Mono.Linker.Pipeline.Process(LinkContext context)
	   at Mono.Linker.Driver.Run(ILogger customLogger)
	   at Mono.Linker.Driver.Main(String[] args)

This was caused by removing `null` checks in Java.Interop.

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>