[Xamarin.Android.Build.Tasks] 3 tales of #deletebinobj (#2057)
I got report from a customer (over email) of an error such as:

	Java.Lang.ClassNotFoundException: Didn't find class "com.google.android.gms.R$string" on path: DexPathList

The build log showed the app was using a combination of Firebase with
MultiDex enabled, so I tried the Firebase sample from the docs team:

	https://github.com/xamarin/monodroid-samples/tree/master/Firebase/FCMNotifications

Things appeared to work fine, but something seemed strange: my
"spider sense" was going off.  My initial thought was that the
customer recently enabled MultiDex, and toggling MultiDex on/off was
breaking the build.

Oh, it was much worse than that.

I wrote a simple test with the following scenario:

 1. Build an app that *requires* MultiDex, w/ many methods
 2. Check we have `classes.dex`, `classes2.dex`, `classes3.dex`
 3. Remove the Java code with all the methods, so MultiDex is no longer required
 4. Build again
 5. We should *only* have `classes.dex`

Here I found problem No. 1:

    <Delete Files="$(IntermediateOutputPath)android\bin\classes\*.dex" />

Not only is this the *wrong directory* -- which should be
`$(IntermediateOutputPath)android\bin\*.dex` -- but this is also an
incorrect use of the `<Delete/>` task!  Using wildcards like this
requires use of an `<ItemGroup/>` to "gather" the paths.

I added an `<ItemGroup/>` and moved on:

	<ItemGroup>
	  <_DexesToDelete Include="$(IntermediateOutputPath)android\bin\*.dex" />
	</ItemGroup>
	<Delete Files="@(_DexesToDelete)" />

Then I found problem No. 2: After it was now properly deleting the
`.dex` files, `classes2.dex` and `classes3.dex` were still recreated!

Looking into `obj\Debug\android\bin\classes`, I saw e.g.
`ManyMethods.class` and `ManyMethods2.class`, which should *not*
exist, as step (3) removed them!

Nothing deletes old `*.classes` files!  (I guess they are just left
around?)  `javac` happily overwrites existing `class` files as needed?

So I added a call to remove the `classes` directory before `<Javac/>`:

    <RemoveDir Directories="$(IntermediateOutputPath)android\bin\classes" />

Then I found problem No 3: when inspecting `obj`, I noticed
`obj\Debug\android\bin\classes.zip` still contained the types
`ManyMethods.class` and `ManyMethods2.class`, even though they were
deleted...

It looked like the `<Javac/>` task was *appending* to the zip file!

I added a final `<Delete/>` to remove `classes.zip`:

    <Delete Files="$(IntermediateOutputPath)android\bin\classes.zip" />

And my test now passes.

How did this ever work?!