[generator] Copy ClassGen into JavaClass
Context: https://github.com/xamarin/xamarin-android/pull/1633#issuecomment-387069574

Turning `SymbolTable` into a non-`static` class (04a30176) broke all
manner of things when trying to integrate with xamarin-android --
partially fixed by 1dd41802, 370cc9c8, and 3af4653a -- yet we *still*
can't bump, because Java.Interop/3af4653a causes the
[`BindingBuildTest/RemoveEventHandlerResolution()` unit test fails][0].

[0]: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3075/testReport/junit/Xamarin.Android.Build.Tests/BindingBuildTest/RemoveEventHandlerResolution___Debug/

	error CS0115: 'SherlockPreferenceActivity.OnTitleChanged(ICharSequence, int)': no suitable method found to override

Further investigation determined that the CS0115 occurred because
during the binding project build `generator.exe --only-xml-adjuster`
is executed. In a pre-04a30176 world, the result of
`generator.exe --only-xml-adjuster` resulted in *no* methods with the
name `onTitleChanged`; in 3af4653a, there are *many*.

`generator.exe --only-xml-adjuster` in turn started emitting the
`onTitleChanged` methods because
`JavaApiOverrideMarkerExtensions.MarkBaseMethod()` wasn't able to
resolve the base class to `android.preference.PreferenceActivity`,
which meant it thought that `onTitleChanged()` was a *new* method,
thus keeping it within the resulting `api.xml` file.

`JavaApiOverrideMarkerExtensions.MarkBaseMethod()` couldn't resolve a
base class for `android.preference.PreferenceActivity` because
`JavaApiDllLoaderExtensions.LoadReferences()` *no longer set base
class information*.

And *here* we have the problem, an error of omission: Commit 04a30176
changed `JavaApiDllLoaderExtensions.Load(JavaClass, ClassGen)` to
`JavaApiDllLoaderExtensions.Load(JavaClass, CodeGenerationOptions, ClassGen)`,
but *the call site didn't change* to provide the new parameter.
Additionally, there was an applicable overload. Consequently, the
"offending" line:

	kls.Load ((ClassGen) gen);

*changed semantic meaning* in 04a30176: instead of calling
`JavaApiDllLoaderExtensions.Load(JavaClass, ClassGen)`, it now called
`JavaApiDllLoaderExtensions.Load(JavaClass, GenBase)`,
*which doesn't set the base class*.

(Even "better", the offending line -- the line which needed changing
-- doesn't even *appear* within 04a30176.)

Fix this oversight: Update
`JavaApiDllLoaderExtensions.LoadReferences()` so that a
`CodeGenerationOptions` is now required, and update callers
accordingly.