[build] Support building *from clean* with `msbuild` (Take 2!) (#391)
Commit 7343965a didn't succeed in actually building `xamarin-android`
with `msbuild` on our Jenkins bot. :-(

Time to take another stab at it.

As an added complication, my local `msbuild` behavior (mono 4.8)
differs from Jenkins' `msbuild` behavior (mono 4.4), specifically
around MSB3644. [On Jenkins][msb-96], it's a warning:

	warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found.

When I run locally, it's an *error*. Go figure.

Fixing the local error requires that I *remove* the
`$(TargetFrameworkRootPath)` MSBuild property from
`Configuration.props`, added in commit 255a569b. The issue is that
`$(TargetFrameworkRootPath)` is an *override*, an "absolute" override.
Thus, when e.g. building `Xamarin.Android.Build.Tasks.csproj`, the
`.NETFramework,Version=v4.5` framework -- and corresponding
`mscorlib.dll` -- cannot be resolved, and everything breaks.

(Which raises the wonderful question of whether removing
`$(TargetFrameworkRootPath)` will cause the Linux build to break
again, but we'll cross that bridge later...)

Removing `$(TargetFrameworkRootPath)` in turn requires that I remove
the explicit `@(Reference)`s to `System.Runtime` which commit
7343965a added when building under `xbuild`. This also means that we
no longer need the `$(_XABuildingWithXBuild)` property.
(The "history" eluded to in 7343965a? It's continuing! Argh!)

Additionally, fix the logging from the `<UnzipDirectoryChildren/>`
task so that it prints the *correct* task name, *not* `Unzip`.
(Seeing the wrong task name in log files makes things *confusing*.)

With my local `msbuild` faiklures fixed, we can turn our attention to
to the [errors reported on Jenkins][msb-96]. They are variations on
the same "form":

	# from build-tools/mono-runtimes
	.../external/mono/configure LDFLAGS=...
	...
	EXEC : error : /Applications/Xcode8.1-beta1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `-' in: --config

	# from src/sqlite-xamarin
	.../android create project -g -n sqlitesample -p . -a MainActivity -t android-25 --package com.xamarin.sqlitesample -v 1.0.0
	EXEC : error : Project folder '.' is not empty. Please consider using 'android update' instead.

The issue here is that MSBuild is "better" than xbuild: xbuild only
checks the process exit code for errors. The above
`android create project` command has en exit code of 0, i.e. it didn't
error...according to xbuild.

That said, when running [with xbuild][xb-203]:

	Task "Exec"
		Executing: .../android create project -g -n sqlitesample -p . -a MainActivity -t android-25 --package com.xamarin.sqlitesample -v 1.0.0
		Environment variables being passed to the tool:
		Error: Project folder '.' is not empty. Please consider using 'android update' instead
		...
	Done executing task "Exec"
	Task "Copy"
		...

Rephrased: `android create project ...` is emitting an "Error: ..."
*message*, but even when it emits that message the exit status is
still 0 (no error).

xbuild is only checking the exit status, and thus continues the build.

MSBuild not only checks the exit status, but *also* checks the command
*output*, looking for the string `error`. Because an "error" message
is printed, MSBuild flags this as an error, halting the build.

The fix? Set `Exec.IgnoreStandardErrorWarningFormat=True` on all
`<Exec/>` tasks which invoke **make**(1) or `configure` within
`build-tools/mono-runtimes` and `src/sqlite-xamarin`. Setting
`Exec.IgnoreStandardErrorWarningFormat=True` prevents the `<Exec/>`
task from scanning the task output for "error", causing `msbuild` to
behave like `xbuild` and only use the process exit code for errors.
This allows the build to continue.

[msb-96]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-msbuild/96/consoleText
[xb-203]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/203/consoleText