Fix build when Java.Interop.Tools.Cecil is built outside the tree. (#74)
Before this fix, it failed to build due to bogus reference resolution in
nuget somehow:

```
Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs(99,16): error CS0012: The type `Mono.Cecil.Cil.SequencePoint' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Xamarin.Android.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
				/sources/monodroid/monodroid/out/lib/mandroid//Java.Interop.Tools.Diagnostics.dll (Location of the symbol related to previous error)
			Task "Csc" execution -- FAILED
			Done building target "CoreCompile" in project "/sources/monodroid/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj".-- FAILED
		Done building project "/sources/monodroid/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "ResolveProjectReferences" in project "/sources/monodroid/Java.Interop/tools/generator/generator.csproj".-- FAILED
Done building project "/sources/monodroid/Java.Interop/tools/generator/generator.csproj".-- FAILED
```

I have added explicit $(MSBuildThisFileDirectory) to fix the issue.