[sqlite-xamarin] Unhide symbols in the native library (#2712)
After commit 52190d70, all the native libraries we build that use
cmake were built with the `-fvisibility=hide` compiler flag, which
hides all the symbols defined by the library unless told otherwise
on per-symbol basis.

This flag change is not desired for our build of SQLite since,
obviously, its functions have to be visible in order for
`Mono.Data.Sqlite` to be able to P/Invoke them, otherwise we end up
in a situation when we have the following errors on the runtime:

	UNHANDLED EXCEPTION:
	System.TypeInitializationException: The type initializer for 'Mono.Data.Sqlite.UnsafeNativeMethods' threw an exception. ---> System.EntryPointNotFoundException: sqlite3_libversion_number
	  at (wrapper managed-to-native) Mono.Data.Sqlite.UnsafeNativeMethods.sqlite3_libversion_number()
	  at Mono.Data.Sqlite.UnsafeNativeMethods..cctor () [0x00000] in :0
	   --- End of inner exception stack trace ---

caused by the failure to look up symbols in the DSO:

	Mono    : DllImport attempting to load: 'libsqlite3_xamarin.so'.
	Mono    : DllImport loaded library './libsqlite3_xamarin.so'.
	Mono    : DllImport searching in: 'libsqlite3_xamarin.so' ('./libsqlite3_xamarin.so').
	Mono    : Searching for 'sqlite3_open_v2'.
	Mono    : Probing 'sqlite3_open_v2'.
	Mono    : Could not find 'sqlite3_open_v2' due to 'Could not find symbol 'sqlite3_open_v2'.'.
	Mono    : Probing 'sqlite3_open_v2'.
	Mono    : Could not find 'sqlite3_open_v2' due to 'Could not find symbol 'sqlite3_open_v2'.'.
	Mono    : Probing 'sqlite3_open_v2A'.
	Mono    : Could not find 'sqlite3_open_v2A' due to 'Could not find symbol 'sqlite3_open_v2A'.'.
	Mono    : Probing 'sqlite3_open_v2A'.
	Mono    : Could not find 'sqlite3_open_v2A' due to 'Could not find symbol 'sqlite3_open_v2A'.'.
	Mono    : DllImport searching in: 'libsqlite3_xamarin.so' ('./libsqlite3_xamarin.so').
	Mono    : Searching for 'sqlite3_open'.
	Mono    : Probing 'sqlite3_open'.
	Mono    : Could not find 'sqlite3_open' due to 'Could not find symbol 'sqlite3_open'.'.
	Mono    : Probing 'sqlite3_open'.
	Mono    : Could not find 'sqlite3_open' due to 'Could not find symbol 'sqlite3_open'.'.
	Mono    : Probing 'sqlite3_openA'.
	Mono    : Could not find 'sqlite3_openA' due to 'Could not find symbol 'sqlite3_openA'.'.
	Mono    : Probing 'sqlite3_openA'.
	Mono    : Could not find 'sqlite3_openA' due to 'Could not find symbol 'sqlite3_openA'.'.
	Mono    : DllImport searching in: 'libsqlite3_xamarin.so' ('./libsqlite3_xamarin.so').
	Mono    : Searching for 'sqlite3_libversion_number'.
	Mono    : Probing 'sqlite3_libversion_number'.
	Mono    : Could not find 'sqlite3_libversion_number' due to 'Could not find symbol 'sqlite3_libversion_number'.'.
	Mono    : Probing 'sqlite3_libversion_number'.
	Mono    : Could not find 'sqlite3_libversion_number' due to 'Could not find symbol 'sqlite3_libversion_number'.'.

This commit rectifies the situation by making the default visibility
configurable on the per-project basis and setting it to `default` for
the SQLite build.

Also, tests are added to `Mono.Android-Tests` to make sure SQLite
actually works on device.