[tests] Fix compilation on Windows (#926)
Context: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1047263

A couple of fixes to get `Xamarin.Android.Bcl-Tests` and
`Xamarin.Android-Tests.sln` compiling on Windows:

The `<SystemUnzip/>` task is passing some file paths to
`Directory.EnumerateFiles()`:

	System.IO.IOException: The directory name is invalid.
	at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	at System.IO.FileSystemEnumerableIterator`1.CommonInit()
	at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
	at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
	at Xamarin.Android.BuildTools.PrepTasks.SystemUnzip.<ExtractFile>d__22.MoveNext() in E:\A\_work\1\s\build-tools\xa-prep-tasks\Xamarin.Android.BuildTools.PrepTasks\SystemUnzip.cs:line 128


Fix this by renaming `SystemUnzip.GetExtractedSourceEntries()` to
`SystemUnzip.GetExtractedSourceDirectories()` and have it return
only directories.

MSBuild is getting a duplicate `@(Compile)` entry passed to `<Csc/>`
for `obj/Debug/App.cs`. There was a conditional `@(Compile)` entry as
well as one added during the `_GenerateApp_cs` target. It seems simpler to
just remove the condition and the duplicate `@(Compile)` entry, since
`$(BuildDependsOn)` causes the `_GenerateApp_cs` target to run first.