[build] Fix Homebrew/openssl
Recently some CI builds are ending early, because Homebrew is failing
like this:

    Installing automake
    ...
    stderr | Error: Not a directory @ dir_s_rmdir - /usr/local/Cellar/openssl
     | Removing: /usr/local/Cellar/openssl/1.0.2t... (1,787 files, 12MB)

    Error: Installation of automake failed