[Xamarin.Android.Build.Tasks] Ignore `global` Alias when emitting code. (#4554)
Fixes: https://github.com/xamarin/xamarin-android/issues/4542

Our previous fix in d18c824c did not take into account that users
might need to add `global` to their list of aliases in the
`%(ProjectReference.Aliases)` metadata.  This then causes the
following error:

	Error CS1681: You cannot redefine the global extern alias (CS1681)

Fix this by ignoring the `global` entry if one is present.