[java-runtimes] Set `%JAVA_HOME%`
For some unknown reason, the JDK environment on @jonpryor's Windows
machine is "wonky," in that the `src\java-runtimes` directory fails
to build because the Android SDK `dx` command fails to execute
because `dx` cannot find Java:

	> cd src\java-runtimes
	> msbuild
	...
	ERROR: No suitable Java found. In order to properly use the Android Developer
	Tools, you need a suitable version of Java JDK installed on your system.
	We recommend that you install the JDK version of JavaSE, available here:
	  http://www.oracle.com/technetwork/java/javase/downloads

	If you already have Java installed, you can define the JAVA_HOME environment
	variable in Control Panel / System / Avanced System Settings to point to the
	JDK folder.

	You can find the complete Android SDK requirements here:
	  http://developer.android.com/sdk/requirements.html

This happens when:

 1. `%JAVA_HOME%` refers to a non-existent directory.
    (*How* @jonpryor got an invalid directory in there...)  *or*

 2. `%JAVA_HOME%` is empty and `$(JavaSdkDirectory)` refers to a
    *valid* directory.

(Again, why this happens to @jonpryor but not others on the team has
not yet been determined.)

Fix this by explicitly providing `%JAVA_HOME%` within the `<Exec/>`
task which executes `dx`, so that `java` can be found.