[prepare] Fix build break
b1edd489 inadvertently introduced a [build break][0]:

	ConfigAndData/Dependencies/AndroidToolchain.cs(46,132): error CS0103: The name 'AndroidPkgRevision' does not exist in the current context

Oops.

Fix the build break.

[0]: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2900128&view=logs&jobId=9342f22e-3bed-57a4-899d-de689bc4e23b