[build] Java.Interop-MonoAndroid wildcards too much (#409)
Downstream in xamarin/xamarin-android, after running:

	msbuild Xamarin.Android.sln
	msbuild Xamarin.Android.sln /p:Configuration=Release

You run into an odd build error:

	(CoreCompile target) ->
	    obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
	    obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
	    obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyCopyrightAttribute' attribute
	    obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
	    obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
	    obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
	    obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
	    obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(21,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute

The `@(Compile)` item group included:

	obj\Debug\netstandard2.0\Java.Interop.AssemblyInfo.cs
	obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs

We have a wildcard in this project to emulate SDK-style projects:

	<Compile Include="**\*.cs" />

We need to exclude `obj` and `obj-MonoAndroid` from this wildcard.

Unfortunately, in excluding `obj*` from the build, the "new normal"
.NET Standard Library Project convention of using the
`$(AssemblyVersion)` and related MSBuild properties to generate an
`AssemblyInfo.cs` file no longer works, because
`Java.Interop.AssemblyInfo.cs` is generated within the `obj*`
directory (see above).  Without `Java.Interop.AssemblyInfo.cs`, there
is no `[AssemblyVersionAttribute]`, and things break because of
assembly strong-naming:

	MainActivity.cs(40,81): error CS1705: Assembly 'Xamarin.Android.Support.Fragment' with identity 'Xamarin.Android.Support.Fragment, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Java.Interop' with identity 'Java.Interop, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

Square this circle by setting `$(GenerateAssemblyInfo)`=False and
partially reverting commit bc77a8e, by re-introducing a
`Properties\AssemblyInfo.cs` which specifies these custom attribues.

This way we can properly include the following attributes when
`Java.Interop-MonoAndroid.csproj` is built:

	[assembly: AssemblyTitle ("Java.Interop")]
	[assembly: AssemblyDescription ("")]
	[assembly: AssemblyCulture ("")]
	[assembly: AssemblyConfiguration ("")]
	[assembly: AssemblyCompany ("Microsoft Corporation")]
	[assembly: AssemblyCopyright ("Microsoft Corporation")]
	[assembly: AssemblyProduct ("")]
	[assembly: AssemblyTrademark ("Microsoft Corporation")]
	[assembly: AssemblyVersion ("0.1.0.0")]