[build] Support building with system Mono 4.8 (#454)
Context: https://github.com/xamarin/xamarin-android/pull/451
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=52673

Trying to build xamarin-android with Mono 4.8's `msbuild` had some
"interesting" results:

1. `src/Mono.Android/Mono.Android.csproj` failed to build.
2. `src/monodroid/monodroid.mdproj` failed to build.

`make prepare MSBUILD=msbuild` would fail within `Mono.Android.csproj`
with the error:

	error MSB3644: The reference assemblies for framework "MonoAndroid,Version=v7.1" were not found.

The problem appears to be in `msbuild`s
[`ToolLocationHelper.GetPathToReferenceAssembliesActual()`][0],
which has a `static` (*global*) cache that depends on filesystem
state. For reasons I'm still not clear on, MSBuild is trying to
resolve the `MonoAndroid,Version=v7.1` framework considerably earlier
than I would expect -- before the
`MonoAndroid\v7.1\RedistList\FrameworkList.xml` file is created --
and the results of that "early" lookup are *cached*.
Meaning when MSBuild tries to resolve that framework "later," it
*fails*, even though by that time it exists.

Fix this issue by:

1. Updating `//Target/@BeforeTargets` to be before
    `GetReferenceAssemblyPaths` to fix "local" builds
    (`cd src/Mono.Android; msbuild`). Keep the previous
    `ResolveReferences` value for Mono 4.4/4.6 compatibility,
    and also (try to) run before `GetTargetFrameworkProperties` in a
    feeble effort to fix the "MonoAndroid,Version=v7.1 is resolved too
    early" problem.

2. `$(TargetFrameworkRootPath)` can't be a relative path, as it
    doesn't work reliably with the `GetReferenceAssemblyPaths` target.
    (I don't know why it isn't reliable; it just doesn't work unless
    it's a full path, via `$(MSBuildThisFileDirectory)`.)

3. In `Mono.Android.csproj`, set `$(TargetFrameworkVersion)` to v1.0.
    Yes, this seems quite "wrong," but since the
    `MonoAndroid\v1.0\RedistList\FrameworkList.xml` file is created
    *much* earlier -- as part of `build-tools\mono-runtimes` -- this
    more reliably populates the MSBuild framework cache correctly.

Fortunately `Mono.Android.csproj` uses `$(AndroidFrameworkVersion)` in
`$(OutputPath)`, so setting `$(TargetFrameworkVersion)` doesn't appear
to break anything else...

Update `Makefile` so that `$(USE_MSBUILD)` can be explicitly set, in
addition to auto-detecting when `$(MSBUILD)` is `msbuild`:

	make prepare MSBUILD=path/to/msbuild USE_MSBUILD=1 V=1

`src/monodroid.mdproj` is another problem entirely, captured by
<https://bugzilla.xamarin.com/show_bug.cgi?id=52673>: when item
metadata references an MSBuild property which is derived from an item
group, Mono 4.8's `msbuild` doesn't propertly expand the item group
when referencing the item metadata.

In concrete terms, when building with Mono 4.8's `msbuild`,
`%(_HostRuntime.CFlags)` *did not contain* the values of
`@(JdkIncludePath)`. This in turn meant that `<jni.h>` couldn't be
found (!):

	jni/jni.c:7:10: fatal error: 'jni.h' file not found
	#include <jni.h>
	         ^

Workaround the problem by moving `@(JdkIncludePath)` use into
`%(_HostRuntime.CFlags)` *directly*, not indirectly through
`$(_CommonCFlags)`/`$(_HostUnixCFlags)`.

[0]: https://github.com/mono/msbuild/blob/ce25647/src/Utilities/ToolLocationHelper.cs#L2128-L2180