[monodroid] Change the System.Native dllmap target on osx (#3030)
Context: https://github.com/xamarin/designer/pull/1967
Context: https://github.com/xamarin/monodroid/runs/113546542
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2629298

One of the designer integration tests is failing on Mac with:

	Unhandled Exception:
	System.TypeInitializationException: The type initializer for 'System.Console' threw an exception. ---> System.DllNotFoundException: libmono-native.so
	  at (wrapper managed-to-native) Interop+Sys.Stat(byte&,Interop/Sys/FileStatus&)
	  at Interop+Sys.Stat (System.ReadOnlySpan`1[T] path, Interop+Sys+FileStatus& output) [0x00028] in <ca2a591e441f458bb6bef167b4521022>:0
	  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <ca2a591e441f458bb6bef167b4521022>:0
	  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath) [0x00006] in <ca2a591e441f458bb6bef167b4521022>:0
	  at System.IO.File.Exists (System.String path) [0x00043] in <ca2a591e441f458bb6bef167b4521022>:0
	  at System.IO.LogcatTextWriter.IsRunningOnAndroid () [0x00000] in <ca2a591e441f458bb6bef167b4521022>:0
	  at System.Console.SetupStreams (System.Text.Encoding inputEncoding, System.Text.Encoding outputEncoding) [0x00050] in <ca2a591e441f458bb6bef167b4521022>:0
	  at System.Console..cctor () [0x0004f] in <ca2a591e441f458bb6bef167b4521022>:0

The "obvious" problem is that it should be loading
`libmono-native.dylib`, which in turn suggests that
`src/monodroid/config.xml` needs the "same" fix that b8c30f9e added
to `src/Xamarin.Android.Build.Tasks/mono.config`.

Unfortunately, this didn't work, as mono never attempted to load
`/Library/Framworks/Xamarin.Android.framework/…/libmono-native.dylib`
which meant we *still* had a `TypeInitializationException`.

Instead, remap `System.Native` on macOS to `__Internal`, and require
that the Designer pre-load the appropriate `libmono-native.dylib` as
part of its process startup code, just as it does with the
`libxamarin-app` library (decfbccf, [xamarin/designer@59b3061b][0]).

[0]: https://github.com/xamarin/designer/commit/59b3061b99990dc6277cfa1d0836034b861361fb