[Java.Interop] Fix build break on fresh checkout.
Commit 11210c8a broke things by renaming JniPeerFields.tt to
JniPeerMembers.JniFields.tt, but it *didn't* rename JniPeerFields.cs
to JniPeerMembers.JniFields.cs, resulting in a build failure:

	CSC: error CS2001: Source file `Java.Interop/JniPeerMembers.JniFields.cs' could not be found

Renaming JniPeerMembers.tt to JniPeerMembers.JniMethods.tt also
results in breakage; fix that rename as well.