[CoreCLR] Initial support of R2R builds (#10007)
Context: https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run
Context: https://github.com/dotnet/runtime/blob/c83f92ad7aa7afa152b833a8e8f5ffe36a3287d1/docs/design/coreclr/botr/readytorun-overview.md
Context: https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/readytorun-format.md
Context: https://github.com/xamarin/monodroid/commit/f22cc208374637fea59bef7f849bff29247a3e5a


ReadyToRun (R2R) is a form of ahead-of-time compilation supported by
CoreCLR.It works by adding setting the `ManagedNativeHeader`
CLR header entrypoint to refer to a `READYTORUN_HEADER` section.

R2R is enabled by using `dotnet publish` alongside
`$(PublishReadyToRun)`=true:

	dotnet new console
	dotnet publish -p:PublishReadyToRun=true

You can see some of the changes that R2R produces by using
[`dumpbin /CLRHEADER`][0].  Consider the original assembly:

	> dumpbin /clrheader .\obj\Release\net9.0\win-x64\*.dll
	…
	  clr Header:
	         …
	         6000001 entry point token
	               …
	               0 [       0] RVA [size] of ManagedNativeHeader Directory

vs. the R2R assembly:

	> dumpbin /clrheader .\obj\Release\net9.0\win-x64\R2R\*.dll
	…
	  clr Header:
	         …
	         6000001 entry point token
	               …
	            1548 [      94] RVA [size] of ManagedNativeHeader Directory

The `ManagedNativeHeader` entry point having a non-zero RVA indicates
that the assembly contains native machine code, possibly R2R data.

Enable R2R usage with .NET for Android and CoreCLR, when
`$(UseMonoRuntime)`=false.  Additionally, `$(RuntimeIdentifier)` must
be set, via `-r RID`:

	dotnet new android
	dotnet publish -p:PublishReadyToRun=true -p:UseMonoRuntime=false -r android-arm64

The resulting packaged assemblies will contain R2R data.

## Problem

Android app build runs two assembly post-processing build tasks which
modify assemblies using Mono.Cecil:
`<RewriteMarshalMethods/>` (86260ed36d) and
`<RemoveRegisterAttribute/>` (xamarin/monodroid@f22cc208).
Unfortunately, if this happens *after* R2R image generation, Cecil
will throw a NotSupportedException, as Cecil does not support
modifying assemblies which contain native data:

	System.NotSupportedException: Writing mixed-mode assemblies is not supported
	   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
	   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
	   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
	   at Mono.Cecil.ModuleDefinition.Write(WriterParameters parameters)
	   at Mono.Cecil.ModuleDefinition.Write()
	   at Mono.Cecil.AssemblyDefinition.Write()
	   at Xamarin.Android.Tasks.RemoveRegisterAttribute.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/RemoveRegisterAttribute.cs:line 37
	   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25

"Fix" this by *disabling* use of the `<RewriteMarshalMethods/>` 
and `<RemoveRegisterAttribute/>` tasks when using R2R.

## TODO

Investigate running R2R image generation build task after
`<RewriteMarshalMethods/>` and `<RemoveRegisterAttribute/>` so that
R2R builds could also benefit from the performance improvements these
build tasks bring.

Investigate running R2R image generation as part of the
`$(RuntimeIdentifiers)` inner build, so that `-r RID` is not required.

Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>

[0]: https://learn.microsoft.com/en-us/cpp/build/reference/clrheader?view=msvc-170