[tests] fix BuildAMassiveApp under MSBuild (#1095)
Context: https://devdiv.visualstudio.com/DevDiv/Default/_build/index?buildId=1206705&tab=ms.vss-test-web.test-result-details

`BuildAMassiveApp` has been failing under MSBuild with:

```
E:\A\_work\1\s\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\Xamarin.Android.Common.targets(1167,2):
error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'Lib0,
Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Lib0.dll'
```
It turns out that setting `$(BuildingInsideVisualStudio)` signals MSBuild
that it doesn't need to figure out project dependencies. So
`Lib0.csproj` isn't built at the time `ResolveLibraryProjectImports`
runs.

For now, it seems simpler to turn off `BuildingInsideVisualStudio` in
this test under MSBuild, since it was not the goal of the test to verify
how things would work inside Visual Studio.