[mono-runtimes] Run `mono --arch=32 MonoAotOffsetsDumper.exe`
Commit 4664057a fixed it's error, but there is yet another
[build break][0] caused by commit 8cc4acb0:

	Executing: MONO_PATH=…/xamarin-android/external/mono/tools/offsets-tool/CppSharp/osx_32 \
		mono …/xamarin-android/external/mono/tools/offsets-tool/MonoAotOffsetsDumper.exe \
		--android-ndk="/Users/builder/android-toolchain/ndk" \
		--mono="…/xamarin-android/external/mono" \
		--monodroid="…/xamarin-android/" \
		--abi="armv5-none-linux-androideabi" \
		--targetdir="…/xamarin-android/build-tools/mono-runtimes/obj/Release//armeabi" \
		--out="…/xamarin-android/build-tools/mono-runtimes/obj/Release//cross-arm"
	Processing triple: armv5-none-linux-androideabi
	Unhandled Exception:
	System.DllNotFoundException: CppSharp.CppParser.dll
		at (wrapper managed-to-native) CppSharp.Parser.CppParserOptions+__Internal:ctor_0 (intptr)
	…

The problem is that Mono 5.2 changes `mono` to run a *64-bit* runtime
by default (previous versions used 32-bit runtimes by default), and
`libCppSharp.CppParser.dylib` is only provided in a 32-bit version.
The result is the `DllNotFoundException`, as above.

The fix is to use `mono --arch=32 MonoAotOffsetsDumper.exe` to ensure
that a 32-bit runtime is used.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/384