[tests] Wait for the emulator to fully boot (#620)
- so that we avoid issue like this (from Jenkins log):

         Task Adb
           Arguments: -s emulator-5570  uninstall "Mono.Android_Tests"
         Tool /Users/builder/android-toolchain/sdk/platform-tools/adb execution started with arguments: -s emulator-5570  uninstall "Mono.Android_Tests"
         Environment variables being passed to the tool:
         Error: Could not access the Package Manager.  Is the system running?