[ci] Move Windows build and test to VS2019 (#3552)
We've been encountering a handful of issues recently with the Windows
machine pool we're using for building and testing.  There have been
quite a few failures caused by files being locked, or dependencies
being out of date or missing, or CS8107 errors on the
[mono/2019-08 bump PR][0] because source code is using C#7.1 features:

	external\linker\src\linker\Linker.Steps\MarkStep.cs(2272,19): Error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.

[0]: https://github.com/xamarin/xamarin-android/pull/3449

Moving to the VSEng VS2019 Windows pool will hopefully resolve some
of these issues.

Unfortunately the size of our build dependencies presents an issue
when attempting to use the Microsoft hosted Windows VS2019 agents, as
our Win job ultimately runs out of space when executing on those VMS.
Using the VSEng VS2019 pool will allow us to migrate to VS2019 while
avoiding disk space limitations.

Additionally, as of commit 8cdda115, `$(JavaSdkDirectory)` will have
a default value of the path to the Corretto JDK we install on both
Windows and macOS.  We should try to use this JDK path for all
Android/Java tool invocations which require `$(JAVA_HOME)` to be set.

Finally, remove the `Builder.MicrosoftNetSdkDirectory` property and
related attempts to find the .NET Core SDK path, as
`azure-pipelines.yaml` now explicitly installs our required
.NET Core SDK version.