[build] Build the latest stable platform. (#1809)
Commit 01988e08 broke the `<ResolveSdks/>` task because it forced the
system to build the v1.0 and v9.0 apis, and v9.0 is unstable.
As such, when attempting to find the "latest stable API level,"
`<ResolveSdks/>` would fail, as there aren't any stable APIs

        The "ResolveSdks" task failed unexpectedly.
        System.NullReferenceException: Object reference not set to an instance of an object
          at Xamarin.Android.Tasks.ResolveSdks.GetMaxStableApiLevel ()
          at Xamarin.Android.Tasks.ResolveSdks.ValidateApiLevels ()
          at Xamarin.Android.Tasks.ResolveSdks.RunTask ()
          at Xamarin.Android.Tasks.ResolveSdks.Execute ()
          at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute ()

Revert `$(AndroidLatestStableApiLevel)` and
`$(AndroidLatestStableFrameworkVersion)` so that API-27/v8.1 are
built, as those *are* stable.