[Java.Interop] Fix ObjectDisposedException at shutdown.
Objects in the finalization queue may be finalized in any order.

The finalization queue is emptied at process shutdown.

Which brings us to:

	$ make shell
	csharp> var vm = new Java.InteropTests.TestJVM (new string[0]);
	csharp> ^D
	# Ctrl+D; exit the shell
	Unhandled Exception:
	System.ObjectDisposedException: The object was used after being disposed.
	  at Java.Interop.JniType.AssertValid () [0x0002d] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:81
	  at Java.Interop.JniType.UnregisterNativeMethods () [0x00002] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:162
	  at Java.Interop.JniType.Dispose () [0x00086] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:102
	  at Java.Interop.JavaVM.ClearTrackedReferences () [0x0003a] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:345
	  at Java.Interop.JavaVM.Dispose (Boolean disposing) [0x00080] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:219
	  at Java.Interop.JavaVM.Finalize () [0x00003] in /Users/jon/Dropbox/Developer/Java.Interop/src/Java.Interop/Java.Interop/JavaVM.cs:186

We die at shutdown via an ObjectDisposedException because the
finalization queue is unordered, and (in this case) the
JniGlobalReference that a JniType is referring to is being disposed
*before* the JavaVM instance that the JniType was registered with:

	// as if:
	var t = new JniType ("...");
	t.RegisterWithVM ();
	// ...

For the above, it's "as if" t.SafeHandle were being disposed *before*
JavaVM.Current was being disposed.

This shouldn't be possible, as
System.Runtime.ConstrainedExecution.CriticalFinalizerObject instances
should be finalized *after* "normal" finalizable instances, but that's
what's apparently happening here. :-(

Fix JniType.Dispose() to ensure that SafeHandle is both non-null *and*
SafeHandle.IsInvalid==false, and review the source code to ensure that
all other comparisons of SafeHandle to null also check IsInvalid.