[Mono.Android, Xamarin.Android.Tools.JavadocImporter] Fix build
Context: https://github.com/xamarin/java.interop/commit/7d197f17a0f9d73854522d6e1d68deafbcdbcaf6
Context: https://github.com/xamarin/xamarin-android/pull/5452

xamarin/java.interop@7d197f17 introduced build breakage:

	…/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/Crc64.cs(58,16):
	  error CS0117: 'Crc64Helper' does not contain a definition for 'HashCore'
	…/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs(648,27):
	  error CS0117: 'Crc64Helper' does not contain a definition for 'Compute'

PR #5452 has the fix.

Include the build fix so that PR #5253 can build.