[build] all desktop Java code should be build with JDK 1.8
Since , building apps with JDK 1.8 fails with:

    ~/android-toolchain/jdk-1.8/bin/java -jar ./xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/apksigner.jar sign --ks "~/.local/share/Xamarin/Mono for Android/debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugke
        y --key-pass pass:android --min-sdk-version 28 --max-sdk-version 29  ./xamarin/XAPerfTest/bin/Debug/com.xamarin.xaperftest-Signed.apk  (TaskId:206)
        Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer; (TaskId:206)
        at com.android.apksig.internal.util.FileChannelDataSource.copyTo(FileChannelDataSource.java:154) (TaskId:206)
        at com.android.apksig.internal.util.FileChannelDataSource.getByteBuffer(FileChannelDataSource.java:164) (TaskId:206)
        at com.android.apksig.internal.zip.ZipUtils.findZipEndOfCentralDirectoryRecord(ZipUtils.java:181) (TaskId:206)
        at com.android.apksig.internal.zip.ZipUtils.findZipEndOfCentralDirectoryRecord(ZipUtils.java:132) (TaskId:206)
        at com.android.apksig.apk.ApkUtils.findZipSections(ApkUtils.java:55) (TaskId:206)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:215) (TaskId:206)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:193) (TaskId:206)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:340) (TaskId:206)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83) (TaskId:206)

I could reproduce this locally by changing `$(JavaSdkDirectory)` to
point to a JDK 1.8 installation:

    xabuild samples/HelloWorld/HelloWorld.csproj -t:SignAndroidPackage -p:JavaSdkDirectory=~/android-toolchain/jdk-1.8

Even though we are effectively building all desktop Java libraries
with `-source 1.8 -target 1.8`, the produced `.jar` files might
*still* fail at runtime. We need to set `JAVA_HOME` so it points to a
JDK 1.8 instance.

The following command-line tools should be built with JDK 1.8:

* apksigner.jar
* manifestmerger.jar
* proguard.jar
* r8.jar

To do this, I created a new `$(Java8SdkDirectory)` MSBuild property to
be used here. It attempts to locate the `..\jdk-1.8` directory, and
falls back to `$(JavaSdkDirectory)` otherwise (for contributors).