[tests] update BuildReleaseArm64SimpleDotNet.apkdesc (#6689)
Some combination of merging:

* 32cff438
* f61cd81c

We missed an update to this file, as `Mono.Android.dll`'s size
increased beyond the threshold:

    stdErr: Error: apkdiff: File 'assemblies/Mono.Android.dll' has changed by 4,468 bytes (5.10 %). This exceeds the threshold of 5.00 %.
    Error: apkdiff: Size regression occured, 1 check(s) failed.