[xaprepare] Fix for newer homebrew on macOS (#5302)
Context: https://github.com/Homebrew/brew/issues/9033
Context: https://github.com/Homebrew/brew/commit/5adb76a5babdccd2c4edfb8752ac979ed14716ca

Homebrew as of Homebrew/brew@5adb76a5 no longer supports the use of
`brew ls` with the `--versions` and `-1` parameters:

	$ brew ls --versions -1 automake
	Error: Invalid usage: Options --versions and -1 are mutually exclusive.

This change in Homebrew breaks `xaprepare`, as `xaprepare` would
use `brew ls --versions -1` to determine if a program was installed:

	$ make prepare
	…
	Error: Invalid usage: Options --versions and -1 are mutually exclusive.
	 [MISSING]
	Checking automake                                   Usage: brew list, ls [options] [formula|cask]

The intention for our use of `xaprepare` was so that *if* a Homebrew
package had multiple versions installed, the use of
`brew ls --versions -1` would cause *only* the latest version to be
printed, not every version.

As `brew ls --versions -1` is no longer supported, update `xaprepare`
so that `brew ls --versions` output is parsed, preserving only the
first line of output.  This avoids the invalid usage error, while
preserving our desired semantics incase multiple versions are present.