[Java.Interop.Tools.JavaCallableWrappers] TypeNameMapGenerator w/o Types (#311)
Fixes: https://github.com/xamarin/xamarin-android/issues/1431

If we end up with an empty mapping dictionary an exception is thrown:

	System.InvalidOperationException: Sequence contains no elements
	   at System.Linq.Enumerable.Max(IEnumerable`1 source)
	   at Java.Interop.Tools.JavaCallableWrappers.TypeNameMapGenerator.WriteBinaryMapping(Stream o, Dictionary`2 mapping)
	   at Java.Interop.Tools.JavaCallableWrappers.TypeNameMapGenerator.WriteJavaToManaged(Stream output)
	   at Xamarin.Android.Tasks.GenerateJavaStubs.UpdateWhenChanged(String path, Action`1 generator)
	   at Xamarin.Android.Tasks.GenerateJavaStubs.WriteTypeMappings(List`1 types)
	   at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
	   at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
	   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
	   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Update `TypeNameMapGenerator` so it handles an empty list of types.