[create-vsix] Don't package files without an extension (#554)
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=54804

Mono's `System.IO.Packaging.ZipPackage` implementation has a bug in
which adding files without an extension will result in
`[Content_Types].xml` containing a `//Default/@Extension` attribute
with no value.

Unfortunately, our created `Xamarin.Android.Sdk*.vsix` package
contains at least two such files:

* `bin/$(Configuration)/lib/xbuild/Xamarin/Android/Version`
* `bin/$(Configuration)/lib/mandroid/MULTIDEX_JAR_LICENSE`

The result is that, while we have a `.vsix` file, Visual Studio
refuses to install it:

> **Installation Failed**
> The file is not a valid VSIX package.

The install log says:

    System.Xml.XmlException: ‘Default’ tag requires a nonempty ‘Extension’ attribute. Line 1, position 618.

*As a workaround*, do not add any files lacking a file extension to
the `Xamarin.Android.Sdk*.vsix` file.