[monodroid] Allocate directory array with correct type (#3888)
Context: 6d857597187e42d0e7190dfdb61d259e4bac409a
Context: https://github.com/xamarin/xamarin-android/pull/3796
Context: https://github.com/xamarin/xamarin-android/commit/6d857597187e42d0e7190dfdb61d259e4bac409a#diff-e99739c16155208685952aa52870d4cdL33-L39

When switching from C-style `xcalloc()` to C++-style `new` I failed
to use the proper type to allocate the array which holds directories
where Android placed the `.apk` files of the application.  This
mistake manifested itself only when using AppBundles, which is where
we allocate more than one entry of the array.

The resulting error was the following runtime exception:

	Unhandled Exception:
	System.DllNotFoundException: __Internal assembly:<unknown assembly> type:<unknown type> member:(null)
	  at (wrapper managed-to-native) Android.Runtime.JNIEnv.monodroid_timing_start(string)

which occurred because the Xamarin.Android runtime failed to load
`libmonodroid.so` from one of the directories that should have been
stored in the array mentioned above - usually found in the *last*
entry of the array.  When iterating over the array, the XA runtime
would end up with a null pointer after the end of the array instead
of a pointer to the last entry.

This commit uses the proper type when allocating the array.