[WIP] Well... it won't work this way
Unfortunately, neither connecting to the remote server nor interacting
with local lldb is possible.  Even the native `ndk-gdb` script won't
work with the modern Android apps, and faithfully reproducing what it
does also led to:

    (lldb) gdb-remote 5039
    error: Failed to connect port

Next step: examine Android Studio sources and do what they do, since
that works fine.

Luckily, most of the "framework" code written in the previous commit can
be reused.

The goal now is to generate a shell script (both on Unix and Windows) to
actually run lldb, and use msbuild task(s) to prepare the application,
pull binaries, make sure they have symbols etc - most of this code is
already done and won't have to change much.