[Xamarin.Android.Build.Tests] Fix Lint Error in the latest Android tools. (#905)
Recent versions of the Android Lint tool are now reporting:

	obj/Debug/android/src/md5f80e635856c5c6d2b732d9b14f8f2b1f/MainActivity.java(27,13): error XA0103:  Overriding method should call super.onCreate [MissingSuperCall]

because we don't call `super.onCreate()` in our JCW genearted code.
This is by design -- *managed* code will perform an equivalent
`base.OnCreate()` call -- so we need to ignore this particular error.

That said we now have 4 issues we ignore, so rather than keep
duplicating code it has been refactored to use a `string[]`.