[linux] Fix the build, by ignoring ntdll.dll dependency (#2739)
The Linux build [is busted][0][^0]:

	   debian/rules override_dh_clideps
	...
	make[2]: Entering directory '/mnt/jenkins/workspace/xamarin-android-linux-release/xamarin-android/xamarin.android-oss_v9.1.199.151_Linux-x86_64_master_23c30056-Release'
	dh_clideps -X/usr/lib/xamarin.android/xbuild-frameworks/ \
	...
	dh_clideps: Error: Could not resolve moduleref: ntdll.dll for: System.Runtime.InteropServices.RuntimeInformation.dll!	

Add `ntdll.dll` to the `dh_clideps --exclude-moduleref` list to avoid
this error.


[^0]: To be fair, the Linux build has been broken for quite some
      time, mostly due to a [`Mono.Cecil` resolution error][1],
      fixed in 7b9df1f1/[mono/mono/2018-08@98810acb][2]:

          System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies.
          File name: 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
            at Program.Main (System.String[] args) [0x0010e] in <a90a1ae5ea75408fa75e79014ad08562>:0 

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux-release/962/console
[1]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux-release/952/console
[2]: https://github.com/mono/mono/commit/98810acba19aa055cf11ae9c78d2fa5861bb1aed