[Xamarin.Android.Build.Tasks] non-existent @(AndroidResource) files should error
I found a performance problem in a project containing:

    <AndroidResource Include="Resources\layout\noexist.xml" />

What happens in this case, is on every build you get:

    Building target "_CompileResources" completely.
    Input file "Resources\layout\noexist.xml" does not exist.
    Building target "_UpdateAndroidResgen" completely.
    Input file "Resources\layout\noexist.xml" does not exist.

Effectively, even builds with no changes will always run expensive
`aapt` calls...

But we should just emit an error here! That would match more in-line
with what the `<Csc/>` MSBuild task gives for missing C# files.

An example of a non-existent C# file:

    (CoreCompile target) ->
    CSC : error CS2001: Source file 'C:\src\xamarin-android\samples\HelloWorld\noexist.cs' could not be found.

Giving a similar `XA2001` error for `@(AndroidResource)` files will
solve the issue here.