[ci] Use Python 3.11 for signing tasks, platform-tools 34.0.5 (#8367)
Authenticode signing attempts started failing recently with:

	ERROR: 'xsign' is misspelled or not recognized by the system.

Updating to Python 3 is the suggested fix for this issue.

However, Authenticode signing attempts recently started failing
elsewhere due to issues installing the `xsignextension`.  We believe
Python 3.12 may have caused this breakage, so we're pinning to
Python 3.11 for now.

Additionally, update `InstallAndroidDependenciesTest()` to install
platform-tools 34.0.5, as the Google Manifest no longer contains
platform-tools 34.0.4.