[Xamarin.Android.Build.Tasks] #deletebinobj bug with stale jars (#2821)
I updated usage of Xamarin.Forms to the current 3.6 stable, which has
a few benefits:

  * 3.6 includes the patch where Xamarin.Forms is shipping portable
    `.pdb` files now.  This prevents some of the pdb2mdb errors we
    see with our tests running in parallel.
  * 3.6 does not require you to list a bunch of support libraries as
    `@(PackageReference)` for things to build.  The transitive
    dependencies work, and the support library 28.x is pulled in
    automatically.

Unfortunately, I also discovered a bug when doing this...

The `BuildTest.CompileBeforeUpgradingNuGet()` test was hitting a
compiler error:

	CompileToDalvik:
	  ...
	  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnimRes;
	  ...
	  UNEXPECTED TOP-LEVEL EXCEPTION:
	  java.lang.RuntimeException: Translation has been interrupted
	  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:614)
	  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:310)
	  	at com.android.dx.command.dexer.Main.runDx(Main.java:288)
	  	at com.android.dx.command.dexer.Main.main(Main.java:244)
	  	at com.android.dx.command.Main.main(Main.java:95)
	  Caused by: java.lang.InterruptedException: Too many errors
	  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:606)
	  	... 4 more
	  Xamarin.Android.Common.targets(2821,3): java.lang.IllegalArgumentException: already added :  Landroid/support/annotation/AnimRes;

When I looked at the list of jar files, two of them didn't make sense:

	obj\Debug\lp\3\jl\com.android.support.support-annotations.jar
	obj\Debug\lp\3\jl\support-annotations.jar

Xamarin.Android.Support.Annotations 28.x includes an `@(EmbeddedJar)`
named `com.android.support.support-annotations.jar`. In older support
library versions, the file is named `support-annotations.jar`.

Reviewing the `<ResolveLibraryProjectImports/>` MSBuild task, I don't
see what would delete old `@(EmbeddedJar)` files?  For that matter,
`@(AndroidEnvironment)` either?  Reviewing the historical source code
for `<ResolveLibraryProjectImports/>`, it was always this way?

`__AndroidLibraryProjects__.zip` and `__AndroidNativeLibraries__.zip`
should be properly deleting stale files now since the fixes in
98d881b were added.

Changes:

  * At the end of `<ResolveLibraryProjectImports/>`, I added a call
    to enumerate the top directory where `@(AndroidEnvironment)` and
    `@(EmbeddedJar)` files are extracted.
  * I added a call to delete unknown files of these types: making
    sure the hash's timestamp (of the .NET assembly we extracted
    from) is invalidated.
  * I updated the various tests to use Xamarin.Forms 3.6. (which was
    my original goal here!)
  * In `CompileBeforeUpgradingNuGet()` I added an assertion that the
    log message for `support-annotations.jar`s deletion is present.
  * In `BuildAfterUpgradingNuget()` I dropped the option for
    `packages.config`, since it was making it difficult to update
    Xamarin.Forms in these tests.  I added a new
    `BuildTest.BuildBasicApplicationAppCompat()` test to cover
    `packages.config` specifically.  The scenario in
    `BuildAfterUpgradingNuget()` is not really affected by the
    "NuGet package management format".