[Mono.Posix] Mono.Posix.csproj fixes.
Building xamarin-android/master with Mono 4.4.0 [0] would result in a
build error within `src/Mono.Posix`:

	CSC: error CS1703: An assembly `System.Runtime' with the same identity
	has already been imported. Consider removing one of the references.

This was introduced by commit f2fed376, which added `System.Runtime`
as a `@(Reference)` to `Mono.Posix.csproj`.

`Mono.Posix.csproj` `<Import/>`s `Xamarin.Android.CSharp.targets`,
which indirectly adds `System.Runtime`, so there is no need for
`Mono.Posix.csproj` to directly refernce `System.Runtime`.

Additionally, `msbuild` is more stringent regarding property functions
and quoting: this resulted in an MSBuild error:

	Condition="$(AndroidSupportedAbisForConditionalChecks.Contains (:x86:'))">

The fix is to properly quote the `.Contains()` method parameters.

Finally, re-order various elements to increase consistency with other
projects, e.g. `@(Reference)` should go with other `@(Reference)`
entries, `Configuration.props` should be imported as early as
possible, `$(TargetFrameworkVersion)` should be set to
`$(AndroidFrameworkVersion)` (which requires the earlirer
`Configuration.props` import), etc.

[0]: mono-4.4.0-branch-c7-baseline/5995f74