[ci] Migrate macOS test jobs to 10.15 Catalina (#5534)
Context: https://brew.sh/2020/12/01/homebrew-2.6.0/
Context: https://github.com/Homebrew/brew/pull/9054

Homebrew 2.6.0 (released 2020-Dec-01) deprecated support for
macOS 10.13 High Sierra.

All of our test jobs running on a [Microsoft-hosted macOS agent][1]
were on…High Sierra.

The result is that all tests that required Homebrew started failing,
e.g. the **Smoke Tests** > **APK Instrumentation - macOS** job
started failing in the
[**install required brew tools and prepare java.interop** step][2]:

	Installing automake  
	stderr | Warning: You are using macOS 10.13.
	stderr | We (and Apple) do not provide support for this old version.
	stderr | You will encounter build failures with some formulae.
	stderr | Please create pull requests instead of asking for help on Homebrew's GitHub,
	stderr | Twitter or any other official channels. You are responsible for resolving
	stderr | any issues you experience while you are running this
	stderr | old version.
	stderr | 
	stderr | Error: automake: no bottle available!
	stderr | You can try to install from source with:
	stderr |   brew install --build-from-source automake
	stderr | Please note building from source is unsupported. You will encounter build
	stderr | failures with some formulae. If you experience any issues please create pull
	stderr | requests instead of asking for help on Homebrew's GitHub, Twitter or any other
	stderr | official channels.

	  Error: Installation of automake failed

Update the test jobs to instead use the macOS 10.15 Catalina image.
This allows the **Smoke Tests** > **APK Instrumentation - macOS**
job to run successfully.

An initial attempt to use this image saw a few emulator jobs fail with:

	/Users/runner/work/1/s/build-tools/scripts/TestApks.targets(57,5): Emulator failed to start: eglMakeCurrent failed in binding subwindow! [/Users/runner/work/1/s/tests/Mono.Android-Tests/Mono.Android-Tests.csproj]

The `<StartAndroidEmulator/>` task has been updated to ignore this
output as it doesn't appear to be fatal.

Retry attempts have also been added to the `use-dot-net.yaml` template
to try to make dotnet SDK installation attempts more robust.

[1]: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
[2]: https://github.com/xamarin/xamarin-android/blob/1877dd5ebee90452c6ab2cc33a58498a83ea7c1f/build-tools/automation/azure-pipelines.yaml#L409-L410