[Xamarin.Android.Build.Tasks] error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly while building Android App
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/626304

If `ResolveLibraryProjectImports` encounters a corrupt zip or
aar file during the extraction process we get the following
error.

	Xamarin.Tools.Zip.ZipIOException: Unexpected libzip error: EOF
	  at Xamarin.Tools.Zip.ZipArchive.Open (System.String path, System.IO.FileMode mode, System.String defaultExtractionDir, System.Boolean strictConsistencyChecks, Xamarin.Tools.Zip.IPlatformOptions options) [0x00141] in <9421129374314790afd60f8c0021d3d4>:0
	  at Xamarin.Android.Tools.Files.ReadZipFile (System.String filename, System.Boolean strictConsistencyChecks) [0x00000] in <c304dcc9c82e4174bfeded58a523ee7b>:0
	  at Xamarin.Android.Tasks.MonoAndroidHelper.ReadZipFile (System.String filename) [0x00000] in <c304dcc9c82e4174bfeded58a523ee7b>:0
	  at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res, System.Collections.Generic.ICollection`1[T] jars, System.Collections.Generic.ICollection`1[T] resolvedResourceDirectories, System.Collections.Generic.ICollection`1[T] resolvedAssetDirectories, System.Collections.Generic.ICollection`1[T] resolvedEnvironments) [0x00521] in <c304dcc9c82e4174bfeded58a523ee7b>:0
	  at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute () [0x000fc] in <c304dcc9c82e4174bfeded58a523ee7b>:0
	  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /_/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:631
	  at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x00212] in /_/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:787  (MSB4018)

Which is not helpful at all. This commit introduces a new error
`xa1004` which at leasts reports the file that had the problem.
It also recommends that the user remove the offending file and
try a `ReBuild`.