Bump to xamarin/Java.Interop/master@60e85b04 (#3504)
Changes: https://github.com/xamarin/java.interop/compare/be581591d0a995c740600be3ceefd0c3351dd0dd...60e85b0424c1cf706ac8c5f1e6ff6e84d38cf3b5

Context: https://github.com/xamarin/java.interop/pull/459

Updates `generator` so that all bound Java interfaces also implement
`IJavaPeerable` in addition to `IJavaObject`, for eventual future
C#8 Default Interface Member support.

[generator] Remove extraneous slash when creating `.projitems`.

[generator] Always use `XAPeerMembers` for `XAJavaInterop1`

Drop dependency on DylibMono when building for Xamarin.Android (#3223)

[jnienv-gen] fix p/invoke usage for .NET framework

Add `jnimarshalmethod-gen.exe -r ASSEMBLY` option.

Improve support for binding package-private interfaces.

Parse `EnclosingMethod`, `SourceFile` attribute blobs.

Emit events for `addListener(Listener,Handler)` pattern.

Fix `jnimarshalmethod-gen.exe`-related build error introduced by
having bound interfaces implement `IJavaPeerable`:

	Instance property 'PeerReference' is not defined for type 'Android.Widget.IListAdapter'
	Parameter name: propertyName
	System.ArgumentException: Instance property 'PeerReference' is not defined for type 'Android.Widget.IListAdapter'
	Parameter name: propertyName
	    at System.Linq.Expressions.Expression.Property (System.Linq.Expressions.Expression expression, System.String propertyName)
	    at Java.Interop.JavaPeerableValueMarshaler.CreateIntermediaryExpressionFromManagedExpression (Java.Interop.Expressions.JniValueMarshalerContext context, System.Linq.Expressions.ParameterExpression sourceValue)
	    at Java.Interop.JavaPeerableValueMarshaler.CreateReturnValueFromManagedExpression (Java.Interop.Expressions.JniValueMarshalerContext context, System.Linq.Expressions.ParameterExpression sourceValue)

Added `external/Java.Interop/build-tools/jnienv-gen.csproj` to
`Xamarin.Android.sln` so that it builds properly.