Bump to dotnet/installer/main@fa261b952d 9.0.100-preview.5.24253.16 (#8921)
Changes: https://github.com/dotnet/installer/compare/d301a122c4...fa261b952d
Changes: https://github.com/dotnet/runtime/compare/d92ac1f892...4326eb7ed4
Changes: https://github.com/dotnet/emsdk/compare/19c9523f5c...53288f87c5
Changes: https://github.com/dotnet/cecil/compare/861f49c137...4abe3e63a5

Updates:

* Microsoft.Dotnet.Sdk.Internal: from 9.0.100-preview.5.24229.2 to 9.0.100-preview.5.24253.16
* Microsoft.NETCore.App.Ref: from 9.0.0-preview.4.24223.11 to 9.0.0-preview.4.24251.3
* Microsoft.NET.Workload.Emscripten.Current.Manifest-9.0.100.Transport: from 9.0.0-preview.4.24215.3 to 9.0.0-preview.5.24223.2
* Microsoft.NET.ILLink.Tasks: from 9.0.0-preview.4.24223.11 to 9.0.0-preview.4.24251.3
* Microsoft.DotNet.Cecil: from 0.11.4-alpha.24215.1 to 0.11.4-alpha.24222.1

Other changes:

* [Mono.Android] fix trimmer warning in `JNIEnvInit`

    src/Mono.Android/Android.Runtime/JNIEnvInit.cs(58,15): error IL2057: Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String)'. It's not possible to guarantee the availability of the target type.

Add appropriate attributes on a local method to silence the warning.

Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>