[Mono.Android] Properly marshal generic lists of primitive arrays (#4788)
Fixes: https://github.com/xamarin/xamarin-android/issues/4098

Consider the following Java method:

	// Java
	public static int count (List<int[]> values) {
	    int c = 0;
	    for (int[] v : values) {
	        c += v.length;
	    }
	    return c;
	}

This is bound as:

	// C#
	[Register ("count", "(Ljava/util/List;)I", "")]
	public static unsafe int Count (IList<int[]> p0)
	{
	    const string __id = "count.(Ljava/util/List;)I";
	    IntPtr native_p0 = global::Android.Runtime.JavaList<int[]>.ToLocalJniHandle (p0);
	    try {
	        JniArgumentValue* __args = stackalloc JniArgumentValue [1];
	        __args [0] = new JniArgumentValue (native_p0);
	        var __rm = _members.StaticMethods.InvokeInt32Method (__id, __args);
	        return __rm;
	    } finally {
	        JNIEnv.DeleteLocalRef (native_p0);
	    }
	}

The problem is that when the `InvokeInt32Method()` statement is hit,
*Java* throws an exception:

	mono.android.runtime.JavaObject cannot be cast to int[]

The cause of the problem is that while `JavaList<T>.ToLocalJniHandle()`
created a `java.util.ArrayList` instance, the *contents* of the created
`ArrayList` were `JavaObject` instances, *not* `int[]` instances.
Thus, when the Java code attempts to cast an element from the list to
`int[]`, the cast fails.

The underlying problem is that e.g.
`JavaConvert.WithLocalJniHandle<TValue, TReturn>(…)` didn't handle
array types, so if `TValue` were an array, the array would be wrapped
into a `JavaObject` instance, instead of being "deep marshaled" to a
Java-side array.

Add support for array marshaling to `JavaConvert`, so that
`JavaLists<int[]>.ToLocalJniHandle()` properly creates a Java-side
`ArrayList` which contains `int[]` values.  This fixes the cast.

Note that I looked at also adding cases for Kotlin's unsigned primitive
arrays, however Kotlin only allows their use in very limited
circumstances, and `List<uint[]>` is not allowed:

	// Kotlin
	UnsignedMethods.kt:39:61: error: expecting a '>'
	    public open fun uintListInstanceMethod (value: List<UInt[]>) : List<UInt[]> { return value; }
	                                                            ^