[Xamarin.Android.Build.Tasks] Fix bug in the Design Time Build (#9711)
We got a bug report that a .NET 10 design-time build in VS results in
the following error:

    System.ArgumentOutOfRangeException: Positive number required.
    Parameter name: bufferSize
       at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
       at Xamarin.Android.Tasks.GenerateResourceCaseMap.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceCaseMap.cs:line 94
       at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25

We were passing `-1` as the `bufferSize`. While this is fine under .NET 9/10.
It seems the full .NET framework does not like it.

So, lets fix it by passing `4096`.