Support build-tools 33.0.0.
Need to make use of `mainDexClasses.rules` conditional, as it
does not exist in build-tools 33.0.0, resulting in:

    java.lang.RuntimeException: com.android.tools.r8.internal.f: Failed to read file: C:\Android\android-sdk\build-tools\33.0.0\mainDexClasses.rules