[Xamarin.Android.Build.Tasks] Fix LayoutBinding under AndroidX (#6894)
Fixes: https://github.com/xamarin/xamarin-android/issues/6893

Context: 92cd68c7beb3a26dab55957b2e061faf6cdc1d89
Context: https://github.com/xamarin/AndroidX/blob/628cf049e0ef61e140cb17600df16ed801449814/source/AndroidXTargets.cshtml#L36

When:

 1. The [`$(AndroidFragmentType)`][0] MSBuild property is set, *and*
 2. The [`$(AndroidGenerateLayoutBindings)`][1]=True, *and*
 3. There is a Layout XML file which has an `id`, *and*
 4. Define `__HAVE_ANDROIDX__` C# symbol.

then [`LayoutBinding.cs`][2] (92cd68c7) fails to compile.

Repro:

 1. `dotnet new android`
 2. Edit `Resources/layout/activity_main.xml` so that the
    `<TextView/>` has `android:id="@+id/text_view"`:

        <TextView
          android:id="@+id/text_view"
          android:layout_width="wrap_content"                                     
          android:layout_height="wrap_content"                                    
          android:layout_centerInParent="true"                                    
          android:text="@string/app_text"                                         
        />

 3. Build!

        dotnet build -p:AndroidFragmentType=AndroidX.Fragment.App.Fragment \
          -p:AndroidGenerateLayoutBindings=True \
          -p:DefineConstants=__HAVE_ANDROIDX__

Expected results: no errors.

Actual results:

	…/LayoutBinding.cs(91,56): error CS0400: The type or namespace name 'Androidx' could not be found in the global namespace
	…/LayoutBinding.cs(91,135): error CS0400: The type or namespace name 'Androidx' could not be found in the global namespace

Update `LayoutBinding.cs` so that it uses the correct `AndroidX`
namespace.  Additionally, `FragmentManager` has been deprecated;
update `LayoutBinding.cs` to use `SupportFragmentManager`, which is
available on the `AndroidX.Fragment.App.FragmentActivity` class.

Finally, remove the use of a `static` field to share object state between
tasks. We have been on `msbuild` rather than `xbuild` on *nix for a while
now, so this workaround is no longer needed.

TODO: Add [`LayoutCodeBehind.md` docs][3] to
[MicrosoftDocs/xamarin-docs][4].

[0]: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-items#androidfragmenttype
[1]: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-properties#androidgeneratelayoutbindings
[2]: https://github.com/xamarin/xamarin-android/blob/16bbf6f0b0cd49f96f73197d28e8faf31aa9e499/src/Xamarin.Android.Build.Tasks/Resources/LayoutBinding.cs
[3]: https://github.com/xamarin/xamarin-android/blob/16bbf6f0b0cd49f96f73197d28e8faf31aa9e499/Documentation/guides/LayoutCodeBehind.md
[4]: https://github.com/MicrosoftDocs/xamarin-docs/tree/live/docs/android/deploy-test/building-apps