[Xamarin.Android.Cecil] More chained MSBuild fixes
Proving once again that I'm cursed -- or that I don't have consistent
development environments, take your pick -- the fix attempted in 
commit 27c3e331 didn't work as expected, with a (patched)
`msbuild`-using invocation from `xamarin-android` failing with a
truly bizarre path:

    # in `xamarin-android`
    $ make MSBUILD=msbuild V=1
    ...
    CSC : error CS0006: Metadata file `@D@/bin/Debug/Xamarin.Android.Cecil.dll' could not be found

where `@D@` was `path/to/xamarin-android/../..`, i.e. a directory
that would never contain `Xamarin.Android.Cecil.dll`.

(Not sure why 27c3e331 appeared to work before, but that was a
different machine, which is why I'm cursed.)

Update `$(OutputPath)` within
`src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.targets` so that it
uses `$(MSBuildThisFileDirectory)` to get a consistent directory.

That *appears* to allow xamarin-android compilation to continue
when building with `msbuild`.