[build] all desktop Java code should be build with JDK 1.8 (#5063)
Ever since c50df1c5, building apps with JDK 1.8 fails with:

	~/android-toolchain/jdk-1.8/bin/java -jar ./xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/apksigner.jar sign --ks "~/.local/share/Xamarin/Mono for Android/debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugkey --key-pass pass:android --min-sdk-version 28 --max-sdk-version 29  ./xamarin/XAPerfTest/bin/Debug/com.xamarin.xaperftest-Signed.apk
	    Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
	    at com.android.apksig.internal.util.FileChannelDataSource.copyTo(FileChannelDataSource.java:154)
	    at com.android.apksig.internal.util.FileChannelDataSource.getByteBuffer(FileChannelDataSource.java:164)
	    at com.android.apksig.internal.zip.ZipUtils.findZipEndOfCentralDirectoryRecord(ZipUtils.java:181)
	    at com.android.apksig.internal.zip.ZipUtils.findZipEndOfCentralDirectoryRecord(ZipUtils.java:132)
	    at com.android.apksig.apk.ApkUtils.findZipSections(ApkUtils.java:55)
	    at com.android.apksig.ApkSigner.sign(ApkSigner.java:215)
	    at com.android.apksig.ApkSigner.sign(ApkSigner.java:193)
	    at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:340)
	    at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)

I could reproduce this locally by changing `$(JavaSdkDirectory)` to
point to a JDK 1.8 installation:

	xabuild samples/HelloWorld/HelloWorld.csproj -t:SignAndroidPackage -p:JavaSdkDirectory=~/android-toolchain/jdk-1.8

Even though we are effectively building all desktop Java libraries
with `-source 1.8 -target 1.8`, the produced `.jar` files might
*still* fail at runtime, because `javac -source 1.8 -target 1.8` only
control the generated Java bytecode, but *not* the "API contract" that
the code is built against.

There isn't a way to use the "Java 8" API contract with the "Java 11"
toolchain; there is no Java equivalent to .NET "Reference Assemblies".

Consequently, if we want to *ensure* that only Java 8 types & methods
are used, we must *build* using the JDK 8 toolchain.

Update the following Java library projects so that they build under
JDK 1.8, by exporting `JAVA_HOME` to use our JDK 1.8 install:

  * `apksigner.jar`
  * `manifestmerger.jar`
  * `proguard.jar`
  * `r8.jar`

To do this, I created a new `$(Java8SdkDirectory)` MSBuild property to
be used here.  It attempts to locate the `..\jdk-1.8` directory, and
falls back to `$(JavaSdkDirectory)` otherwise (for contributors).