Fix `File.Move` with dangling symlinks
Current versions of Mono 6 have a bug which makes them throw an `IOException`
whenever an attempt is made to move a file that is a dangling symlink, on Unix
operating systems:

    Mono archive already downloaded and valid
    Archive path: android-archives/android-debug-Darwin-ddef564e344e1e287d6e7755d633d54aa6344985.7z
    [7zip] extracting archive
    [7zip] log file: bin/BuildDebug/prepare-20190610T143559.7zip-extract.android-debug-Darwin-ddef564e344e1e287d6e7755d633d54aa6344985.7z.log
    Elapsed: 00:00:41.0868232

    Step Xamarin.Android.Prepare.Step_BuildMonoRuntimes failed: Could not find file 'external/mono/sdks/out.tmp/android-host-mxe-Win32-debug/bin/mono'.
    System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_BuildMonoRuntimes failed: Could not find file 'external/mono/sdks/out.tmp/android-host-mxe-Win32-debug/bin/mono'. ---> System.IO.FileNotFoundException: Could not find file 'external/mono/sdks/out.tmp/android-host-mxe-Win32-debug/bin/mono'.
      at Xamarin.Android.Prepare.Utilities.MoveFileWithRetry (System.String source, System.String destination, System.Boolean resetFileTimestamp) [0x000c1] in build-tools/xaprepare/xaprepare/Application/Utilities.cs:538
      at Xamarin.Android.Prepare.Utilities.MoveDirectory (System.String sourceDir, System.String destinationDir, System.Boolean resetFileTimestamp) [0x000be] in build-tools/xaprepare/xaprepare/Application/Utilities.cs:475
      at Xamarin.Android.Prepare.Utilities.MoveDirectory (System.String sourceDir, System.String destinationDir, System.Boolean resetFileTimestamp) [0x00098] in build-tools/xaprepare/xaprepare/Application/Utilities.cs:468
      at Xamarin.Android.Prepare.Utilities.MoveDirectory (System.String sourceDir, System.String destinationDir, System.Boolean resetFileTimestamp) [0x00098] in build-tools/xaprepare/xaprepare/Application/Utilities.cs:468
      at Xamarin.Android.Prepare.Utilities.MoveDirectoryContentsRecursively (System.String sourceDir, System.String destinationDir, System.Boolean cleanDestinationDir, System.Boolean resetFileTimestamp) [0x000dc] in build-tools/xaprepare/xaprepare/Application/Utilities.cs:451

Since we cannot, at this time, fix the problem in the Mono BCL, we need to work
around it. Thus, this commit implements a way to check whether a file is a
dangling symlink before calling `File.Move`. If the file **is** a dangling
symlink, it is not copied using `link(2)` (the cause of the Mono bug) but,
rather, it is recreated at the destination location using the contents of the
source symlink acquired using `readlink(2)`.