Bump to xamarin/Java.Interop/main@cbd96668 (#6737)
Changes: https://github.com/xamarin/Java.Interop/compare/7dc270dbb83948b278bee38fc83bf9ae5cd42a7e...cbd966686e2a3179cf3e6285990302c6b7afab21

  * xamarin/Java.Interop@cbd96668: [Java.Interop] $(Version) depends on TargetFramework (#952)
  * xamarin/Java.Interop@e587cf6b: [build] Remove the `make prepare-core` targets (#951)
  * xamarin/Java.Interop@e02d8572: [build] Remove globalPackagesFolder override (#948)

Of particular note is xamarin/Java.Interop@cbd96668, which changes
the version of `Java.Interop.dll` in the net6.0 profile from 0.1.0.0
to 6.0.0.0, and the version of "utility libs" like
`Xamarin.SourceWriter.dll` from being identical to their non-net6.0
counterparts, to instead having `6.0.0.*` version numbers.
This change in turn necessitates:

  * Updating `build-tools/create-packs` and `build-tools/installers`
    so that the "utility libs" are grabbed from their appropriate
    build directory, so that we don't distribute e.g. "legacy"
    `Xamarin.SourceWriter, Version=0.2.0.0` in the .net 6 package.

  * Updating `tests/**/*.csproj` to specify a "full"
    `$(TargetFramework)`=net6.0-android32 instead of
    `$(TargetFramework)`=net6.0-android.  If we don't use the "full"
    version, we'll use the net6.0-android31.0 targeting pack, which
    has the wrong version for `Java.Interop.dll`, possibly resulting
    in compilation errors:

        error CS0433: The type 'JavaObject' exists in both
	'Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' and
	'Java.Interop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

xamarin/Java.Interop@e587cf6b simplified the Java.Interop build
system, necessitating changes to `build-tools/xaprepare` --
`make prepare-core` is no longer needed -- but also required adding
`Java.Runtime.Environment.csproj` to `Xamarin.Android.sln`, so that
it's build-time Target could properly create
`Java.Runtime.Environment.dll.config`.

TODO: Better deal with the `Java.Interop.dll` version change that is
now part of `net6.0-android32.0`.  We should consider "removing" the
`net6.0-android31.0` targeting pack, and make `net6.0-android` be an
alias for `net6.0-android32.0`.