[bundle] Bundle Consts.cs (#207)
Commit 29568117 inadvertently stopped bundling `include/Consts.cs`,
which is causing a [build break][0]:

	CSC: error CS2001: Source file
	`../../bin/Debug/lib/xbuild-frameworks/MonoAndroid/v1.0/../../../../include/Consts.cs'
	could not be found

Fix the `GetMonoBundleItems` target to include `Consts.cs`, and bump
the bundle version within `GetBundleFileName` so that a new bundle is
created and uploaded.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/78/