[Xamarin.Android.Build.Tasks] error XA1004, not MSB4018 (#2251)
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/626304

When `<ResolveLibraryProjectImports/>` encounters a corrupt `.zip` or
`.aar` file during the extraction process we get the following error:

	Xamarin.Tools.Zip.ZipIOException: Unexpected libzip error: EOF
	  at Xamarin.Tools.Zip.ZipArchive.Open (System.String path, System.IO.FileMode mode, System.String defaultExtractionDir, System.Boolean strictConsistencyChecks, Xamarin.Tools.Zip.IPlatformOptions options)
	  at Xamarin.Android.Tools.Files.ReadZipFile (System.String filename, System.Boolean strictConsistencyChecks)
	  at Xamarin.Android.Tasks.MonoAndroidHelper.ReadZipFile (System.String filename)
	  at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res, System.Collections.Generic.ICollection`1[T] jars, System.Collections.Generic.ICollection`1[T] resolvedResourceDirectories, System.Collections.Generic.ICollection`1[T] resolvedAssetDirectories, System.Collections.Generic.ICollection`1[T] resolvedEnvironments)
	  at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute ()
	  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute ()
	  at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext ()

Which is not helpful at all.

This commit introduces a new error `XA1004` which at leasts reports
the file that had the problem.  It also recommends that the user
remove the offending file and try a `ReBuild`.