[Xamarin.Android.Build.Tasks] Support cmdline-tools
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3778167&view=ms.vss-test-web.build-test-results-tab&runId=13587054&resultId=100129&paneView=debug
Context: fa8ac9e33561db7a9a4ff214dba45b3ff5fc8324

`lint` was moved to the `cmdline-tools` package, and in the process
the value returned by `lint --version` was *lowered* (?!):

	% ~/android-toolchain/sdk/tools/bin/lint --version
	lint: version 26.1.1
	% ~/android-toolchain/sdk/cmdline-tools/1.0/bin/lint --version
	lint: version 3.6.0

3.6.0 is less than 26.1.1, and thus `lint --disable` values which need
to be used *aren't* used, which results in `lint` errors:

	MainActivity.java(27,13): error XA0103:  Overriding method should call super.onCreate [MissingSuperCall]

In the interest of expediency, assume that we're using the
cmdline-tools package if `ToolPath` contains `cmdline-tools`, in which
case we treat `lint` as newer than any previous version.

(This may be less than ideal.)