[Xamarin.Android.Build.Tasks] Fix aapt_rules.txt corruption
Fixes #7447

Users are reporting a error with the aapt_rules file generated by aapt2
```
MSBUILD : java.exe error JAVA0000: Error in obj\Release\110\aapt_rules.txt at line 289, column 1: [C:\Jenkins\workspace\Demo\Demo.Android\Demo.Android.csproj]
MSBUILD : java.exe error JAVA0000: Expected char '-' at obj\Release\110\aapt_rules.txt:289:1 [C:\Jenkins\workspace\Demo\Demo.Android\Demo.Android.csproj]
MSBUILD : java.exe error JAVA0000: nit>(...); } [C:\Jenkins\workspace\Demo\Demo.Android\Demo.Android.csproj]
MSBUILD : java.exe error JAVA0000: Compilation failed
```

This only happens when building with `AndroidCreatePackagePerAbi` set
to `true`. After looking at the code, it turns out that we call
`aapt2 link` multiple times when building per abi. The temp file used
for the `aapt2 link` proguard output was the same file for ALL of the
calls. This results in one call to aapt2 overwriting the previous ones
results... or worse leaving garbage at the end.

So the fix in this case is to provide a different temp file for each
call to `aapt2`. These files are then combined later just in case they
contain unique information for that abi. While this does result in
duplicate lines in the `aapt_rules` file, this does not impact on the
build.