Bump to xamarin/Java.Interop/master@cdf840f7
Changes: https://github.com/xamarin/Java.Interop/compare/4f47ec82c14ae6ca23c1dcde3f7b5c8b93b6a4f7...cdf840f7f746b691db930aa2631fd410aaef215d

Context: https://github.com/xamarin/xamarin-android/pull/4219

  * xamarin/Java.Interop@cdf840f: [Java.Interop] Remove `obj/*` from @(Compile) for x-a (#585)
  * xamarin/Java.Interop@95712a2: [Java.Interop] Alter $(BaseIntermediateOutputPath) for x-a (#584)

The bump to mono/mono/2020-02@86f2aad3 brought in an [msbuild bump][0]
which included a "semantic change" around *where* the generated
`*.AssemblyAttributes.cs` were placed: previously, they were placed
into `$TMP`, but with microsoft/msbuild@67991ede they were instead
placed into `$(IntermediateOutputPath)`.  This change "broke" the
Java.Interop build, as both `Java.Interop.csproj` and
`Java.Interop-MonoAndroid.csproj` place files into
`external/Java.Interop/src/Java.Interop/obj*` directories, causing the
"other" build to use those files, resulting in duplicate attributes:

	obj/Release/netstandard2.0/.NETStandard,Version=v2.0.AssemblyAttributes.cs(4,12):
	error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute

Commits xamarin/Java.Interop@cdf840f7 and xamarin/Java.Interop@95712a2
address this problem, allowing PR #4219 to continue.

[0]: https://github.com/mono/mono/commit/de188682978ae830a04878d897d8a8faa3d0d546
[1]: https://github.com/microsoft/msbuild/commit/67991edee76d433b744ceb593f554e2bbeb6b9a0