Remove brew/openssl workaround (#5434)
The homebrew/openssl related workaround/fix started failing recently with:

    Error: No available formula or cask with the name "openssl@1.0.2t".

When running:

    brew uninstall openssl@1.0.2t && rm -rf /usr/local/etc/openssl && rm -rf /usr/local/etc/openssl@1.1

@pjcollins thinks the original issue was fixed meanwhile, so we can remove it,
instead of fixing it by forcing the uninstall.