[Mono.Android] fix a set of the "easiest" trimmer warnings (#8731)
Context: https://github.com/xamarin/xamarin-android/issues/5652

Fixing the following trimmer warnings:

~~ TypeConverter ~~

Context: https://source.dot.net/#System.ComponentModel.TypeConverter/System/ComponentModel/TypeConverter.cs,226

	src\Mono.Android\System.Drawing\SizeFConverter.cs(121,49): error IL2046:
	  Base member 'System.ComponentModel.TypeConverter.GetProperties(ITypeDescriptorContext, Object, Attribute[])' with 'RequiresUnreferencedCodeAttribute' has a derived member
	  'System.Drawing.SizeFConverter.GetProperties(ITypeDescriptorContext, Object, Attribute[])' without 'RequiresUnreferencedCodeAttribute'.
	  'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.

Various `TypeConverter` implementations need to specify
`[RequiresUnreferencedCode]` to match the base type.


~~ ColorValueMarshaler & IJavaObjectValueMarshaler ~~

Context: https://github.com/xamarin/java.interop/commit/7d1e7057cf4b0adcf65e7064186326dafce11b72

From the trimmer warnings solved in `Java.Interop.dll`, we need to
bring these changes forward to any `*Marshaler` types.


~~ AndroidClientHandler ~~

	'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.NonPublicFields' in call to 'System.Type.GetField(String, BindingFlags)'.
	The return value of method 'System.Collections.IEnumerator.Current.get' does not have matching annotations.
	The source value must declare at least the same requirements as those declared on the target location it is assigned to.

This class had a loop that was not trimming safe:

	for (var type = GetType (); type != null; type = type.BaseType) {
	    field = type.GetField (fieldName, BindingFlags.Instance | BindingFlags.NonPublic);
	    if (field != null)
	        break;
	}

If we *look* at the actual base types of `AndroidClientHandler`, we
can simplify this loop to something that *is* trimming safe:

	const BindingFlags flags = BindingFlags.Instance | BindingFlags.NonPublic;
	FieldInfo? field = typeof (HttpClientHandler).GetField (fieldName, flags) ??
	    typeof (HttpMessageHandler).GetField (fieldName, flags);

There should be no need to iterate *beyond* `HttpMessageHandler`, the
code is looking for this field:

  * https://github.com/dotnet/runtime/blob/135fec006e727a31763271984cd712f1659ccbd3/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.AnyMobile.cs#L25

As `AndroidClientHandler` is `[Obsolete]` and unlikely to have its
inheritance hierarchy changed, removing the loop is deemed safe.