Revert "[Mono.Android] Add implicit int -> Color operator (#4120)" (#4315)
There was an unforeseen complication in commit 1d5ed48:
circular conversions.  Before 1d5ed48, `Android.Graphics.Color` had
an implicit conversion from `Color` to `int`.  Commit 1d5ed48 added
an implicit conversion from `int` to `Color`.  Thus:

	partial struct Color {
	    public static implicit operator Color (int value);
	    public static implicit operator int (Color value);
	}

This *seems* fine, but is problematic within ternary expressions:

	Color c1 = ...
	int   c2 = ...;
	var   c  = condition ? c1 : c2;

This results in a [CS0172 error][0]:

	error CS0172: Type of conditional expression cannot be determined because 'Color' and 'int' implicitly convert to one another	

In short, adding an implicit conversion from `int` to `Color` results
in a source compatibility break.

[Xamarin.Forms ran into this breakage][1]:

	SetScrimColor(isShowingSplit ? Color.Transparent.ToAndroid() : (int)DefaultScrimColor);

There are two potential fixes:

 1. Make the implicit `int`-to-`Color` operator *`explicit`*, or
 2. Remove the added operator entirely.

At this point in time, we see little benefit to making the operator
`explicit`, so we have opted to remove the operator by reverting
commit 1d5ed48.

[0]: https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0172
[1]: https://github.com/xamarin/Xamarin.Forms/blob/7a52542d50797ccc69ae1d8dd84259190d96bdb4/Xamarin.Forms.Platform.Android/Renderers/MasterDetailRenderer.cs#L425