Partially revert 8e92871429d
This change causes build failures, it should not be needed:

    "src\Mono.Android\Mono.Android.csproj" (default target) (24:2) ->
    (CoreCompile target) ->
        Android.Runtime\JNIEnv.g.cs(120,141): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(138,138): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(156,138): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(174,139): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(192,137): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(210,138): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(246,140): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(264,131): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(282,183): error CS1503: Argument 4: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(300,184): error CS1503: Argument 4: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(318,181): error CS1503: Argument 4: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(336,181): error CS1503: Argument 4: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(354,182): error CS1503: Argument 4: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(372,180): error CS1503: Argument 4: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(390,181): error CS1503: Argument 4: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(408,182): error CS1503: Argument 4: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(426,183): error CS1503: Argument 4: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(444,174): error CS1503: Argument 4: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(580,143): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(616,140): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(634,141): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(652,139): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(670,140): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(688,141): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(706,142): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'
        Android.Runtime\JNIEnv.g.cs(724,133): error CS1503: Argument 3: cannot convert from 'System.IntPtr' to 'Java.Interop.JniArgumentValue*'