[Mono.Android] prefix `Microsoft.Android.Runtime` namespace with `_`
We introduced a new `internal` type in `Mono.Android.dll`:

    namespace Microsoft.Android.Runtime;

    class ManagedValueManager : JniRuntime.JniValueManager

Causes various C# compiler errors in dotnet/maui:

    D:\src\maui\src\Essentials\src\AppActions\AppActions.shared.cs(62,28):
    error CS0234: The type or namespace name 'Content' does not exist in the namespace 'Microsoft.Android' (are you missing an assembly reference?)

To fix this, we can prefix the namespace with `_`. We basically can
never use a `Microsoft.Android.*` namespace in `Mono.Android.dll`.