Add `[RequiresDynamicCode]`
Fixes the build error(s):

    src/Mono.Android/Android.Runtime/IJavaObjectValueMarshaler.cs(40,11): error IL3050:
    Using member 'System.Linq.Expressions.Expression.Call(Type, String, Type[], params Expression[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Calling a generic method requires dynamic code generation. This can be suppressed if the method is not generic.
    src/Mono.Android/Android.Runtime/IJavaObjectValueMarshaler.cs(54,7): error IL3050:
    Using member 'System.Linq.Expressions.Expression.Call(Type, String, Type[], params Expression[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Calling a generic method requires dynamic code generation. This can be suppressed if the method is not generic.