[tests] Preserve Java.Interop-Tests types!
See also the "Preserve required types" commit.
`Mono.Android_TestMultiDex` and `Mono.Android_TestsAppBundle` are
failing because they can't resolve some Java types:

	Java.Lang.ClassNotFoundException : com.xamarin.interop.CallVirtualFromConstructorDerived
	  at Java.Interop.JniEnvironment+Types.FindClass (System.String classname)
	  at Java.Interop.JniType..ctor (System.String classname)
	  at Java.Interop.JniType.GetCachedJniType (Java.Interop.JniType& cachedType, System.String classname)
	  at Java.Interop.JniPeerMembers.get_JniPeerType ()
	  at Java.Interop.JniPeerMembers+JniStaticMethods.GetMethodInfo (System.String encodedMember)
	  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters)
	  at Java.InteropTests.CallVirtualFromConstructorDerived.NewInstance (System.Int32 value)
	  at Java.InteropTests.InvokeVirtualFromConstructorTests.ActivationConstructor ()
	  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
	  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
	  --- End of managed Java.Lang.ClassNotFoundException stack trace ---
	java.lang.ClassNotFoundException: com.xamarin.interop.CallVirtualFromConstructorDerived
		at crc64f295cabbf85394f5.TestSuiteInstrumentation.n_onStart(Native Method)
		at crc64f295cabbf85394f5.TestSuiteInstrumentation.onStart(Unknown Source:0)
		at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

Add a `@(ProguardConfiguration)` entry to the appropriate projects so
that these required types are preserved.