[Mono.Android] Remove enum mapping for DisplayMetrics.DENSITY_DEVICE_STABLE
Commit 50c0c15f [broke][0] the [build][1]:

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/784/consoleText
[1]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/784/

	obj/Release/android-27/mcw/Android.Util.DisplayMetricsDensity.cs(22,20): error CS0150: A constant value is expected

Remove the enum mapping for DisplayMetrics.DENSITY_DEVICE_STABLE so
that the build is no longer broken.