[xabt] additional fixes for non-integer API levels
We found the following errors with many `javac` errors:

    class MyTextObjectFont : Android.Graphics.Pdf.Component.PdfPageTextObjectFont
    {
        public MyTextObjectFont(Android.Graphics.Pdf.Component.PdfPageTextObjectFont font) : base(font)
        {
        }
    }

Such as:

    obj\Debug\net10.0-android36.1\android\src\crc643b87557a63e7c027\MainActivity_MyTextObjectFont.java(5,40): error JAVAC0000:  error: package android.graphics.pdf.component does not exist
        extends android.graphics.pdf.component.PdfPageTextObjectFont

This appears to be caused by the use of:

    "C:\Program Files (x86)\Android\android-sdk\platforms\android-36\android.jar"

When the build *should* be using:

    "C:\Program Files (x86)\Android\android-sdk\platforms\android-36.1\android.jar"

Update various MSBuild logic to handle non-integer API levels.

Co-authored-by: Jonathan Pryor <jonpryor@vt.edu>