[Mono.Android] Unbind Cursor.getNotificationUris() (#5161)
Fixes: https://github.com/xamarin/xamarin-android/issues/5027
Context: https://github.com/xamarin/java.interop/issues/699
Context: https://github.com/xamarin/java.interop/issues/699#issuecomment-699462809
Context: eadd3bda8e2a81c6ca997f05d3faac7040b29a7b

The [`Cursor.getNotificationUris()`][0] interface default method was
added in API-29.

Much as with `Cursor.setNotificationUris()` and commit eadd3bda, this
introduces an issue when implementing `Android.Database.ICursor`
in API-30+: when binding a Java class that implements `Cursor`:

	// Java
	public class MyCursor implements android.database.Cursor {
	    // …
	}

In the binding `generator` emits for `MyCursor`, the Java-to-managed
marshal method to support `Cursor.getNotificationUris()` does not
compile, as it tries to use a generic type -- `IList<T>` -- without
providing any generic type parameters:

	// C# binding
	public partial class MyCursor : Java.Lang.Object, ICursor {
	    static IntPtr n_GetNotificationUris (IntPtr jnienv, IntPtr native__this)
	    {
	        var __this  = Java.Lang.Object.GetObject<MyCursor> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
	        return global::Android.Runtime.JavaList.ToLocalJniHandle (__this.NotificationUris);;
	        // ^^ error CS1503: Argument 1: cannot convert from 'System.Collections.Generic.IList<Android.Net.Uri>' to 'System.Collections.IList?'
	    }
	}

We had thought that xamarin/java.interop@262743b47 addressed this
issue, but we were mistaken.

The `generator` fix for this scenario seems tricky, so as a workaround
for now we can simply remove the `Cursor.getNotificationUris()` default
method so users can implement the interface.

(Although the method was added in API-29, we don't support
Default Interface Members in API-29, so it was ignored.  Thus, this
problem doesn't show up until API-30+ is used.)

[0]: https://developer.android.com/reference/android/database/Cursor#getNotificationUris()