[xaprepare] remove xamarin-android-windeps dependency (#5531)
We've been seeing the attempts to install the
`xamarin/xamarin-android-windeps/mingw-zlib` Homebrew recipe time out
on our CI servers:

	Error: Process '/usr/local/bin/brew "install" "xamarin/xamarin-android-windeps/mingw-zlib"' timed out after 00:30:00
	Error: Installation of xamarin/xamarin-android-windeps/mingw-zlib failed

Since the recipe existed only for the benefit of cross-building Mono
for Windows on macOS using mingw -- which we no longer do regularly
as of commit 0c9f83b7 -- we can remove the recipe.