[Mono.Android] Support building with API-10 (#1613)
Commit ab3773cf [broke the build][0]:

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/972/

	Xamarin.Android.Design/ILayoutBindingClient.cs(15,79): error CS0246: The type or namespace name 'Fragment' could not be found (are you missing a using directive or an assembly reference?)
	Xamarin.Android.Design/LayoutBinding.cs(35,77): error CS0246: The type or namespace name 'Fragment' could not be found (are you missing a using directive or an assembly reference?)
	Android.App/Activity.cs(49,94): error CS0246: The type or namespace name 'Fragment' could not be found (are you missing a using directive or an assembly reference?)
	Android.Views/View.cs(87,114): error CS0234: The type or namespace name 'Fragment' does not exist in the namespace 'Android.App' (are you missing an assembly reference?)
	Android.Views/View.cs(87,23): error CS0425: The constraints for type parameter 'T' of method 'View.OnLayoutFragmentNotFound<T>(int, ref T)' must match the constraints for type parameter 'T' of interface method 'ILayoutBindingClient.OnLayoutFragmentNotFound<T>(int, ref T)'. Consider using an explicit interface implementation instead.

The above C# compiler errors result when attempting to build
`src/Mono.Android` for API-10:

	$ make API_LEVEL=10
	# -or-
	$ (cd src/Mono.Android; msbuild /p:AndroidFrameworkVersion=v2.3 /p:AndroidApiLevel=10)

The problem is that API-10 doesn't contain the `Android.App.Fragment`
type, which is used in ab3773cf.

Fix things by making references to `Android.App.Fragment` conditional
on API-11+.