Revert "Bump to lipzip/rel-1-3-0/51ff59da (#863)"
This reverts commit fa9f62a113bf9fba42e39c4556b130988137b967.

Commit fa9f62a1 [broke the master build][b630]:

[b630]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/630/

	Linking C executable hole.exe
	CMakeFiles/hole.dir/objects.a(hole.c.obj):hole.c:(.text+0x77): undefined reference to `__imp_zip_error_init'
	...

Revert commit fa9f62a1 until we figure out how to properly fix it.