[build] disable roslyn analyzers within Visual Studio IDE (#5507)
If I open our `.sln` files in VS Windows, I start getting errors
about projects in `external/nrefactory` and `external/debugger-libs`:

	"Xamarin.Android.sln" (default target) (1) ->
	"tests\MSBuildDeviceIntegration\MSBuildDeviceIntegration.csproj" (default target) (53) ->
	"tests\MSBuildDeviceIntegration\MSBuildDeviceIntegration.csproj" (Build target) (53:2) ->
	"external\debugger-libs\Mono.Debugging.Soft\Mono.Debugging.Soft.csproj" (default target) (54:2) ->
	"external\debugger-libs\Mono.Debugging\Mono.Debugging.csproj" (default target) (56:3) ->
	"external\nrefactory\ICSharpCode.NRefactory\ICSharpCode.NRefactory.csproj" (default target) (57:3) ->
	(CoreCompile target) ->
	    external\nrefactory\ICSharpCode.NRefactory\Documentation\XmlDocumentationProvider.cs(122,38): error CA3075: XmlTextReader instance created with insecure default settings.
	    external\nrefactory\ICSharpCode.NRefactory\Documentation\XmlDocumentationProvider.cs(134,52): error CA3075: XmlTextReader instance created with insecure default settings.
	    external\nrefactory\ICSharpCode.NRefactory\Documentation\XmlDocumentationProvider.cs(362,39): error CA3075: XmlTextReader instance created with insecure default settings.
	    external\nrefactory\ICSharpCode.NRefactory\Documentation\XmlDocumentationProvider.cs(399,30): error CA3075: XmlTextReader instance created with insecure default settings.

To workaround the issue, I could try:

	cd external/nrefactory ; git clean -dxf;
	cd ../debugger-libs ; git clean -dxf;
	msbuild Xamarin.Android.sln -t:Restore

However, it breaks again if I open a `.sln` file in the IDE.

I moved the MSBuild logic from `Directory.Build.props` into
`RoslynAnalyzers.projitems`, which is conditionally imported by
`Configuration.props`.  This appears to solve the issue, as we will
only import the analyzers for projects that import
`Configuration.props`.

I looked to see if we could fix NRefactory itself, but the
[Github repo is archived][0]!

[0]: https://github.com/icsharpcode/NRefactory/tree/0607a4ad96ebdd16817e47dcae85b1cfcb5b5bf5