Revert "[monodroid] Add java-interop sources to build (#1675)"
This reverts commit 88ef36b85272206103e2013e4a8a3e061843d7c9.

Commit 88ef36b8 broke the [full master build][0] because the
`java-interop` sources don't build under Windows:

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1010/

	"/Users/builder/android-toolchain/mxe-b9cbb53/bin/x86_64-w64-mingw32.static-gcc" -o "…/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/lib/host-mxe-Win64/libmono-android.debug.dll" ...
	/var/folders/x8/jnqh86dn7t90f9wccp0g0hqh0000gn/T//ccpnkdsJ.o: In function `ji_realpath': (TaskId:1201)
	…/xamarin-android/external/Java.Interop/src/java-interop/java-interop-gc-bridge-mono.c:158: undefined reference to `realpath'
	collect2 : error : ld returned 1 exit status […/xamarin-android/src/monodroid/monodroid.csproj]

Revert the inclusion of `java-interop` sources until they're buildable
under MXE/Windows.