Bump to dotnet/installer/main@3b43390 (#6131)
Changes: https://github.com/dotnet/installer/compare/cc10fae...3b43390
Changes: https://github.com/mono/linker/compare/6eae019...0cb9250
Changes: https://github.com/dotnet/runtime/compare/d019e70...cf52b7e

Updates:

* Microsoft.Dotnet.Sdk.Internal: from 6.0.100-rc.1.21376.3 to 6.0.100-rc.1.21379.2
* Microsoft.NET.ILLink.Tasks: from 6.0.100-preview.6.21370.1 to 6.0.100-preview.6.21378.1
* Microsoft.NETCore.App.Ref: from 6.0.0-rc.1.21374.7 to 6.0.0-rc.1.21378.2

Bump to Mono.Cecil 0.11.4. 

Hopefully fixes a [build break][0]:

	CSC : error CS1705: Assembly 'illink' with identity 'illink, Version=6.0.100.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
	uses 'Mono.Cecil, Version=0.11.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'
	which has a higher version than referenced assembly
	'Mono.Cecil' with identity 'Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'

Bump `$(MonoCecilVersion)` to compensate?

Note: an actual fix very likely requires a Java.Interop bump, as
Java.Interop references Cecil 0.11.3 (same as the error message)
while `$(MonoCecilVersion)` is 0.11.2 (not present in the error).

[0]: https://github.com/xamarin/xamarin-android/pull/6131#pullrequestreview-716413727

Context: https://github.com/xamarin/xamarin-android/pull/6131#pullrequestreview-716413727
Context: fcb9ea3

Changes: http://github.com/xamarin/Java.Interop/compare/4fb7c147f8c6eb9bf94d9bfb8305c7d2a7a9fb33...dd1ef455ee4fbfa7e17f34c51cbe2ef24459e2e6

  * xamarin/java.interop@dd1ef45: Bump to mono/linker@b888d67 Mono.Cecil 0.11.4 (#861)

Commit fcb9ea3 didn't fix the build breakage.

Bump to xamarin/java.interop@dd1ef45 and set
`$(_XamarinAndroidCecilVersion)`, which will override the Mono.Cecil
NuGet package version within the Java.Interop build.

This will hopefully ensure/allow everything to now use Cecil 0.11.4.

TODO: This Quick-And-Dirty approach hardcodes
`$(_XamarinAndroidCecilVersion)`=0.11.4, meaning we now have two
different properties for the same thing:

	Directory.Build.props:    <MonoCecilVersion>0.11.4</MonoCecilVersion>
	build-tools/scripts/Configuration.Java.Interop.Override.props:    <_XamarinAndroidCecilVersion>0.11.4</_XamarinAndroidCecilVersion>

This is "undesirable".  Is there a way to update `xaprepare` so that
we can generate `external/Java.Interop/Configuration.Override.props`
so that `$(_XamarinAndroidCecilVersion)`=`$(MonoCecilVersion)`?

(Assuming that this approach even works…)

Co-authored-by: Jonathan Pryor <jonpryor@vt.edu>