[Xamarin.Android.Build.Tasks] Use $(AndroidLatestApiLevel) (#560)
`src/Xamarin.Android.Build.Tasks` uses some *generated* files from
`src/Mono.Android`. Unfortunately, whether those files exist or not
depends on the value of `$(AndroidApiLevel)` and
`$(AndroidFrameworkVersion). For example, the
`Android.Views.LayoutDirection` enum was added in API-17, so if you
build *only* API 16 from a "clean" environment:

	$ git clean -xdf .
	$ make prepare
	$ xbuild Xamarin.Android.sln /p:AndroidApiLevel=16 /p:AndroidFrameworkVersion=v4.1
	# ...

Then [the build fails][0] because `Android.Views.LayoutDirection.cs`
[cannot be found][1]:

	CSC: error CS2001: Source file '.../xamarin-android/src/Xamarin.Android.Build.Tasks/../../src/Mono.Android/obj/Debug/android-16/mcw/Android.Views.LayoutDirection.cs' could not be found.

To improve build reliability, update the
`src/Xamarin.Android.Build.Tasks` project to instead rely on
`src/Mono.Android` build outputs based on the new
`$(AndroidLatestApiLevel)` MSBuild property, which corresponds to the
prior `$(AndroidLatestFrameworkVersion)` property (de6d8ef7).

If the required files don't exist, the new `_GenerateMonoAndroidEnums`
target will invoke `<MSBuild/>` on `Mono.Android.csproj` to cuase the
files to be created.

This allows the build system to be more reliable, ensuring that the
files which `Xamarin.Android.Build.Tasks.csproj` actually exist,
regardless of the possibly overridden values of the
`$(AndroidApiLevel)` and `$(AndroidFrameworkVersion)` properties.

[0]: https://gitter.im/xamarin/xamarin-android?at=58f23ee98e4b63533dcfcc60
[1]: https://pastebin.com/ha7Y0hjC