[Microsoft.Android.Sdk] fix $(AndroidUseSharedRuntime) w/ linker (#4911)
The `XA0119` test was failing under a `dotnet` context:

    (_BuildApkEmbed target) ->
        System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\A\_work\1\s\bin\TestRelease\temp\XA0119\obj\Debug\linked\shrunk\UnnamedProject.dll'.
        at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
        at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
        at Xamarin.Android.Tasks.MonoAndroidHelper.IsReferenceAssembly(String assembly)
        at Xamarin.Android.Tasks.BuildApk.AddAssemblies(ZipArchiveEx apk, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo)
        at Xamarin.Android.Tasks.BuildApk.ExecuteWithAbi(String[] supportedAbis, String apkInputPath, String apkOutputPath, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo)
        at Xamarin.Android.Tasks.BuildApk.RunTask()
        at Xamarin.Android.Tasks.AndroidTask.Execute()

This appears to be caused by using the linker and
`$(AndroidUseSharedRuntime)` at the same time.

It turns out that the `_RemoveRegisterAttribute` MSBuild task is not
run at all in this `Condition`:

    <Target Name="_RemoveRegisterAttribute"
      Condition="'$(AndroidLinkMode)' != 'None' AND '$(AndroidUseSharedRuntime)' != 'true'">

And so we were passing a list of assemblies in a `shrunk` directory
that did not exist. We need to update the `<ProcessAssemblies/>`
MSBuild task to check the same condition.

After doing this, I could add two more tests under the `dotnet` context.