[xaprepare] fix workload install on Linux (#6012)
Currently, `make prepare` fails on Linux with:

	System.Exception: Duplicate workload manifest microsoft.net.workload.mono.toolchain
	    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.RefreshWorkloadManifests()
	    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver..ctor(IWorkloadManifestProvider manifestProvider, String[] dotnetRootPaths, String[] currentRuntimeIdentifiers)
	    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion)
	    at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userHome, String tempDirPath, String version)
	    at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.<get_SubCommands>b__9_0(ParseResult appliedOption)
	    at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
	    at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args)
	    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
	    at Microsoft.DotNet.Cli.Program.Main(String[] args)

Which is the result of:

	$ ls -la ~/android-toolchain/dotnet/sdk-manifests/6.0.100/
	total 36
	drwxr-xr-- 9 codespace codespace 4096 Jun  9 13:25 .
	drwxr-xr-x 3 codespace codespace 4096 Jun  9 13:25 ..
	drwxr-xr-- 2 codespace codespace 4096 Jun  9 13:25 microsoft.net.sdk.android
	drwxr-xr-- 2 codespace codespace 4096 Jun  9 13:25 microsoft.net.sdk.ios
	drwxr-xr-- 2 codespace codespace 4096 Jun  9 13:25 microsoft.net.sdk.maccatalyst
	drwxr-xr-- 2 codespace codespace 4096 Jun  9 13:25 microsoft.net.sdk.macos
	drwxr-xr-- 2 codespace codespace 4096 Jun  9 13:25 microsoft.net.sdk.tvos
	drwxr-xr-- 2 codespace codespace 4096 Jun  9 13:25 microsoft.net.workload.mono.toolchain
	drwxr-xr-x 2 codespace codespace 4096 Jun  9 13:25 Microsoft.NET.Workload.Mono.ToolChain

Our code in `Step_InstallDotNetPreview.cs` needs to use a lowercase
path for `microsoft.net.workload.mono.toolchain`

After doing this, the build was able to get past this point.