[xaprepare] Add Disk information to output (#6711)
Sometimes a CI build will fail due to insufficient disk space:

	System.IO.IOException: No space left on device
	   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
	   at System.IO.FileStream.FlushWriteBuffer()
	   …

What we *don't* know is how much free space there was in the first
place, or how much space we've consumed during the build.

Update `xaprepare` to print out the current disk space usage at the
beginning of the build.  This output will be visible from the
**make jenkins** step output.

macOS will print out `df -h` output:

	=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	Detecting operating system
	=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	

	     OS type: Darwin
	   OS flavor: macOS
	     OS name: Mac OS X
	  OS release: 10.15.7 (19H2)
	     OS bits: x86_64
	   CPU count: 12
	   Disk Info: 
	Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
	/dev/disk1s1   466Gi   10Gi  267Gi     4%  488254 4881964626    0%   /
	devfs          186Ki  186Ki    0Bi   100%     642          0  100%   /dev
	/dev/disk1s6   466Gi  178Gi  267Gi    40% 2099549 4880353331    0%   /System/Volumes/Data
	/dev/disk1s4   466Gi  2.0Gi  267Gi     1%       2 4882452878    0%   /private/var/vm
	/dev/disk1s5   9.3Gi  7.8Gi  1.5Gi    84%     346   97655934    0%   /Volumes/BotDeploy
	map auto_home    0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
	/dev/disk1s3   466Gi  504Mi  267Gi     1%      50 4882452830    0%   /Volumes/Recovery

Linux will print out `df -h` output:

	=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	Detecting operating system
	=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


	     OS type: Linux
	   OS flavor: Debian
	     OS name: Ubuntu
	  OS release: 20.04
	     OS bits: x86_64
	   CPU count: 8
	   Disk Info: 
	Filesystem      Size  Used Avail Use% Mounted on
	/dev/root        84G   55G   29G  66% /
	devtmpfs         16G     0   16G   0% /dev
	tmpfs            16G   12K   16G   1% /dev/shm
	tmpfs           3.2G  1.1M  3.2G   1% /run
	tmpfs           5.0M     0  5.0M   0% /run/lock
	tmpfs            16G     0   16G   0% /sys/fs/cgroup
	/dev/loop0       62M   62M     0 100% /snap/core20/1328
	/dev/sda15      105M  5.2M  100M   5% /boot/efi
	/dev/loop2       68M   68M     0 100% /snap/lxd/21835
	/dev/loop1       44M   44M     0 100% /snap/snapd/14549

Windows will use the values from [`System.IO.DriveInfo`][0]:

	=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	Detecting operating system
	=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
	
	Visual Studio detected in C:\Program Files\Microsoft Visual Studio\2022\Enterprise
	MSBuild detected at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
	
	     OS type: Windows
	   OS flavor: Windows 10
	     OS name: Microsoft Windows 10 [Version 10.0.20348]
	  OS release: 10.0.20348
	     OS bits: x86
	   CPU count: 8
	   Disk Info: 
	Drive	TotalSize	AvailableFreeSpace
	C:\	256GB	105GB

[0]: https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo?view=net-6.0