[Xamarin.Android.Build.Tasks] cast with `as` for GetRegisteredTaskObject
Context: https://github.com/jonathanpeppers/Xamarin.Legacy.Sdk

When working on an experiment that enables multi-targeting such as:

  <Project Sdk="Xamarin.Legacy.Sdk">
    <PropertyGroup>
      <TargetFrameworks>monoandroid11.0;net6.0-android</TargetFrameworks>
    </PropertyGroup>
  </Project>

I got the build error:

    Xamarin.Android.Aapt2.targets(123,3): error MSB4018: The "Aapt2Compile" task failed unexpectedly.
    System.InvalidCastException: [A]Xamarin.Android.Tasks.Aapt2Daemon cannot be cast to [B]Xamarin.Android.Tasks.Aapt2Daemon. Type A originates from 'Xamarin.Android.Build.Tasks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Build.Tasks.dll'. Type B originates from 'Xamarin.Android.Build.Tasks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.win-x64\11.0.200-ci.master.22\tools\Xamarin.Android.Build.Tasks.dll'.
      at Xamarin.Android.Tasks.Aapt2Daemon.GetInstance(IBuildEngine4 engine, String aapt2, Int32 numberOfInstances, Int32 initalNumberOfDaemons, Boolean registerInDomain)
      at Xamarin.Android.Tasks.Aapt2.Execute()
      at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
      at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

This fails because we are doing an explicit cast instead of using the
`as` keyword. An `Aapt2Daemon` instance from the VS location of
`Xamarin.Android.Build.Tasks.dll` cannot be used from the .NET 6
location of the assembly.

I also added some extension methods that include the current
`Assembly.Location` in the key:

* `RegisterTaskObjectAssemblyLocal()`
* `GetRegisteredTaskObjectAssemblyLocal()`
* `UnregisterTaskObjectAssemblyLocal()`

I audited all `GetRegisteredTaskObject()` calls in this repo, and
added comments for the three tasks the usage seemed appropriate.

These all would be able to be shared between assemblies:

* `<ResolveAndroidTooling/>` uses the path to `aapt2` as a key and
  stores `System.Version` in the value.
* `<ResolveJdkJvmPath/>` uses `JavaSdkPath` as the key and stores the
  string `JdkJvmPath` in the value.
* `<ValidateJavaVersion/>` uses the path to java/javac as the key and
  stores a string in the value.