[xaprepare] Remove mingw installation formula (#5210)
Context: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4145754&view=results

All of our macOS test jobs are currently blocked during environment
provisioning due to the following error:

	stderr | Error: Calling Installation of mingw-w64 from a GitHub commit URL is disabled! Use 'brew extract mingw-w64' to stable tap on GitHub instead.

	Failed to install some required programs.
	System.InvalidOperationException: Failed to install some required programs.
	  at Xamarin.Android.Prepare.OS.EnsureDependencies ()
	  at Xamarin.Android.Prepare.OS.Init ()
	  at Xamarin.Android.Prepare.Context.Init (System.String scenarioName)
	  at Xamarin.Android.Prepare.App.Run (System.String[] args)

@grendello will be looking at a more sustainable fix, but this should
hopefully unblock PR builds for the time being.