[Xamarin.Android.Build.Tasks] Handle duplicate Resources for Resource.Designer.cs (#3077)
Context: https://github.com/xamarin/monodroid/runs/120750052
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2654120

Android allows developers to provide [alternate resources][0], which
are resource directories with a `-<config-qualifier>` suffix.
For example, `Resources\drawable-hdpi` would contain high-DPI
drawable resources, which can differ from `Resources\drawable`.
As a result you can have duplicate resource entries.  In the case of
`style`-able items we were trying to use a dictionary to keep track
of the items which we need to generate id's for.

Unfortunately `ManagedResourceParser` didn't support the existence of
such "duplicate" resource ids; the `Dictionary<TKey, TValue>.Add()`
method thus threw when a "duplicate" was encountered:

	System.ArgumentException: An item with the same key has already been added.
	   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
	   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
	   at Xamarin.Android.Tasks.ManagedResourceParser.ProcessStyleable(XmlReader reader)
	   at Xamarin.Android.Tasks.ManagedResourceParser.ProcessXmlFile(String file)
	   at Xamarin.Android.Tasks.ManagedResourceParser.ProcessResourceFile(String file)
	   at Xamarin.Android.Tasks.ManagedResourceParser.Parse(String resourceDirectory, IEnumerable`1 additionalResourceDirectories, Boolean isApp, Dictionary`2 resourceMap)
	   at Xamarin.Android.Tasks.GenerateResourceDesigner.Execute()
	   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
	   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

This wasn't immediately obvious, because it was generated from an
MSB4018 *warning*; the "obvious error" was a Designer test failure:

	1) Failed : Xamarin.AndroidDesigner.Tests.FixtureSetup
	  C:\…\Resources\layout\activity_main.axml
	  Expected: no item equal to "MockView"
	  But was:  < "DrawerLayout", "RelativeLayout", "MockView", "FrameLayout", "MockView" >

*Because* the `<GenerateResourceDesigner/>` had an unhandled
exception, `activity_main.axml` wasn't updated as expected.  This was
because we had already created a `CodeMemberField` for the resource
id and added it to the dictionary.

What we *need* to do is instead skip over items which have already
been added.

Another problem with `ManagedResourceParser` was the order in which
we generated the `style`-able items.  Adding the new
`MultiSelectListPreference` item caused `ManagedResourceParser` to
produce different results.  It turns out that Android does some
sorting on the values and fields it produces for `Styleable` items.

Given the following xml declaration

	<declare-styleable name="MultiSelectListPreference">
	  <attr name="entries"/>
	  <attr name="android:entries"/>
	  <attr name="entryValues"/>
	  <attr name="android:entryValues"/>
	</declare-styleable>

the following is produced in the `R.txt` file.

	int[] styleable MultiSelectListPreference { 0x010100b2, 0x010101f8, 0x7f030001, 0x7f030002 }
	int styleable MultiSelectListPreference_android_entries 0
	int styleable MultiSelectListPreference_android_entryValues 1
	int styleable MultiSelectListPreference_entries 2
	int styleable MultiSelectListPreference_entryValues 3

Note that the items are ordered alphabetically and NOT by the order
in which they appear in the xml.  This needs to be done BEFORE we
actually generate or lookup the actual id values for these items.
This is so they have the correct `index` into the
`MultiSelectListPreference` array.

This commit also fixes up this issue.

Unit test has been modified to take into account these new scenarios.

[0]: https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources