[Xamarin.Android.Tools.BootstrapTasks] Import Configuration.props
Fix a [build break][0] introduced from 57cf8ca7:

		Xamarin.Android.Tools.BootstrapTasks/Zip.cs(9,15): error CS0234:
		The type or namespace name `Tools' does not exist in the namespace
		`Xamarin'. Are you missing an assembly reference?

Indeed, it *is* missing an assembly reference, to `libZipSharp.dll`,
because `libZipSharp.csproj` couldn't be resolved:

	Microsoft.Common.targets:  warning : Referenced Project /libZipSharp.csproj not found, ignoring.

Add an `<Import/>` for `Configuration.props` so that the
`$(LibZipSharpSourceFullPath)` MSBuild property is available.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/56/