[Java.Interop] JniPeerMembers shouldn't require that Java types exist.
Java.Interop is intended to be used with Xamarin.Android, which binds
the Android Java APIs. An artifact of this is that Android has
"API levels", in which new types and members will be added to
successive versions of Android.

It is desirable (required) to be able to use a binding for API Y on a
device running API X, X < Y. (For example, use a binding for API-23 on
a device running API-10.) This in turn requires the ability to
instantiate JniPeerMembers instances for types that may not exist:

	var members = new JniPeerMembers ("android/app/Fragment", typeof (Fragment));

android.app.Fragment was added in API-11, so if the above statement is
executed on an API-10 device, IT MUST NOT THROW [0].

(Why? Because JniPeerMembers will be invoked from a static
constructor, and there have been instances where new base classes were
introduced, e.g. in API-8 android.view.MotionEvent inherited from
java.lang.Object, while in API-9 MotionEvent inherited from the new
android.view.InputEvent type. Thus, when using an API-10+ binding on
an API-8 device, the InputEvent static constructor *will* execute,
even though the InputEvent type *doesn't exist*.)

Fix JniPeerMembers so that it doesn't instantiate the JniType unless
it actually needs to. If no other JniPeerMembers members are used,
then the JniType won't be created, and no runtime error will occur.

[0] 1) Test Error : Java.InteropTests.JniPeerMembersTests.Ctor_CanReferenceNonexistentType
   Java.Interop.JavaException : __this__/__type__/__had__/__better__/__not__/__Exist__
  ----> Java.Interop.JavaException : __this__.__type__.__had__.__better__.__not__.__Exist__
  at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x00049] in .../Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:3231
  at Java.Interop.JniType..ctor (System.String classname) [0x00008] in .../Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:31
  at Java.Interop.JniType.GetCachedJniType (Java.Interop.JniType& cachedType, System.String classname) [0x0002f] in .../Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:92
  at Java.Interop.JniPeerMembers.get_JniPeerType () [0x0000d] in .../Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:75
  at Java.Interop.JniPeerMembers+JniInstanceMethods..ctor (Java.Interop.JniPeerMembers members) [0x0002b] in .../Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:12
  at Java.Interop.JniPeerMembers..ctor (System.String jniPeerType, System.Type managedPeerType, Boolean checkManagedPeerType) [0x000c1] in .../Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:53
  at Java.Interop.JniPeerMembers..ctor (System.String jniPeerType, System.Type managedPeerType) [0x00000] in .../Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:10
  at Java.InteropTests.JniPeerMembersTests.Ctor_CanReferenceNonexistentType () [0x00010] in .../Java.Interop/src/Java.Interop/Tests/Java.Interop/JniPeerMembersTests.cs:15
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr5/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.5/mcs/class/corlib/System.Reflection/MonoMethod.cs:230
  --- End of managed Java.Interop.JavaException stack trace ---
java.lang.NoClassDefFoundError: __this__/__type__/__had__/__better__/__not__/__Exist__
Caused by: java.lang.ClassNotFoundException: __this__.__type__.__had__.__better__.__not__.__Exist__
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

--JavaException

  --- End of managed Java.Interop.JavaException stack trace ---
java.lang.ClassNotFoundException: __this__.__type__.__had__.__better__.__not__.__Exist__
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)