Remove GeneratedCode Attribute
It causes

```
__Microsoft.Android.Resource.Designer.cs(15,3,15,16): error CS0579: Duplicate 'GeneratedCode' attribute
```