[Xamarin.Android.Build.Tasks] fix Android Wear incremental builds (#3569)
* [Xamarin.Android.Build.Tasks] fix Android Wear incremental builds

Fixes: https://github.com/xamarin/xamarin-android/issues/3562

Our QA tests caught a regression where building a Xamarin.Android app
that includes an embedded Android Wear app would always rebuild.

This brought up a few things:

1. We have a `XamarinAndroidWearApplicationProject` class, but no
   tests using it?
2. What does our MSBuild targets even do for Wear projects?

~~ Tests ~~

In adding some tests, I had to fix a few other things:

* We should use the 1.0.0 Xamarin.Android.Wearable NuGet instead of
  `preview7`.
* `Xamarin.ProjectTools` was generating `csproj` files of an encoding
  that did not match:

    C:\src\xamarin-android\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\Xamarin.Android.Common.targets(423,2): error MSB4018: The "ParseAndroidWearProjectAndManifest" task failed unexpectedly.
        System.Xml.XmlException: There is no Unicode byte order mark. Cannot switch to Unicode.
        at System.Xml.XmlTextReaderImpl.Throw(Exception e)
        at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
        at System.Xml.XmlTextReaderImpl.CheckEncoding(String newEncodingName)
        at System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(Boolean isTextDecl)
        at System.Xml.XmlTextReaderImpl.Read()
        at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
        at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
        at System.Xml.Linq.XDocument.Load(String uri)
        at Xamarin.Android.Tasks.ParseAndroidWearProjectAndManifest.Execute()
        at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
        at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\src\xamarin-android\bin\TestDebug\temp\BundledWearApp\MyApp\MyApp.csproj]

The file was actually `utf-8` but we were generating:

    <?xml version="1.0" encoding="utf-16"?>

I reworked `Xamarin.ProjectTools` to fix this.

I was able to add a simple test that just build a wear project, and
then added a second test that reproduces the problem.

~~ The Problem ~~

Generally embedded Android Wear solutions:

* A main app references the Wear project.
* The main app grabs a few files from the Wear project: the APK and an
  xml configuration file and copies them into `obj\Debug\res`.

What was even weirder, since we put them in `@(AndroidResource)` the
`_GenerateAndroidResourceDir` MSBuild target would attempt to copy
these files to themselves. The same files paths were in
`@(_AndroidResolvedResources)` and `@(_AndroidResourceDest)`...

    <CopyIfChanged
        SourceFiles="@(_AndroidResolvedResources)"
        DestinationFiles="@(_AndroidResourceDest)"

The problem was we basically were copying these files and never adding
them to `@(_ModifiedResources)`. This meant that
`$(_AndroidResFlagFile)` was not `<Touch/>`'d in some cases:

    <Touch
        Files="$(_AndroidResFlagFile)"
        AlwaysCreate="True"
        Condition=" !Exists ('$(_AndroidResFlagFile)') Or '@(_ModifiedResources)' != '' Or '@(_AndroidResourceDestRemovedFiles)' != '' "
    />

Two fixes seemed to solve the issue:

* The `<PrepareWearApplicationFiles/>` task needs to return a
  `ModifiedFiles` output we can add to `@(_ModifiedResources)`.
* We should define the Wear files in `@(_AndroidResourceDest)` after
  the `<CopyIfChanged/>` call such as:

    <_AndroidResourceDest Include="@(_WearableApplicationDescriptionFile);@(_BundledWearApplicationApkResourceFile)" />

This way they are never part of `@(AndroidResource)`, since they are
auto-generated.