[generator] Fix xamarin-android/src/Mono.Android build (#972)
Context: e48c48c802d24cf7abffc7db0e9f82d9e1804036
Context: https://github.com/xamarin/xamarin-android/pull/6939

xamarin/xamarin-android#6939 attempted to bump to 0575eb81, which
promptly broke the build of src/Mono.Android, e.g.
`src/Mono.Android/obj/Debug/net6.0/android-32/mcw/Android.Widget.GridLayout.cs`:

	/*       */ partial class GridLayout {
	/*       */     partial class partial class LayoutParams {
	/*       */         [Register ("rowSpec")]
	/*       */         public Android.Widget.GridLayout.Spec? RowSpec {
	/*       */             get {
	/*       */                 const string __id = "rowSpec.Landroid/widget/GridLayout$Spec;";
	/*       */                 var __v = _members.InstanceFields.GetObjectValue (__id, this);
	/*       */                 return global::Java.Lang.Object.GetObject<Android.Widget.GridLayout.Spec> (__v.Handle, JniHandleOwnership.TransferLocalRef);
	/*       */             }
	/*       */             set {
	/*       */                 const string __id = "rowSpec.Landroid/widget/GridLayout$Spec;";
	/*       */                 IntPtr native_value = global::Android.Runtime.JNIEnv.ToLocalJniHandle (value);
	/*       */                 try {
	/* L 239 */                     _members.InstanceFields.SetValue (__id, this, new JniObjectReference (value));
	/*       */                 } finally {
	/* L 242 */                     global::Android.Runtime.JNIEnv.DeleteLocalRef (value);
	/*       */                 }
	/*       */             }
	/*       */         }
	/*       */     }
	/*       */ }

due to compilation errors:

	src/Mono.Android/obj/Debug/net6.0/android-32/mcw/Android.Widget.GridLayout.cs(239,77):
	  error CS1503: Argument 1: cannot convert from 'Android.Widget.GridLayout.Spec' to 'System.IntPtr'
	src/Mono.Android/obj/Debug/net6.0/android-32/mcw/Android.Widget.GridLayout.cs(242,54):
	  error CS1503: Argument 1: cannot convert from 'Android.Widget.GridLayout.Spec' to 'System.IntPtr'

This was caused by `BoundFieldAsProperty.cs` not appropriately
setting `arg` to `native_arg`, so that the correct variable would be
cleaned up in the `finally` block.

There was another set of errors:

	src/Mono.Android/obj/Release/net6.0/android-32/mcw/Android.Widget.ArrayAdapter.cs(525,53):
	  error CS1503: Argument 1: cannot convert from 'Java.Lang.ICharSequence[]' to 'string[]?'

which was also caused by e48c48c8 mis-refactoring
`SourceWriterExtensions.cs`, and overlooking the entire existence of
the `CharSequence.ArrayToStringArray()` method (oops).

Update `generator` so that xamarin-android once again builds, and add
unit tests to hit these particular code paths.