[Mono.Android] Ignore CS1584, CS1658 documentation warnings (#5651)
Commit a7413a23 updated the non-PR `src/Mono.Android` build to import
Android Javadoc comments and translate them into C# XML documentation
comments when building on CI for non-PR branches, or locally when
the `$(IncludeAndroidJavadoc)` MSBuild property is True:

	cd src/Mono.Android
	msbuild /restore /v:diag /p:IncludeAndroidJavadoc=True

This translation is buggy and incomplete, e.g. it emits `<see/>`
elements, but doesn't translate the `//see/@cref` value from Java:

	/// <c><see cref="#getChildStaticTransformation(View, android.view.animation.Transformation)" /></c> to be

This results in an additional 40k+ warnings on our main CI, a'la:

	obj/Debug/netcoreapp3.1/android-30/mcw/Android.Views.ViewGroup.cs(5047,21):
	warning CS1584: XML comment has syntactically incorrect cref attribute '#getChildStaticTransformation(View, android.view.animation.Transformation)' 
	obj/Debug/netcoreapp3.1/android-30/mcw/Android.Views.ViewGroup.cs(5047,21):
	warning CS1658: Identifier expected. See also error CS1001.

This is why a7413a23 ignored multiple C# XML documentation warnings.

Update `$(NoWarn)` to also ignore CS1584 and CS1658 warnings.
This will hopefully bring the number of warnings reported on CI down
to a more manageable level.