[java-runtime] Preload `libmono-native.so` while initializing XA (#4861)
Fixes: https://github.com/xamarin/xamarin-android/issues/4772
Fixes: https://github.com/xamarin/xamarin-android/issues/4852

Context: https://issuetracker.google.com/issues/36950617

Fixes apply to the the **Release** builds on Android 5.x devices.

A Xamarin.Android application contains multiple native libraries:

	$ adb shell pm list packages -f | grep -i hello
	package:/data/app/com.xamarin.android.helloworld-_-zYezFQQsuaiegto4HlCw==/base.apk=com.xamarin.android.helloworld

	$ adb shell ls /data/app/com.xamarin.android.helloworld-_-zYezFQQsuaiegto4HlCw==/lib/arm64
	…
	libmono-native.so
	libmonosgen-2.0.so
	…

Native libraries may have dependencies, e.g. `libmono-native.so`
depends on `libmonosgen-2.0.so` in order to load.

Once Upon A Time, Android's native linker was "not helpful" when
loading native libraries through **dlopen**(3): it wouldn't use the
library's directory to resolve dependencies, and thus
`dlopen("libmono-native.so")` would fail.

[This limitation was (mostly) fixed in Android 4.3 (API-18)][0], but
a variation of this limitation is also present on some Android 5.x
devices (API-21, API-22) when running *64-bit apps*.  For example, if
a C# API call requires loading `libmono-native.so`, then on these
devices the load will fail, as `libmonosgen-2.0.so` can't be found --
which is rather unexpected, as `libmonosgen-2.0.so` is *already*
loaded (!) -- which results in an app crash:

	UNHANDLED EXCEPTION:
	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. --->
		System.TypeInitializationException: The type initializer for 'PanCardView.Droid.CardsViewRenderer' threw an exception. --->
		System.TypeInitializationException: The type initializer for 'System.Random' threw an exception. --->
		System.DllNotFoundException: libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)
	  at (wrapper managed-to-native) Interop+Sys.GetNonCryptographicallySecureRandomBytes(byte*,int)
	  at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) <0x7f86c3bbf0 + 0x0001b> in <39e41a681ea94f00bcc87fb130853dc2>:0 
	  at System.Random.GenerateGlobalSeed () <0x7f86cb33f0 + 0x00017> in <39e41a681ea94f00bcc87fb130853dc2>:0 
	  at System.Random..cctor () <0x7f86cb3690 + 0x0000b> in <39e41a681ea94f00bcc87fb130853dc2>:0 
	  …

The problem is that the Android dynamic linker on these devices fails
to properly interpret the internal library name (so-called `SONAME`,
contained in the `DT_SONAME` field in the ELF executable header) when
checking whether the library is already loaded in the process memory.
Failing that check, the loader proceeds to look for the library
**file** on the disk/storage medium in the predefined paths.  Since
`libmonosgen-2.0.so` and other libraries are not found in those paths,
the search fails and the linker returns an error.

Later versions of Android fix the bug in that the `DT_SONAME` field
is used to properly look up already loaded shared libraries and thus
the dependency resolution succeeds.

The solution here is to use the `System.loadLibrary()` Java API to
preload `libmono-native.so`, as the Java API is able to figure out
that the dependent libraries are found in the same directory and load
them to satisfy the requirements.

[0]: https://issuetracker.google.com/issues/36950617