[Java.Interop, Java.Base] Fix xamarin-android integration issues (#929)
Context: https://github.com/xamarin/xamarin-android/pull/6549
Context: https://github.com/xamarin/java.interop/compare/35195527a8835f92f28261cfa0d139a75b5512fe...d0996b0e73b99aaccff566e60dfa8c215174ac4e

When attempting to bump xamarin-android from 35195527 to d0996b0e,
the build failed for a number of reasons, including because d0996b0e
added a "duplicate" type `Java.Interop.JavaTypeParametersAttribute`,
which caused unit tests to fail:

	error CS0433: The type 'JavaTypeParametersAttribute' exists in both
	'Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' and
	'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

The plan was to use type forwarders for this type from
`Mono.Android.dll` to `Java.Interop.dll`, but in retrospect this
sounds like a potential "forward-incompatible ABI break" (aad96bf2),
as assemblies built against the newer `Mono.Android.dll` (with type
forwarders) won't be usable on previous Xamarin.Android SDKs.

Make `JavaTypeParametersAttribute` conditional on `NET`, so that it's
only included in .NET 6 builds.  .NET SDK for Android will then use
type forwarders, which won't be an issue as there's no previous .NET
release to be forward compatible with.

Update `tests/generator-Tests` so that `JavaTypeParametersAttribute`
is once again provided for non-`NET` builds.

Additionally, commit e8cd6ed2 enabled `$(TreatWarningsAsErrors)`=True,
which had an inadvertent side effect of preventing VS2019 from
building the Java.Interop repo, as warning CS8032 is now an error:

	error CS8032: An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from
	C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll :
	Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
	or one of its dependencies.
	The system cannot find the file specified.

As it happens, the xamarin-android Windows PR builds are on VS2019,
and thus promptly broke.

Fix this error by adding CS8032 to `$(NoWarn)`, and updating various
`.csproj` files so that the `$(NoWarn)` in `Directory.Build.props`
is used everywhere needed.

Finally, update `Java.Base.targets` so that it looks for
`class-parse.dll` and `generator.dll` from `$(UtilityOutputFullPath)`
*not* `$(ToolOutputFullPath)`.  `class-parse.csproj` and
`generator.csproj` both set `$(OutputPath)` to
`$(UtilityOutputFullPath)`, and the correct path must be used in
order for `Java.Base.targets` to find the required utilities.