[One .NET] fix design-time builds (#4925)
Design-time builds were not working as expected under a `dotnet`
context, mostly due to differences in build ordering.

`dotnet` design-time builds would fail with:

    Xamarin.Android.Common.targets(577,2): Could not locate MonoAndroid SDK.

Reviewing the `_ResolveMonoAndroidSdks` MSBuild target, it depends on
values that the `_ResolveSdks` provides.

After updating `$(_ResolveMonoAndroidSdksDependsOn)` to include
`_ResolveSdks`, I hit:

    Xamarin.Android.Common.targets(716,2): error MSB4044: The "GetAndroidDefineConstants" task was not given a value for the required parameter "AndroidApiLevel".

`$(_AndroidApiLevel)` was blank, which is provided by the
`_ResolveAndroidTooling` target.

After updating `$(_ResolveMonoAndroidSdksDependsOn)` again, I hit:

    CSC error CS2001: Source file 'C:\src\xamarin-android\bin\TestDebug\temp\BuildAppWithManagedResourceParser\App1\obj\Release\Resource.designer.cs' could not be found.

It turns out using `$(AndroidUseIntermediateDesignerFile)` breaks
design-time builds. We set this by default for .NET 5+. The fix here
was to make the `_RemoveLegacyDesigner` target not run when
`$(ManagedDesignTimeBuild)` is true.

After these changes, I could add the `dotnet` category to a few tests
around design-time builds.