[build] on Windows, kill processes before zipping test results
Context: https://build.azdo.io/3142932

Builds have been occasionally failing with:

    build-tools\Xamarin.Android.Tools.BootstrapTasks\result-packaging.targets(79,5): Error MSB4018: The "Zip" task failed unexpectedly.
    System.IO.IOException: The process cannot access the file 'E:\A\_work\214\a\xa-test-results-10.1.99.28_62cd0ab-Windows-Release\temp\XA5213IsRaisedWhenOutOfMemoryErrorIsThrown\build.log' because it is being used by another process.

We are using a "kill lingering process" task before the build, but I
think we should also use it at the end of the build in
`upload-results.yaml`.