Bump to xamarin/Java.Interop/master@f7d97c23
Changes: https://github.com/xamarin/Java.Interop/compare/be581591d0a995c740600be3ceefd0c3351dd0dd...f7d97c233c70712409d1c07ecef3a0c277e4f57d

Context: https://github.com/xamarin/java.interop/pull/459

Updates `generator` so that all bound Java interfaces also implement
`IJavaPeerable` in addition to `IJavaObject`, for eventual future
C#8 Default Interface Member support.

[generator] Remove extraneous slash when creating .projitems.

[generator] Always use XAPeerMembers for XAJavaInterop1

Drop dependency on DylibMono when building for Xamarin.Android

[jnienv-gen] fix p/invoke usage for .NET framework

Add `jnimarshalmethod-gen.exe -r ASSEMBLY` option.

Improve support for binding package-private interfaces.

Parse EnclosingMethod, SourceFile annotation blobs.

Emit events for addListener(Listener,Handler) pattern

Fix `jnimarshalmethod-gen.exe`-related build error:

	Instance property 'PeerReference' is not defined for type 'Android.Widget.IListAdapter'
	Parameter name: propertyName
	System.ArgumentException: Instance property 'PeerReference' is not defined for type 'Android.Widget.IListAdapter'
	Parameter name: propertyName
	    at System.Linq.Expressions.Expression.Property (System.Linq.Expressions.Expression expression, System.String propertyName)
	    at Java.Interop.JavaPeerableValueMarshaler.CreateIntermediaryExpressionFromManagedExpression (Java.Interop.Expressions.JniValueMarshalerContext context, System.Linq.Expressions.ParameterExpression sourceValue)
	    at Java.Interop.JavaPeerableValueMarshaler.CreateReturnValueFromManagedExpression (Java.Interop.Expressions.JniValueMarshalerContext context, System.Linq.Expressions.ParameterExpression sourceValue)

Fix DylibMono build issues which prevented `src/monodroid` from
building.