[monodroid] Fix the Windows build.
Commit 9621be1d [broke the Windows build][0]:

	xamarin-android/src/monodroid/jni/android-system.cc(862,86): error G9AB2EBAB: invalid static_cast from type 'char**' to type 'const wchar_t*'
	xamarin-android/src/monodroid/jni/android-system.cc(865,16): error G5FFED110: invalid conversion from 'const void*' to 'void*'

This was overlooked because normal PR builds don't build for Windows,
so the `static_cast<const wchar_t*>(&libmonoandroid_directory_path)`
wasn't ever actually compiled, hence the G9AB2EBAB error.  (Doh!)

Replace the `static_cast` with a `reinterpret_cast` to fix the build.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1213/