Bump to xamarin/xamarin-android-tools/master@66d445c (#423)
Context: http://build.devdiv.io/2532642
Context: https://github.com/xamarin/xamarin-android-tools/compare/9e78d6e...66d445c

When building Java.Interop on Windows as part of xamarin-android, the
build fails:

	warning MSB3274: The primary reference "E:\A\_work\1345\s\external\xamarin-android-tools\bin\Release\Xamarin.Android.Tools.AndroidSdk.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.7.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1". [E:\A\_work\1345\s\external\Java.Interop\build-tools\Java.Interop.BootstrapTasks\Java.Interop.BootstrapTasks.csproj]
	...
	Java.Interop.BootstrapTasks\JdkInfo.cs(14,19): error CS0246: The type or namespace name 'Xamarin' could not be found (are you missing a using directive or an assembly reference?) [E:\A\_work\1345\s\external\Java.Interop\build-tools\Java.Interop.BootstrapTasks\Java.Interop.BootstrapTasks.csproj]
	Java.Interop.BootstrapTasks\JdkInfo.cs(12,7): error CS0246: The type or namespace name 'Xamarin' could not be found (are you missing a using directive or an assembly reference?) [E:\A\_work\1345\s\external\Java.Interop\build-tools\Java.Interop.BootstrapTasks\Java.Interop.BootstrapTasks.csproj]

This happens because `$(TargetFrameworkVersion)` in
`Java.Interop.BootstrapTasks.csproj` is lower than that of
`Xamarin.Android.Tools.AndroidSdk.csproj`, which is v4.7.1, done in
xamarin/xamarin-android-tools/master@66d445c4.  As part of this
change, anything referencing `Xamarin.Android.Tools.AndroidSdk.csproj`
needs to be using a `$(TargetFrameworkVersion)` of `v4.7.1`.

Bump the `$(TargetFrameworkVersion)` value within
`Java.Interop.BootstrapTasks.csproj` to v7.4.1 to fix the build
failure on xamarin-android/Windows.