Bump to xamarin/java.interop/jcw-interfaces@05f41ebd
Context: https://github.com/xamarin/java.interop/issues/590

Without the Java.Interop bump, fails with:

  obj/Debug/android/src/crc64eadbb4d7d7a577cd/JI590.java(4,8): javac error JAVAC0000:  error: JI590 is not abstract and does not override abstract method invoke(MyRunnable) in InvokeRunnable [/Volumes/Xamarin-Work/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]
obj/Debug/android/src/crc64eadbb4d7d7a577cd/JI590.java(4,8): javac error JAVAC0000: public class JI590 [/Volumes/Xamarin-Work/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]
obj/Debug/android/src/crc64eadbb4d7d7a577cd/JI590.java(4,8): javac error JAVAC0000:  [/Volumes/Xamarin-Work/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]
  obj/Debug/android/src/crc64eadbb4d7d7a577cd/JI590.java(29,14): javac error JAVAC0000:  error: name clash: invoke(Runnable) in JI590 and invoke(MyRunnable) in InvokeRunnable have the same erasure, yet neither overrides the other [/Volumes/Xamarin-Work/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]
obj/Debug/android/src/crc64eadbb4d7d7a577cd/JI590.java(29,14): javac error JAVAC0000: 	public void invoke (java.lang.Runnable p0) [/Volumes/Xamarin-Work/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]
obj/Debug/android/src/crc64eadbb4d7d7a577cd/JI590.java(29,14): javac error JAVAC0000:  [/Volumes/Xamarin-Work/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]