[Xamarin.Android.Build.Tasks] Disable layout bindings
Context: https://github.com/xamarin/xamarin-android/issues/1669

The layout bindings and associated Code-Behind (ab3773cf)
infrastructure is breaking existing projects, e.g. the
[Cheesesquare sample][0] [fails to build][1] with:

[0]: http://github.com/xamarin/monodroid-samples/tree/master/android5.0/Cheesesquare
[1]: https://github.com/xamarin/xamarin-android/issues/1669#issuecomment-388163599

	error CS0234: The type or namespace name 'Android' does not exist in the namespace 'Cheesesquare'

This is apparently happening because the wrong namespace is used for
the generated `Resource` type, with generated code containing:

	public TextView Text1 => FindView (global::Cheesesquare.Android.Resource.Id.Text1, ref __Text1);

There is no `Cheesesquare.Android.Resource` type; the generated
`Resource.designer.cs` file contains `Cheesesquare.Resource`.

Disable layout binds for now, until it can become more stable.