[Java.Interop.Tools.Cecil] Fix the xamarin-android build
Context: https://github.com/xamarin/xamarin-android/pull/5945
Context: https://github.com/xamarin/xamarin-android/blob/d5ef9982dc7b9efc22f7efb80ed0b58ff0bd7cdb/src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj#L43-L46

Xamarin.Android's `Microsoft.Android.Sdk.ILLink.dll` assembly uses
`TypeDefinitionCache`, but doesn't reference the
`Java.Interop.Tools.Cecil.dll` assembly.  Instead, it references some
of the sources in `src/Java.Interop.Tools.Cecil`, and *no* sources for
any of `Java.Interop.Tools.Cecil.dll`s dependencies, such as
`Java.Interop.Tools.Diagnostics.dll`.

This meant that while commit 4c7c0dc8 built for Java.Interop, it
broke the xamarin-android build, by introducing an (unnecessary)
`using Java.Interop.Tools.Diagnostics` into `TypeDefinitionCache.cs`:

	…/TypeDefinitionCache.cs(4,26): error CS0234: The type or namespace name 'Diagnostics' does not exist in the namespace 'Java.Interop.Tools' (are you missing an assembly reference?)
	[…/xamarin-android/src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj]

The `using Java.Interop.Tools.Diagnostics` wasn't actually needed;
it was part of an unnecessary tangent.

Remove the `using Java.Interop.Tools.Diagnostics` statement, allowing
the xamarin-android build to progress.