[Java.Interop.Tools.JavaCallableWrappers] Fix IsValidIdentifier() (#610)
Context: https://github.com/xamarin/xamarin-android/pull/4431

Commit 269dcbd9 added `IdentifierValidator.IsValidIdentifier()`,
replacing use of `CSharpCodeProvider.IsValidIdentifier()`, and this
change caused a unit test failure within xamarin-android:

	// Xamarin.Android.Build.Tests.BuildTest.GeneratorValidateEventName
	obj/Debug/generated/src/Com.Xamarin.Testing.Test.cs(350,29,350,32): error CS1001: Identifier expected

The line in question?

	public event EventHandler 123 {

Oops.

It Turns Out™ that `IdentifierValidator.IsValidIdentifier("123")`
returned True, so we attempted to create an event named `123`, which
the C# compiler Does Not Like.

Fix `IdentifierValidator.IsValidIdentifier()` by using a new
`IsValidIdentifierRegex` regex to match against identifiers, instead
of attempting to reuse the `validIdentifier` regex, which matches for
*invalid* characters (it negates the match via `[^...]`), and thus
cannot differentiate between "starting" characters and everything
else, which is fine for `IdentifierValidator.CreateValidIdentifier()`,
but not for `IdentifierValidator.IsValidIdentifier()`.

Add unit tests for `IdentifierValidator.IsValidIdentifier()`.

Update `make run-test-generator-core` tests so that we add a
`View.setOn123Listener()` method, which prior to this commit would add
a `View.123` event:

	partial class View {
	  public event EventHandler 123 {
	    add { … }
	    remove { … }
	  }
	}

With a corrected `IdentifierValidator.IsValidIdentifier()`, this event
is no longer generated.