Branching for d16-11; Bump $(ProductVersion) to 11.4.0 (#6015)
Xamarin.Android v11.4.0 will be shipped as part of
Visual Studio 2019 16.11 Preview 3 and subsequent releases.

Changes: https://github.com/xamarin/monodroid/compare/76c04cd15eca7afc269a6d26296e9d2db6f79be2...fab2d0b3e5205cb97d03e7a33a367245dbd211aa

  * xamarin/monodroid@fab2d0b3e: Branching for d16-11. (#1209)


Update `azure-pipelines.yaml` so that the macOS Designer Tests use
the xamarin/UITools/d16-10 branch, *not* the default d16-11 branch.
Using the UITools/d16-11 branch results in build errors:

	/Users/runner/work/1/s/UITools/Designer/external/Xamarin.PropertyEditing/Xamarin.PropertyEditing.Mac/Controls/BaseDateTimeEditorControl.cs(2,7):
	error CS0246: The type or namespace name 'AppKit' could not be found (are you missing a using directive or an assembly reference?)
	[/Users/runner/work/1/s/UITools/Designer/external/Xamarin.PropertyEditing/Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj]
	…plus 931 other errors…


Finally, constrain mono to v6.12.0.137 by updating
`$(MonoRequiredMaximumVersion)`.  This is done to "work around" some
unit test errors we observed because xamarin/xamarin-android#6014 had
updated the system mono:

	226) Error : Xamarin.Android.Build.Tests.SingleProjectTest.AndroidManifestProperties
	System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.NET.StringTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
	   at Microsoft.Build.Evaluation.Expander`2.MetadataExpander.ExpandMetadataLeaveEscaped(String expression, IMetadataTable metadata, ExpanderOptions options, IElementLocation elementLocation)
	   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/msbuild-15/src/Build/Evaluation/Expander.cs:line 414
	   …

Limiting system mono to 6.12.0.137 prevents these errors.