[Xamarin.Android.Build.Tasks] Preserve Binding constructor (#1653)
When an application with generated bindings is built in Release
configuration all assemblies linked, the *constructor* for the
binding classes may be removed by the linker as they are instantiated
via `Activator.CreateInstance()` and not directly.  Consequently,
the `Activity.SetContentView<T>()` method may cause a
`MissingMethodException` to be thrown as the constructor is missing:

	System.MissingMethodException: Constructor on type 'Binding.activity_main' not found.
	  at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark)
	  at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes)
	  at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture)
	  at Android.App.Activity.SetContentView[T] ()
	  at Example.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState)
	  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState)

Prevent this from happening by decorating the binding constructor
with `[Preserve(Conditional=true)]`, which tells the linker to keep
the constructor if the declaring type is also preserved.