[Mono.Android] Include JavaNativeTypeManager.ToJniName()
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3261114&view=logs&j=65486226-8c87-5153-e73a-d57909d6ac16&t=0c4ab8a2-b502-54b1-2c2d-58f1af7b0279

The Designer tests failed!

	System.NotSupportedException: Cannot create instance of type 'Android.Runtime.UncaughtExceptionHandler': no Java peer type found.
	  at Java.Interop.JniPeerMembers+JniInstanceMethods..ctor (System.Type declaringType) [0x00046] in <9cb9a310e5034526b407c7688775bf95>:0
	  at Java.Interop.JniPeerMembers+JniInstanceMethods.GetConstructorsForType (System.Type declaringType) [0x00031] in <9cb9a310e5034526b407c7688775bf95>:0
	  at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x00038] in <9cb9a310e5034526b407c7688775bf95>:0
	  at Java.Lang.Object..ctor () [0x0001f] in /Users/runner/runners/2.160.1/work/1/s/src/Mono.Android/obj/Release/android-28/mcw/Java.Lang.Object.cs:30
	  at Android.Runtime.UncaughtExceptionHandler..ctor (Java.Lang.Thread+IUncaughtExceptionHandler defaultHandler) [0x00000] in /Users/runner/runners/2.160.1/work/1/s/src/Mono.Android/Android.Runtime/UncaughtExceptionHandler.cs:14
	  at Android.Runtime.JNIEnv.Initialize (Android.Runtime.JnienvInitializeArgs* args) [0x00159] in /Users/runner/runners/2.160.1/work/1/s/src/Mono.Android/Android.Runtime/JNIEnv.cs:156

...which was rather odd.  Why couldn't the Java peer type be found?

The answer is that `AndroidRuntime.GetSimpleReferences()` *used to* call
`JNIEnv.GetJniName(Type)`, which in turn would call
`JavaNativeTypeManager.ToJniName(Type)`, which was really only useful on
Desktop environments.

The "updated" `AndroidRuntime.GetSimpleReferences()` stopped calling
`JNIEnv.GetJniName()`, in order to fix one of the Java.Interop unit tests,
which also meant that it stopped calling `JavaNativeTypeManager.ToJniName()`.
This is why `UncaughtExceptionHandler` could not be found.

When on desktop, continue calling `JavaNativeTypeManager.ToJniName()`.