[Xamarin.Android.Build.Tasks] Build-tools r30 requires JDK11
Context: https://issuetracker.google.com/issues/150189789

Update the "legacy" `<ValidateJavaVersion/>` task to require JDK11
when using Build-tools r30, because `apksigner.jar` in Build-tools
r30.0.0-rc4 requires JDK11 to execute.

For example, see [this build][0] for PR #4735, which fails because
JDK 1.8 is used with Build-tools r30's apksigner.jar:

	Task "AndroidApkSigner"
	  Task Parameter:ApkSignerJar=C:\Users\dlab14\android-toolchain\sdk\build-tools\30.0.0-rc4\lib\apksigner.jar
	  …
	  Task Parameter:ToolPath=C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\bin
	  Task Parameter:ManifestFile=obj\Release\android\AndroidManifest.xml
	  C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe -jar C:\Users\dlab14\android-toolchain\sdk\build-tools\30.0.0-rc4\lib\apksigner.jar sign --ks "C:\Users\dlab14\AppData\Local\Xamarin\Mono for Android\debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugkey --key-pass pass:android --min-sdk-version 21 --max-sdk-version 29  "C:\A\vs2019xam00000Y-1\_work\1\s\bin\TestRelease\temp\BuildAotApplication AndÜmläüts_x86_64_True_True\bin\Release\UnnamedProject.UnnamedProject-Signed.apk"
	  java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	  at java.lang.ClassLoader.defineClass1(Native Method)
	  …
	…\Xamarin.Android.Common.targets(2559,2): error MSB6006: "java.exe" exited with code 1.

This was "implicitly" the case before commit a2b827e1, because
`$(AndroidSdkBuildToolsVersion)` couldn't be parsed, and thus
`$(LatestSupportedJavaVersion)` was being checked for, which caused
all the Designer and Windows unit tests to fail.

Commit a2b827e1 fixed those failures, at the cost of allowing
`apksigner.jar` use with JDK 1.8, which isn't correct.

Fix the Build-tools + JDK version semantics within
`<ValidateJavaVersion/>`.  This will "re-break the world."

To attempt to address *some* of that breakage, update the macOS
Designer unit tests to export the `$(JavaSdkDirectory)` environment
variable.  This will hopefully cause the Designer build system to use
the JDK11 install that xamarin-android provisions, thus avoiding an
XA0032 build error.

[0]: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3771781&view=ms.vss-test-web.build-test-results-tab&runId=13535824&resultId=100072&paneView=attachments