Bump to dotnet/installer/release/8.0.1xx-preview2@e2b49c7 8.0.100-preview.2.23128.9 (#7838)
Changes: https://github.com/dotnet/installer/compare/e3ab0b5...e2b49c7
Changes: https://github.com/dotnet/runtime/compare/ff7c19f...96c27e4
Changes: https://github.com/dotnet/emsdk/compare/d7ff0aa...7b6bae1

Updates:

* Microsoft.Dotnet.Sdk.Internal: from 8.0.100-preview.2.23123.10 to 8.0.100-preview.2.23128.9
* Microsoft.NET.ILLink.Tasks: from 8.0.0-preview.2.23123.4 to 8.0.0-preview.2.23127.9
* Microsoft.NETCore.App.Ref: from 8.0.0-preview.2.23123.4 to 8.0.0-preview.2.23127.9
* Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100-preview.2: from 8.0.0-preview.2.23113.1 to 8.0.0-preview.2.23127.1

~~ Other changes ~~

* [build] pass `--skip-sign-check` to `dotnet workload`

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7397299&view=logs&j=28f7b402-0b52-5743-3f46-b0c973acb4f8&t=06392762-0cbe-5837-5fae-a131d329206a&l=81
Context: 978b74f

Many times on release branches, parts of the .NET installer is signed,
and we need to allow unsigned workloads to be installed via the
`--skip-sign-check` flag:

    Rolling back pack Microsoft.Android.Sdk.Windows installation...
    Workload installation failed: Failed to validate package signing.
    Verifying Microsoft.Android.Sdk.Windows.34.0.0-ci.darc-release-8-0-1xx-preview2-cef50a92-f62d-4147-9b74-08689588cab8.180

This is testing a local build of the `android` workload, so it will
not be signed at this stage.

* Changes for `Microsoft.DotNet.Cecil`

Add a new feed:

    <add key="dotnet8-transport" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8-transport/nuget/v3/index.json" />

`@(PackageReference)` to `Mono.Cecil` is no longer needed.

* Update `BuildReleaseArm64XFormsDotNet.apkdesc`

    apkdiff: File 'assemblies/System.IO.Compression.dll' has changed by -878 bytes (-5.49 %). This exceeds the threshold of 5.00 %.
    Error: apkdiff: Size regression occured, 1 check(s) failed.

Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>