[xaprepare] Do less when updating Mono (#4342)
When updating Mono from an older version (e.g. 6.6) `xaprepare` can
crash as soon as the Mono package is installed with exceptions similar
to the ones below:

	System.InvalidOperationException: Failed to obtain version information from the cc compiler
	  at Xamarin.Android.Prepare.Unix.DetectCompilers () [0x00344] in build-tools/xaprepare/xaprepare/OperatingSystems/Unix.cs:102
	  at Xamarin.Android.Prepare.OS.ConfigureEnvironment () [0x00096] in build-tools/xaprepare/xaprepare/OperatingSystems/OS.cs:371
	  at Xamarin.Android.Prepare.OS.Init () [0x000e6] in build-tools/xaprepare/xaprepare/OperatingSystems/OS.cs:254
	  at Xamarin.Android.Prepare.Context.Init (System.String scenarioName) [0x0026c] in build-tools/xaprepare/xaprepare/Application/Context.cs:761
	  at Xamarin.Android.Prepare.App.Run (System.String[] args) [0x0078a] in build-tools/xaprepare/xaprepare/Main.cs:153

	System.InvalidOperationException: Unable to determine the last version change commit
	  at Xamarin.Android.Prepare.BuildInfo.DetermineLastVersionChangeCommit (Xamarin.Android.Prepare.Context context) [0x000fa] in build-tools/xaprepare/xaprepare/Application/BuildInfo.cs:130
	  at Xamarin.Android.Prepare.BuildInfo.GatherGitInfo (Xamarin.Android.Prepare.Context context) [0x0006d] in build-tools/xaprepare/xaprepare/Application/BuildInfo.cs:36
	  at Xamarin.Android.Prepare.Context.Init (System.String scenarioName) [0x00430] in build-tools/xaprepare/xaprepare/Application/Context.cs:780
	  at Xamarin.Android.Prepare.App.Run (System.String[] args) [0x0078a] in build-tools/xaprepare/xaprepare/Main.cs:153

This is most probably caused by the new Mono changing assemblies and
shared libraries underneath the older Mono which is currently
executing `xaprepare`.

In order to avoid the crash, do as little as possible to update Mono
and quit as quickly as possible.