[tests] Address breakage from using Version everywhere
Some tests now fail:

	"C:\a\_work\1\a\TestRelease\09-10_14.30.50\temp\BindFacebook\UnnamedProject.csproj" (Build target) (1:7) ->
	(_BuildAndroidGradleProjects target) ->
	  GRADLE : Script compilation error :  [C:\a\_work\1\a\TestRelease\09-10_14.30.50\temp\BindFacebook\UnnamedProject.csproj]
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.12/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: Daemon will be stopped at the end of the build
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: Calculating task graph as no cached configuration is available for tasks: Library:assembleRelease
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: w: file:///C:/a/_work/1/a/TestRelease/09-10_14.30.50/temp/BindFacebook/obj/Debug/gradle/net.android.init.gradle.kts:11:36: Type mismatch: inferred type is String? but Any was expected
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: > Configure project :Library
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: e: file:///C:/a/_work/1/a/TestRelease/09-10_14.30.50/temp/gradle/BindFacebook/Library/build.gradle.kts:7:18: The floating-point literal does not conform to the expected type Int?
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: FAILURE: Build failed with an exception.
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: * Where:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: Build file 'C:\a\_work\1\a\TestRelease\09-10_14.30.50\temp\gradle\BindFacebook\Library\build.gradle.kts' line: 7
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: * What went wrong:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: Script compilation error:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000:   Line 7:     compileSdk = 36.0
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000:                            ^ The floating-point literal does not conform to the expected type Int?
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: 1 error
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: * Try:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: > Run with --stacktrace option to get the stack trace.
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: > Run with --info or --debug option to get more log output.
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: > Run with --scan to get full insights.
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: > Get more help at https://help.gradle.org.
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000:
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: BUILD FAILED in 1m 21s
	…\Microsoft.Android.Sdk.Bindings.Gradle.targets(83,5): error XAGRDL0000: Configuration cache entry stored.

This is because of constructs such as:

	compileSdk = {XABuildConfig.AndroidDefaultTargetDotnetApiLevel}

and when `XABuildConfig.AndroidDefaultTargetDotnetApiLevel` is now
a `System.Version`, this results in 36.0 instead of 36.

Update these callsites so that `.Major` is used, so that the
`int` constraint is preserved.