[Xamarin.Android.Build.Tasks] Add Support fo Comma delimited Aliases (#4423)
Fixes: https://github.com/xamarin/xamarin-android/issues/4409

Commit d18c824c added support for `%(Aliases)`, but `%(Aliases)` can
contain a comma-separated list of names, accorind go the description
text in the Visual Studio **Properties** window:

> A comma-delimited list of aliases to this reference.

However, if you attempt to actually provide a comma-separated list of
values, a CS1002 will instead be reported:

	Resources\Resource.designer.cs(1,20,1,21): error CS1002: ; expected

because we generate the line:

	extern alias Lib1A,Lib1B;

Add support for comma delimited `%(Aliases)` metadata values so that
the generated `Resource.designer.cs` file compiles, emitting a=
separate `extern alias` per value:

	extern alias Lib1A;
	extern alias Lib1B;