Fix CS0103
  Steps/Step_PrepareExternalGitDependencies.cs(31,82): error CS0103: The name 'monoPropsFile' does not exist in the current context [/Users/vsts/agent/2.155.1/work/1/s/build-tools/xaprepare/xaprepare/xaprepare.csproj]