[Xamarin.Android.Build.Tasks] redistribute apksigner.jar
The Android SDK Build-tools 30.x currently requires JDK 11
in order to use `apksigner.jar`:

	Task "AndroidApkSigner"
	  Task Parameter:ApkSignerJar=C:\Users\dlab14\android-toolchain\sdk\build-tools\30.0.0-rc4\lib\apksigner.jar
	  …
	  Task Parameter:ToolPath=C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\bin
	  Task Parameter:ManifestFile=obj\Release\android\AndroidManifest.xml
	  C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe -jar C:\Users\dlab14\android-toolchain\sdk\build-tools\30.0.0-rc4\lib\apksigner.jar sign --ks "C:\Users\dlab14\AppData\Local\Xamarin\Mono for Android\debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugkey --key-pass pass:android --min-sdk-version 21 --max-sdk-version 29  "C:\A\vs2019xam00000Y-1\_work\1\s\bin\TestRelease\temp\BuildAotApplication AndÜmläüts_x86_64_True_True\bin\Release\UnnamedProject.UnnamedProject-Signed.apk"
	  java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	  at java.lang.ClassLoader.defineClass1(Native Method)
	  …
	…\Xamarin.Android.Common.targets(2559,2): error MSB6006: "java.exe" exited with code 1.

Since it is currently unknown when we can install a JDK 11 with Visual
Studio, instead could we compile `apksigner.jar` for Java 1.8
ourselves?

My initial thought was to find `apksigner.jar` on Maven, and we could
simply redistribute it. I could only find `apksig`, which is the
library that drives `apksigner`--not the actual command-line tool.

https://mvnrepository.com/artifact/com.android.tools.build/apksig/4.0.1

If I find the source for this library:

https://android.googlesource.com/platform/tools/apksig/

The source for `apksig` and `apksigner.jar` live in the same git
repository. For now, we can add `apksig` as a submodule and build it
ourselves.

It wasn't too hard to write a gradle script to build all of the
sources into a single, self-contained `apksigner.jar`.

Then I changed the `<ResolveAndroidTooling/>` task so it no longer was
responsible for setting `$(ApkSignerJar)` and `$(AndroidUseApkSigner)`.
I setup these properties in a similar way as we did for aapt2, r8, etc.

In a future PR, I will need to make changes to xamarin/androidtools,
so it can find and use the `apksigner.jar` bundled with
Xamarin.Android.