[Microsoft.Android.Sdk.ILLink] use linker preservation files (#5145)
Fixes: https://github.com/xamarin/xamarin-android/issues/5143
Fixes: https://github.com/xamarin/xamarin-android/issues/5166

Context: https://github.com/xamarin/xamarin-android/issues/5156

As of commit 40644d91, "One .NET" builds enable the linker, which
causes the `XASdkDeployTests.DotNetInstallAndRun(isRelease:True,…)`
unit tests to *crash on startup*:

	F monodroid: The type `Java.Lang.Throwable` is missing required instance fields! handle=0x7cf0f7175580 handle_type=0x7cf0f71755c0 refs_added=0x7cf0f71755e0 weak_handle=0x0

The cause of the crash is that the .NET 5 linker is not preserving
the `Java.Lang.Throwable.weak_handle` field (see also 130905e1?), and
the `Throwable.weak_handle` field wasn't being preserved because the
.NET 5 linker wasn't using our linker preservation list XML files.

Fix the .NET 5 linker:

 1. Add new linker preservation XML files for `Java.Inteorp.dll` &
    `Mono.Android.dll` to
    `src/Microsoft.Android.Sdk.ILLink/PreserveLists/*.xml`.

    Note that these are new files, "filtered" to contain only types
    present in `Java.Interop.dll` & `Mono.Android.dll`, unlike the
    ones in `src/Xamarin.Android.Build.Tasks/Linker/PreserveLists`.

 2. Add the linker preservation files (1) to the
    `Microsoft.Android.Sdk` NuGet package contents.

 3. Update `Microsoft.Android.Sdk.ILLink.targets` so that the linker
    preservation files are added to the `@(TrimmerRootDescriptor)`
    item group.  This item group is used by the `<ILLink/>` task
    which performs linking in a .NET 5 context.

This allows the `DotNetInstallAndRun()` test to start without printing
the `missing required instance fields` message.

***Note***: this will *not* allow the `DotNetInstallAndRun()` test to
*pass*; it merely uncovers xamarin/xamarin-android#5156!

	Unhandled Exception:
	System.ArgumentException: Cannot bind to the target method because its signature is not cmpatible with that of the delegate type.
	   at System.Delegate.CreateDelegate(Type type, Type target, String method, Boolean ignorCase, Boolean throwOnBindFailure)
	   at System.Delegate.CreateDelegate(Type type, Type target, String method)
	   at Android.Runtime.AndroidTypeManager.RegisterNativeMembers(JniType nativeClass, Type ype, String methods)
	   at Android.Runtime.JNIEnv.RegisterJniNatives(IntPtr typeName_ptr, Int32 typeName_len, ntPtr jniClass, IntPtr methods_ptr, Int32 methods_len)

This `ArgumentException` will be addressed in a later commit.