[Xamarin.Android.Build.Tasks] ManagedResourceParser & dupe `attr`s (#5111)
Context: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1184573

`aapt2` is capable of processing the following input without error,
in which `customFont` is declared twice:

	<declare-styleable name="CustomFonts">
	  <attr name="android:scrollX" />
	  <attr name="customFont" />
	  <attr name="customFont" />
	</declare-styleable>

Our `ManagedResourceParser` instead generated an exception:

	 System.ArgumentException: An entry with the same key already exists.
		at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
		at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
		at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
		at Xamarin.Android.Tasks.ManagedResourceParser.Parse(String resourceDirectory, IEnumerable`1 additionalResourceDirectories, Boolean isApp, Dictionary`2 resourceMap)
		at Xamarin.Android.Tasks.GenerateResourceDesigner.RunTask()
		at Xamarin.Android.Tasks.AndroidTask.Execute()

Rework `ManagedResourceParser` to handle these duplicate `<attr/>`
elements.

Finally, introduce a new `GenerateResourceDesigner.RTxtFile` property
which will let us specify the exact location of the `R.txt` file to
use.  This means we no longer need to rely on relative paths.