[Xamarin.Android.Build.Tasks] fix C# 8.0 support by default (#5054)
Fixes: https://github.com/xamarin/xamarin-android/issues/5049

Context: https://github.com/dotnet/roslyn/commit/12f1b8f6c17c0bcd271525b5f4db0f621944c49d#diff-125e2d8c52dd9033f9b248f79f78c3f8
Context: https://github.com/dotnet/roslyn/pull/44911#discussion_r477418327

The `BuildTest.CSharp8Features()` test was failing for me locally when
I have Visual Studio 2019 16.7.2 installed:

	Foo.cs(1,23): error CS8370: Feature 'using declarations' is not available in C# 7.3. Please use language version 8.0 or greater.

After review, it appears that a change in Roslyn's MSBuild targets
[removed `$(MaxSupportedLangVersion)`][0] and made the property\
private: `$(_MaxSupportedLangVersion)`.

After some discussion around C# 9.0:

  * It is unknown if C# 9.0 will be supported by mono/mono/2020-02.
    Some features like covariant return types and function pointers
    require runtime changes.

  * Using a build of .NET 5 rc1, `$(LangVersion)` is already being set
    to `9.0` by default.

We should just change the current behavior of:

	<MaxSupportedLangVersion Condition=" '$(MaxSupportedLangVersion)' == '' ">8.0</MaxSupportedLangVersion>

and change it to:

	<LangVersion Condition=" '$(LangVersion)' == '' ">8.0</LangVersion>

This matches [Roslyn's default behavior][1]:

.NET 5+ projects should be unaffected by this change, as they do not
import `Xamarin.Android.CSharp.targets`.

If at some point, if mono/mono/2020-02 fully supports C# 9 we can bump
this value.  Users can opt into `9.0` on their own if desired.

`BuildTest.CSharp8Features()` now passes for me locally.

[0]: https://github.com/dotnet/roslyn/commit/12f1b8f6c17c0bcd271525b5f4db0f621944c49d#diff-125e2d8c52dd9033f9b248f79f78c3f8
[1]: https://github.com/dotnet/roslyn/blob/1aeda2e94fb9371b96d4bfd94b074860064ec3d2/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L6-L21