[release/10.0.1xx-preview3] [Mono.Android] prefix `Microsoft.Android.Runtime` namespace with `_` (#9998)
Context: b217dca87cc37b374fc39d1533ee1de5f0a39744

We introduced a new `internal` type in `Mono.Android.dll`:

	namespace Microsoft.Android.Runtime;

	class ManagedValueManager : JniRuntime.JniValueManager

Causes various C# compiler errors in dotnet/maui:

	D:\src\maui\src\Essentials\src\AppActions\AppActions.shared.cs(62,28):
	error CS0234: The type or namespace name 'Content' does not exist in the namespace 'Microsoft.Android' (are you missing an assembly reference?)

To fix this, prefix the namespace with `_`.  We basically can never
introduce a `Microsoft.Android.*` namespace in `Mono.Android.dll`
without potentially breaking MAUI.