[ci] Use commandlinetools' avdmanager
Context: https://github.com/xamarin/xamarin-android/pull/4567
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3711144&view=logs&jobId=4348ab7c-72f0-52b0-44fd-6f17a16a558f&j=8556562a-ae5f-5bd1-7c4d-bf1af4b6f1e1&t=9f016295-34d3-5b55-55cb-51df877e2cc6

Usage of `avdmanager` fails under JDK 11:

	TestApks.targets(45,5): error : Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	TestApks.targets(45,5): error : 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	TestApks.targets(45,5): error : 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	TestApks.targets(45,5): error : 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	TestApks.targets(45,5): error : 	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	TestApks.targets(45,5): error : 	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
	TestApks.targets(45,5): error : Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	TestApks.targets(45,5): error : 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	TestApks.targets(45,5): error : 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	TestApks.targets(45,5): error : 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	TestApks.targets(45,5): error : 	... 5 more
	TestApks.targets(45,5): error : Process `/Users/runner/Library/Android/sdk/tools/bin/avdmanager` exited with value 1.

This is because the "normal" `tools`' `avdmanager` doesn't support
JDK 11, and has been replaced with a *new* `commandlinetools` package
whicih *does* support JDK 11.

Begin installing the `commandlinetools` SDK package, and use it for
`sdkmanager` invocations.