[Xamarin.Android.Build.Tasks] Fix Linker CS1501 errors
mono/linker@0c63b9ed *broke source compatibility*, removing the
`LinkContext.LogMessage(string, params object[])` method, which
resulted in CS1501 errors when we attempted to use it:

	Context.LogMessage ("    Stripped {0} from {1}", r.Name, fileName);
	//  Linker/MonoDroid.Tuner/StripEmbeddedLibraries.cs(30,15): error CS1501: No overload for method 'LogMessage' takes 3 arguments

Remove `FixAbstractMethodsStep.LogMessage()` -- I can't easily find
any required use of it, or overrides of it -- and use
`Context.LogMessage()` "directly".  Additionally, use C#6 interpolated
strings instead of `string.Format()` placeholders, so that
`LinkContext.LogMessage(string)` can be used.