[nativeaot] fix missing `PreserveLists\*.xml` files
Context: https://github.com/dotnet/android/commit/9bc45b58ce0641890a0a3fbd6498eac515e9555a

A `dotnet new maui` project template fails to build with:

    obj\Release\net10.0-android\android-arm64\android\src\mono\android\runtime\InputStreamAdapter.java:4: error: InputStreamAdapter is not abstract and does not override abstract method read() in InputStream
    obj\Release\net10.0-android\android-arm64\android\src\mono\android\runtime\OutputStreamAdapter.java:4: error: OutputStreamAdapter is not abstract and does not override abstract method write(int) in OutputStream

I found I could also reproduce this issue with the
`BuildBasicApplicationAppCompat()` MSBuild test.

After reviewing `.binlog` files, I found we weren't including
`PreserveLists\*.xml` files *at all* in NativeAOT, as the `Condition`
was false:

    <_PreserveLists Include="$(MSBuildThisFileDirectory)..\PreserveLists\*.xml" />
    <TrimmerRootDescriptor
        Condition=" '@(ResolvedFileToPublish->Count())' != '0' and '%(Filename)' != '' "
        Include="@(_PreserveLists)" />

9bc45b58 doesn't say why the `Condition` was added, but this was
during early .NET 5 development. Some of this code may have been
shared with Xamarin.Android back then.

We can simply remove the `Condition` to fix this, and the MSBuild test
also passes.