[jnienv-gen] Use `0`, not `NULL`.
The Android NDK <jni.h> doesn't #include a definition for NULL, so use
of NULL within Xamarin.Android results in compiler errors:

	jni.c: In function 'JavaInterop_DefineClass':
	jni.c:48:13: error: 'NULL' undeclared (first use in this function)
	  *_thrown = NULL;
	             ^

Use `0` instead of `NULL` to fix these errors.