[One .NET] add $(AndroidGenerateResourceDesigner) property (#6224)
Fixes: https://github.com/xamarin/xamarin-android/issues/6198

When migrating Xamarin.Android binding projects to .NET 6, one
difference is that `Resource.designer.cs` will be generated by .NET 6
class libraries.

This can result in build failures, e.g.:

	error CS0101: The namespace 'MyBinding' already contains a definition for 'Resource'

There is not currently a way to turn this off; if you try:

	dotnet build -p:AndroidUseIntermediateDesignerFile=false

Then `Resources\Resource.designer.cs` will be generated instead.
There is no way to prevent this behavior, because
`$(AndroidResgenFile)` defaults to this value.

To solve cases where you *don't* want `Resource.designer.cs` at all:

 1. Remove the `$(AndroidResgenFile)` default value.

 2. Add a new `$(AndroidGenerateResourceDesigner)` MSBuild property,
    that seems like it will be a better name for .NET 6.
    `$(AndroidGenerateResourceDesigner)` defaults to True.

 3. `$(AndroidUseIntermediateDesignerFile)` is based on
    `$(AndroidGenerateResourceDesigner)`.

This way, if a Xamarin.Android binding project is migrated to .NET 6,
the binding project can set `$(AndroidGenerateResourceDesigner)`=False
to prevent `Resource.designer.cs` from being generated, which may
prevent build failures.

I added a test and docs for the new property.