[Xamarin.Android.Build.Tasks] proguard/r8 + multidex missing rule
I recently was doing some testing, and was using the Xamarin.Forms
Shell template from Visual Studio 2019. I also added
Xamarin.Forms.Maps and enabled multi-dex + r8.

Unfortunately, the app crashed on start with:

    java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication"

Using `dexdump`, the class was indeed missing from `classes.dex`.

It feels like this should "just work"?

From some conversation on Slack, @JonDouglas tried in Android Studio;
it was adding this proguard rule automatically:

    -keep class android.support.multidex.MultiDexApplication { <init>(); }

I think we can just add this rule to `proguard_xamarin.cfg` *always*
to fix this problem. I tested non-multidex apps, and no new warnings
are popping up or anything. Xamarin.Android apps with proguard/r8 +
multidex were working by default after I made this change.

I added a test that verifies this problem is fixed.