[build] Fix AOT build (#2125)
The `make leeroy` target failed with a "file not found" exception
while attempting to invoke the `cross-arm` cross-compiler:

	[AOT] MONO_PATH="/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/src/Mono.Android/Test/obj/Release/android/assets/shrunk" MONO_ENV_OPTIONS="" /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/Darwin/cross-arm --aot=outfile=/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/src/Mono.Android/Test/obj/Release/aot/armeabi-v7a/libaot-System.dll.so,asmwriter,mtriple=armv7-linux-gnueabi,tool-prefix=/Users/builder/android-toolchain/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-,ld-flags=,llvm-path=/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/Darwin,temp-path=/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/src/Mono.Android/Test/obj/Release/aot/armeabi-v7a/System.dll /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/src/Mono.Android/Test/obj/Release/android/assets/shrunk/System.dll
	...
	error XA3001: System.AggregateException: One or more errors occurred. ---> 
	  System.AggregateException: One or more errors occurred. ---> 
	  System.ComponentModel.Win32Exception: ApplicationName='/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/Darwin/cross-arm', CommandLine='…', CurrentDirectory='/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/src/Mono.Android/Test',
	    Native error= Cannot find the specified file

The reason for this was that `cross-arm` was never built, because
commit 9abbfc44 removed `armeabi` builds, which built `cross-arm`.

Fix these errors by adding `armeabi-v7a` to `$(ALL_AOT_ABIS)`, which
will cause `cross-arm` to once again be built.

Additionally, modify the `.apk` tests to:

  * Target Android API-22 to maintain uniformity across tests and
    also to make sure that the code which determines location of the
    on-device test result files returns the same location for all the
    tests - it relies on APIs introduced in API level 19)
  * Request external storage permissions.  This ensures that we can
    create the test result files in a location that's publicly
    accessible.  If access to external storage is denied our test
    code will create the results file in the application data
    directory and on Android 28 the file will be only readable by
    owner, thus making `adb pull` fail to download it.
  * Update the `<Adb/>` task so that it *no longer* is a `ToolTask`,
    because we want to be able to *ignore* `adb` errors, and
    `ToolTask` doesn't appear to have a way to ignore the exit value.