Bump to dotnet/installer/release/6.0.1xx-preview5@14d786c 6.0.100-preview.5.21281.3 (#5963)
Changes: https://github.com/dotnet/installer/compare/74b69d2...14d786c
Changes: https://github.com/mono/linker/compare/7a5c445...dd761f7
Changes: https://github.com/dotnet/runtime/compare/691c12b...ef54ee2

Microsoft.Dotnet.Sdk.Internal
 From Version 6.0.100-preview.5.21275.1 -> To Version 6.0.100-preview.5.21281.3

Dependency coherency updates

Microsoft.NET.ILLink.Tasks
 From Version 6.0.100-preview.5.21264.1 -> To Version 6.0.100-preview.5.21278.1

Microsoft.NETCore.App.Ref
 From Version 6.0.0-preview.5.21270.12 -> To Version 6.0.100-preview.5.21280.5

* [tests] fix AbiNameInIntermediateOutputPath test

Context: https://github.com/xamarin/xamarin-android/commit/6034f6f35552f67dd872f00857b7a4edacda66e8

.NET 6 is no longer bringing in .NET 6 linux .so files that used to trigger the warning:

    warning XA4301: Cannot determine ABI of native library 'C:\src\xamarin-android\packages\sqlitepclraw.lib.e_sqlite3.linux\1.1.11\runtimes\linux-arm64\native\libe_sqlite3.so'.

We can simply remove an assert that was looking for this.

I suspect this is related to improvements in NuGet, such as:

https://github.com/NuGet/NuGet.Client/commit/10274281c37e9dd3626938757f7e947d649b821b

* [tests] fix CustomLinkDescriptionPreserve test

Context: https://www.nuget.org/packages/SQLitePCLRaw.bundle_green/2.0.3

The `CustomLinkDescriptionPreserve` test builds an Android application
that references a `netstandard2.0` library. The `netstandard2.0`
library has a dependency on `sqlite-net-pcl`.

One improvement here is now `SQLitePCLRaw.lib.e_sqlite3.android` is
brought in correctly. Unfortunately we get a crash at runtime:

    System.TypeInitializationException: TypeInitialization_Type, SQLite.SQLiteConnection
    ---> System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.provider.dynamic_cdecl, Version=2.0.3.851, Culture=neutral, PublicKeyToken=b68184102cba0b3b' or one of its dependencies.
    IO_FileName_Name, SQLitePCLRaw.provider.dynamic_cdecl, Version=2.0.3.851, Culture=neutral, PublicKeyToken=b68184102cba0b3b
    at SQLitePCL.Batteries_V2.Init() in SQLitePCLRaw.batteries_v2.dll:token 0x6000004+0x0
    at SQLite.SQLiteConnection..cctor() in SQLite-net.dll:token 0x6000020+0x16

This causes some *odd* NuGet behavior in that `netstandard2.0`,
`netcoreapp3.0`, and `monoandroid8.0` dependencies are brought in:

    Task ResolvePackageAssets
    ...
    RuntimeCopyLocalItems
        ~\.nuget\packages\sqlite-net-pcl\1.7.335\lib\netstandard2.0\SQLite-net.dll
        ~\.nuget\packages\sqlitepclraw.bundle_green\2.0.3\lib\netcoreapp3.0\SQLitePCLRaw.batteries_v2.dll
        ~\.nuget\packages\sqlitepclraw.bundle_green\2.0.3\lib\netcoreapp3.0\SQLitePCLRaw.nativelibrary.dll
        ~\.nuget\packages\sqlitepclraw.core\2.0.3\lib\netstandard2.0\SQLitePCLRaw.core.dll
        ~\.nuget\packages\sqlitepclraw.lib.e_sqlite3.android\2.0.3\lib\monoandroid80\SQLitePCLRaw.lib.e_sqlite3.android.dll
        ~\.nuget\packages\sqlitepclraw.provider.e_sqlite3\2.0.3\lib\netstandard2.0\SQLitePCLRaw.provider.e_sqlite3.dll

And yet we're missing `SQLitePCLRaw.provider.dynamic_cdecl`?

I don't quite understand what's happening here, due to how complicated
the dependency graph is here. For now changing the workaround to
include `SQLitePCLRaw.provider.dynamic_cdecl` instead of
`SQLitePCLRaw.lib.e_sqlite3.android` is sufficient to fix this test.

Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>