Revert "[generator] fix NRE encountered when binding AndroidX (#396)" (#400)
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-builder-release/140/

This reverts commit c75b8245bfcc34bc011ce9be3b4d0630645f66b8.

I neglected to test this change in `Mono.Android.csproj`!

	obj\Debug\android-28\mcw\Java.Time.Temporal.ChronoUnit.cs(284,50): error CS0234: The type or namespace name 'ITemporal' does not exist in the namespace 'Java.Time.Temporal' (are you missing an assembly reference?) [C:\Users\jopepper\Desktop\Git\xamarin-android\src\Mono.Android\Mono.Android.csproj]
	obj\Debug\android-28\mcw\Java.Time.Temporal.ChronoUnit.cs(284,99): error CS0234: The type or namespace name 'ITemporal' does not exist in the namespace 'Java.Time.Temporal' (are you missing an assembly reference?) [C:\Users\jopepper\Desktop\Git\xamarin-android\src\Mono.Android\Mono.Android.csproj]
	obj\Debug\android-28\mcw\Java.Time.Temporal.ChronoUnit.cs(299,56): error CS0234: The type or namespace name 'ITemporal' does not exist in the namespace 'Java.Time.Temporal' (are you missing an assembly reference?) [C:\Users\jopepper\Desktop\Git\xamarin-android\src\Mono.Android\Mono.Android.csproj]
	obj\Debug\android-28\mcw\Java.Time.Temporal.ValueRange.cs(113,72): error CS0234: The type or namespace name 'ITemporalField' does not exist in the namespace 'Java.Time.Temporal' (are you missing an assembly reference?) [C:\Users\jopepper\Desktop\Git\xamarin-android\src\Mono.Android\Mono.Android.csproj]
	obj\Debug\android-28\mcw\Java.Time.Temporal.ValueRange.cs(128,70): error CS0234: The type or namespace name 'ITemporalField' does not exist in the namespace 'Java.Time.Temporal' (are you missing an assembly reference?) [C:\Users\jopepper\Desktop\Git\xamarin-android\src\Mono.Android\Mono.Android.csproj]

Let's revert this change, and I will look into another fix for the
AndroidX problem.  It will happen *after* we branch.