[Xamarin.Android.Build.Tasks] Add Support for '@+MyCustomId/Foo' in Resources.
Context https://devdiv.visualstudio.com/DevDiv/_workitems/edit/675510

`aapt` has support for custom id's. This allows developers
to replace `@+id/foo` with `@+FooId/foo`. Our normal
build process handles this without any problems. However
our `ManagedResourceParser` does not. It ignores them.

This PR adds support for that.

However it appears `aapt2` does NOT support this. If you
use custom ids you will end up with the following error
message.

	Error: '@+FooId/foo' is incompatible with attribute id (attr) reference.

So while we need to add support for this, users using
`aapt2` will not be able to use it.

This commit also reworks the `ManagedResourceParser` to
emit ids which match those which `aapt2` produce. The
end goal being that we can use the `ManagedResourceParser`
to generate the `Resource.designer.cs` file for both
normal builds and design time. We can then remove one
of the calls to `Aapt2Link` which should improve our
build performance.