Rationale for d16-2-with-mono-2018-08-via-31871d49
(This is an empty commit.)

The [Xamarin.Android Designer][0] is an interesting beast: it runs a
Xamarin.Android-like Java stack on desktop macOS and Windows.  A Java
process is created, and that Java process loads:

  * *Desktop* Mono via `libmonosgen-2.0.dylib` (macOS)` or
    `libmonosgen-2.0.dll` (Windows).`
  * The Xamarin.Android runtime via `libmono-android.debug.dylib`
    (macOS) or `libmono-android.debug.dll` (Windows)
  * Other Java code (to render items to the screen)
  * `Mono.Android.dll` and other user assemblies (to render items to
    the screen).

Being "interesting" means it introduces all kinds of "fun":
`libmono-android.debug.dll` needs to be built *for Windows* (which is
why there's `#if WINDOWS` within `src/monodroid`),
`libmonosgen-2.0.dll` needs to be built for Windows (not a huge
issue), and -- "equally" important but *more* important regarding the
next few paragraphs! -- `mscorlib.dll` needs to target Windows.

`mscorlib.dll` is where things get annoying.  Once Upon A Time™,
Mono's `mscorlib.dll` was platform agnostic: build it for one
platform, it would run everywhere, as it would internally perform
OS-checks to behave appropriate on Unix/Windows/etc.

That hasn't been true for awhile, but the Xamarin.Android build and
install environment still assumes it to be true.  Consequently, a
"Unix" `mscorlib.dll` is used by the Designer on Windows.  This
[*apparently* (?)][1] hasn't blown up catastrophically before, but
with the mono/2019-02 migration (b8c30f9e) we have now entered
"catastrophic" territory: [Designer integration tests on Windows][2]
may fail because `System.Native` cannot be found:

  System.TypeInitializationException: The type initializer for 'System.Console' threw an exception. ---> System.DllNotFoundException: System.Native

Given current release timeframes, @jonpryor is not confident that
d16-2 Preview 1 can ship with mono/2019-02.  (Perhaps later previews!
Just not Preview 1.)

If we can't use mono/2019-02, what about mono/2018-10, from *before*
commit b8c30f9e?  @jonpryor doesn't feel confident about mono/2018-10
*either*, because while `mscorlib.dll` may not have any
`System.Native` dependencies, `System.dll` *does*.  Furthermore,
nobody else is considering this entire "revert mono" idea, and thus
mono/2018-10 is getting (effectively) *no* release testing.

Thus, the thought experiment: Can we use mono/2018-08, as is used in
[d16-1][3]?

Let's Find Out™.

As part of this exploration, please note that the
d16-2-with-mono-2018-08-via-31871d49 branch is branched from
xamarin/xamarin-android/d16-2@31871d49.

[0]: https://docs.microsoft.com/en-us/xamarin/android/user-interface/android-designer/
[1]: https://developercommunity.visualstudio.com/content/problem/440975/xamarin-xaml-designer-still-fails.html
[2]: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2634805
[3]: https://github.com/xamarin/xamarin-android/commits/d16-1/