Use macOS d16-10 Designer tests
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4855000&view=logs&j=291ea0a5-8698-5441-8000-f7fa1e7709b7&t=6f8f21ba-ac47-54c3-4dfb-6d90f0f1c309

The macOS Designer Tests fail to *build*:

    /Users/runner/work/1/s/UITools/Designer/external/Xamarin.PropertyEditing/Xamarin.PropertyEditing.Mac/Controls/BaseDateTimeEditorControl.cs(2,7):
    error CS0246: The type or namespace name 'AppKit' could not be found (are you missing a using directive or an assembly reference?)
    [/Users/runner/work/1/s/UITools/Designer/external/Xamarin.PropertyEditing/Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj]
    …plus 931 other errors…

which is a tad "odd" in that the macS Designer Tests build and run
successfully for both d16-10 and main branches, but not d16-11.

My conjecture is that "something changed" in UITools/d16-11 to break
the macOS build.

Update the "Clone and update UITools" step for
`designer_integration_mac` and explicitly checkout the d16-10 branch.
Let's see if that improves things.