[tests] changes to get test projects building again on Windows/monodroid
Since ab3773cf, `Xamarin.Android-Tests.sln` hasn't been building on
Windows, with the following errors:

    "Mono.Android-Tests.csproj" (default target) (2) ->
        Xamarin.Android.RuntimeTests\MainActivity.cs(19,4): error CS0103: The name 'first_text_view' does not exist in the current context
        Xamarin.Android.RuntimeTests\MainActivity.cs(23,4): error CS0103: The name 'second_text_view' does not exist in the current context
        Xamarin.Android.RuntimeTests\MainActivity.cs(27,4): error CS0103: The name 'my_scroll_view' does not exist in the current context
        Xamarin.Android.RuntimeTests\MainActivity.cs(29,4): error CS0103: The name 'first_text_view' does not exist in the current context
        Xamarin.Android.RuntimeTests\MainActivity.cs(33,4): error CS0103: The name 'second_text_view' does not exist in the current context
        Xamarin.Android.RuntimeTests\MainActivity.cs(37,4): error CS0103: The name 'csharp_simple_fragment' does not exist in the current context
        Xamarin.Android.RuntimeTests\MainActivity.cs(38,4): error CS0103: The name 'csharp_partial_assembly' does not exist in the current context
        Xamarin.Android.RuntimeTests\MainActivity.cs(39,4): error CS0103: The name 'csharp_full_assembly' does not exist in the current context

Looking into it, there were several layout files that were not
specifying `AndroidBoundLayout` as the build action. Changing the build
action of `Main.axml` got `Mono.Android-Tests.csproj` building again.

Unfortunately, as I looked into `CodeBehindBuildTests.csproj`, many of
the situations where @grendel had setup conflicting types did not
compile. _For now_, it seems our best option is to resolve the conflicts
to get things to compile again. Cases where one layout had `<Button />`
and another had `<TextView />`, I just changed the layouts to use the
same type. When @grendel gets back, he can investigate and get these
tests back to what they were trying to accomplish for testing.

I am uncertain on how these projects were building on other platforms,
but similar build errors have cropped up upstream in `monodroid`:

    /Users/builder/jenkins/workspace/monodroid-pr/monodroid/external/xamarin-android/src/Mono.Android/Test/Xamarin.Android.RuntimeTests/MainActivity.cs
        MainActivity.cs(17,36): error CS0117: 'Resource.Layout' does not contain a definition for 'Main'
        MainActivity.cs(19,4): error CS0103: The name 'first_text_view' does not exist in the current context
        MainActivity.cs(23,4): error CS0103: The name 'second_text_view' does not exist in the current context
        MainActivity.cs(27,4): error CS0103: The name 'my_scroll_view' does not exist in the current context
        MainActivity.cs(29,4): error CS0103: The name 'first_text_view' does not exist in the current context
        MainActivity.cs(33,4): error CS0103: The name 'second_text_view' does not exist in the current context
        MainActivity.cs(37,4): error CS0103: The name 'csharp_simple_fragment' does not exist in the current context
        MainActivity.cs(38,4): error CS0103: The name 'csharp_partial_assembly' does not exist in the current context
        MainActivity.cs(39,4): error CS0103: The name 'csharp_full_assembly' does not exist in the current context

I'm hoping this PR will fix Windows builds and builds upstream in
`monodroid`.