Revert "[Mono.Android] Do not fallback in GetJavaToManagedType (#1886)"
This reverts commit 86c84efd1b52f0c10e0ad39fb0ab51f73f5af9a5.

Context: https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build?buildId=1950655

Commit 86c84efd was a runtime performance optimization which required
the presence and use of the `typemap.jm` file.

Unfortunately, as part of "requiring use of `typemap.jm`", we
*removed* support and use of the pre-existing
string-and-reflection-based type mapping infrastructure, and this
broke the Android Designer:

	4 [monodroid] SWITCHING CONTEXT
	INFO: Trying to load class md54908d67eb9afef4acc92753cc61471e9.CircleImageView

	[Info] MonoDroid: UNHANDLED EXCEPTION:
	[Info] MonoDroid: System.ArgumentException: Handle must be valid.
	[Info] MonoDroid: Parameter name: instance
	[Info] MonoDroid:   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method)
	[Info] MonoDroid:   at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod)
	[Info] MonoDroid:   at Java.Interop.TypeManager.GetClassName (System.IntPtr class_ptr)
	[Info] MonoDroid:   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType)
	[Info] MonoDroid:   at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c
	[Info] MonoDroid:   at Android.Runtime.JNIEnv+<>c.<CreateNativeArrayElementToManaged>b__93_9 (System.Type type, System.IntPtr source, System.Int32 index)
	[Info] MonoDroid:   at Android.Runtime.JNIEnv.GetObjectArray (System.IntPtr array_ptr, System.Type[] element_types)
	[Info] MonoDroid:   at Java.Interop.TypeManager.n_Activate (System.IntPtr jnienv, System.IntPtr jclass, System.IntPtr typename_ptr, System.IntPtr signature_ptr, System.IntPtr jobject, System.IntPtr parameters_ptr)
	[Info] MonoDroid:   at (wrapper dynamic-method) System.Object.2(intptr,intptr,intptr,intptr,intptr,intptr)
	ERROR: An exception occured while loading control md54908d67eb9afef4acc92753cc61471e9.CircleImageView
	ERROR: java.lang.reflect.InvocationTargetException
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at mono.android.SessionProjectCallback.instantiateClass(SessionProjectCallback.java:404)
		at mono.android.SessionProjectCallback.loadView(SessionProjectCallback.java:204)
		at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:337)
		at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:348)
		at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:248)
		at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
		at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)
		at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
		at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
		at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
		at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)
		at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
		at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
		at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
		at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)
		at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
		at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
		at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
		at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)
		at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
		at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
		at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
		at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
		at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
		at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
		at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
		at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:270)
		at mono.android.DesignerSession.load(DesignerSession.java:307)
		at mono.android.DesignerSession.processMessage(DesignerSession.java:675)
		at mono.android.MessageListener.executeMessage(MessageListener.java:88)
		at mono.android.MessageListener$Runner.run(MessageListener.java:44)
		at java.lang.Thread.run(Thread.java:745)

Revert commit 86c84efd so that the Designer can work once again.