[Mono.Android-Tests] Fix AndroidClientHandlerTests.cs compilation
[The build is broken][0]:

	Xamarin.Android.Net/AndroidClientHandlerTests.cs(192,21): error CS0246: The type or namespace name `CancellationTokenSource' could not be found. Are you mis sing `System.Threading' using directive?
	Xamarin.Android.Net/AndroidClientHandlerTests.cs(210,21): error CS0246: The type or namespace name `CancellationTokenSource' could not be found. Are you mis sing `System.Threading' using directive?

I'm saddened that we didn't catch this in the PR. :-(

Fix `AndroidClientHandlerTests.cs` compliation by adding the required
`using System.Threading` declaration.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/188/